### ISSUE TITLE
Allow put object with Transfer Acceleration enabled

### ISSUE THREAD

**Issue by Jasperav** [awslabs/aws-sdk-rust#1009]
### Describe the feature

I got this code, but this is using the default bucket. I want to enable transfer acceleration on this upload.

```
let upload_result = self
    .client
    .put_object()
    .bucket(&*common::properties::AWS_S3_BUCKET_NAME)
    // I am guessing this saves some money
    .storage_class(StorageClass::IntelligentTiering)
    .key(self.path)
    .body(ByteStream::from(self.content))
    .send()
    .await;
```

I also want to create a presigned URL which use transfer acceleration so that clients can benefit from the performance.

### Use Case

I want to sent out presigned URLs to clients which can upload files, it would be useful if clients benefit from transfer acceleration.

### Proposed Solution

Add another method 'accelerate' in the builder to benefit from it.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
I think you just need to set `accelerate` on the S3 Config: https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/config/struct.Builder.html#method.accelerate

```rust
let sdk_config = aws_config::load_defaults().await;
let config = aws_sdk_s3::Config::from(&sdk_config).to_builder().accelerate(true).build();
let client = aws_sdk_s3::Client::from_conf(config);
```

**Comment by Jasperav** [comment]
@jdisanti Thanks that worked out. The sad thing is I am presigning URLs for clients to upload data to and I reuse that same client for downloading data. I want TA on for clients when uploading data, but TA off when doing server related stuff. Guess I will have to create 2 clients.
