### ISSUE TITLE
Restrict file size for upload when creating presigned URLS

### ISSUE THREAD

**Issue by Jasperav** [awslabs/aws-sdk-rust#1013]
### Describe the feature

I would like to see a similar option as described here: https://stackoverflow.com/questions/13390343/s3-direct-upload-restricting-file-size-and-type and/or here: https://boto3.amazonaws.com/v1/documentation/api/1.9.42/reference/services/s3.html#S3.Client.generate_presigned_post as well as: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-PolicyConditions.

Apparently, setting a content-length-range as a 'condition' should prevent users to upload files larger than allowed. Is it possible to add that to this crate?

### Use Case

I don't want users to upload huge files

### Proposed Solution

Add another method: 
```
let presigned_result = context
    .aws_s3_client
    .put_object()
    .bucket(&*common::properties::AWS_S3_BUCKET_NAME)
    .key(path)
    .XXX // <--- Here some logic?
    .presigned(presigned)
    .await;
```

### Other Information

Maybe PUT should be changed to POST because I think only POST can handle the conditions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jmklix** [comment]
This is a cross sdk feature request, so I created an issue [here](https://github.com/aws/aws-sdk/issues/671) where progress can be tracked. Closing this issue.
