### ISSUE TITLE
Add support for batch_get_secret_value

### ISSUE THREAD

**Issue by flarocca** [awslabs/aws-sdk-rust#1017]
### Describe the feature

AWS Secretsmanaget API exposes an API to retrieve secrets in batches ([batch_get_secret_value](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_batch.html)).

This is a feature request to add support for that API

### Use Case

For a multi-tenanted api, based on some metadata of the incoming request we need to load some group of secrets for the current tenant.
Currently we are making one request per secret, as there is no support for get secret value in batches

### Proposed Solution

Add support for the aforementioned API

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
This is actually a bug. It should be there, but isn't.

**Comment by flarocca** [comment]
Thanks!

**Comment by jdisanti** [comment]
I merged a fix for this. It should go out with today's release.

**Comment by ysaito1001** [comment]
Confirmed [the method](https://docs.rs/aws-sdk-secretsmanager/1.8.0/aws_sdk_secretsmanager/struct.Client.html#method.batch_get_secret_value) is now available at `1.8.0`.
