### ISSUE TITLE
Provide paginators interop with the `futures::Stream` implementation

### ISSUE THREAD

**Issue by Veetaha** [awslabs/aws-sdk-rust#1028]
### Describe the feature

The removal of `futures::Stream` implementation in `1.0` for paginators is a breaking change for lots of our code (both public: https://github.com/elastio/ssstar/pull/125 and private).

Consider implementing `futures::Stream` for paginators again either:
- Unconditionally
- Under some cargo feature flag like `feature = "futures"`
- Via some interop crate that can convert aws SDK paginator into a `futures::Stream` implementor newtype. For example, like conversion of timestamps to `chrono` is implemented in [`aws_smithy_types_convert`](https://docs.rs/aws-smithy-types-convert/latest/aws_smithy_types_convert/date_time/index.html) crate. This is the least-preferred variant, because we'll still need to explicitly import some extension trait and call `.into_stream()` or smth like that to use the paginator as a `futures::Stream`.

Basically, we need a shared interop code so that we don't have to write [this boilerplate newtype wrapper](https://github.com/elastio/ssstar/blob/956dc3ea27e4dc072f0c4521005aeb6462b4a1b5/ssstar/src/objstore/stream.rs#L1-L52) over and over again in various places. Have a shared interop code that everyone in the open-source community can use.

### Use Case

`futures::Stream` contains a lot of useful combinators with `[Try]StreamExt` traits and also a lot of our code works with `impl futures::Stream`. It's basically the golden standard akin to `Iterator` in the ecosystem and we've been using it everywhere including with the pre-1.0 AWS SDK code.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
This is actually done and pending release: https://github.com/smithy-lang/smithy-rs/pull/3299

**Comment by rcoh** [comment]
Done! https://docs.rs/aws-smithy-types-convert/latest/aws_smithy_types_convert/stream/index.html
