### ISSUE TITLE
s3-helloworld example error.

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-sdk-rust#103]
### Version
s3-helloworld v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/examples/s3-helloworld)
├── aws-sdk-s3 v0.0.6-alpha (/Users/aaron/repos/rust/aws-sdk-rust/sdk/s3)
│   ├── aws-auth v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-auth)
│   │   ├── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http)
│   │   │   ├── smithy-types v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-types)
│   ├── aws-endpoint v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-endpoint)
│   │   ├── aws-types v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-types)
│   │   └── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http) (*)
│   ├── aws-http v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-http)
│   │   ├── aws-types v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-types) (*)
│   │   ├── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http) (*)
│   │   ├── smithy-types v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-types) (*)
│   ├── aws-hyper v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-hyper)
│   │   ├── aws-auth v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-auth) (*)
│   │   ├── aws-endpoint v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-endpoint) (*)
│   │   ├── aws-http v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-http) (*)
│   │   ├── aws-sig-auth v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-sig-auth)
│   │   │   ├── aws-auth v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-auth) (*)
│   │   │   ├── aws-types v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-types) (*)
│   │   │   ├── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http) (*)
│   │   ├── protocol-test-helpers v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/protocol-test-helpers)
│   │   ├── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http) (*)
│   │   ├── smithy-http-tower v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http-tower)
│   │   │   ├── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http) (*)
│   │   ├── smithy-types v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-types) (*)
│   ├── aws-sig-auth v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-sig-auth) (*)
│   ├── aws-types v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/aws-types) (*)
│   ├── smithy-http v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-http) (*)
│   ├── smithy-types v0.0.1 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-types) (*)
│   └── smithy-xml v0.1.0 (/Users/aaron/repos/rust/aws-sdk-rust/sdk/smithy-xml)

### AWS Services
s3

### Description
list_buckets ls successed, put_object&get_object failed!

INFO send_operation{operation="PutObject" service="s3" status="service_err" Error { code: "PermanentRedirect", message: "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

**Comment by rcoh** [comment]
Hello and thanks for the report! We need to add some special casing & better docs around this error. 

You need to set the appropriate region in your client that matches the region the bucket is in:
```rust
let conf =  s3::Config::builder().region(s3::Region::new("<region the bucket is in>")).build();
let client = s3::Client::from_conf(conf);
client.put_object(...)
```

**Comment by overheat** [comment]
It works after I chage the region in the code. Thanks.
I am wondering why the list_buckets works but put & get not, when I export region to enviroment variable like this: `export AWS_DEFAULT_REGION=ap-northeast-1`

**Comment by overheat** [comment]
> It works after I chage the region in the code. Thanks.
> I am wondering why the list_buckets works but put & get not, when I export region to enviroment variable like this:
> `export AWS_DEFAULT_REGION=ap-northeast-1`

S3
