### ISSUE TITLE
Error using credential process provider

### ISSUE THREAD

**Issue by trevorstr** [awslabs/aws-sdk-rust#1036]
### Describe the bug

I'm trying to create an `SdkConfig`, using a `CredentialProcessProvider`. However, the `credentials_provider()` function on the `SdkConfig` requires a specific `SharedCredentialsProvider` instead.

### Expected Behavior

I should be able to pass in any valid type of Credential Provider into the `credentials_provider()` function, on the `SdkConfig`.

### Current Behavior

```
mismatched types
expected `SharedCredentialsProvider`, found `CredentialProcessProvider`
```

### Reproduction Steps

1. Create a `CredentialProcessProvider`
1. Create an `SdkConfig` builder, and set the credential provider to the object from Step 1

```
let cred_proc = aws_config::credential_process::CredentialProcessProvider::new("/Users/trevor.sullivan/Downloads/aws_signing_helper credential-process --certificate xyz.crt --private-key xyz.key --profile-arn <profile_arn> --trust-anchor-arn <trust_anchor_arn> --role-arn <role_arn> --region us-east-1".to_string());
let config = aws_config::SdkConfig::builder().credentials_provider(cred_proc).build();
```

### Additional Information/Context

I configured IAM Roles Anywhere, so I can exchange an X.509 certificate for a JSON blob containing short-lived credentials. That isn't necessarily relevant though, as the program won't even compile using a credential process provider.

### Version

```text
[dependencies]
aws-config = { version = "1.1.2", features = ["behavior-version-latest"] }
tokio = { version = "1.35.1", features = ["full"] }

```
```


### Environment details (OS name and version, etc.)

MacOS Sonoma

### Logs

_No response_

**Comment by jdisanti** [comment]
In most cases, you don't want to use `SdkConfig::builder()` directly as that won't load any defaults. The config should be built this way instead:

```rust
let config = aws_config::from_env().credentials_provider(cred_proc).load().await;

// or

let config = aws_config::defaults(aws_config::BehaviorVersion::latest())
    .credentials_provider(cred_proc)
    .load()
    .await;
```

**Comment by trevorstr** [comment]
@jdisanti Thank you for the solution. However, doesn't it still seem odd that the `credentials_provider()` only supports `SharedCredentialsProvider` on `SdkConfig`? That seems arbitrarily limiting. I'd expect it to take `impl ProvideCredentials`, like `ConfigLoader` does.

<img width="358" alt="Screenshot 2024-01-11 at 3 44 58 PM" src="https://github.com/awslabs/aws-sdk-rust/assets/147647647/f6d2a1ed-5281-4bc1-bcc9-b1aae730eb37">

**Comment by jdisanti** [comment]
There is an `into_shared()` method implemented for all `ProvideCredentials` traits that can be used to convert into a SharedCredentialsProvider, so it's more of an inconvenience than an issue. Since SdkConfig isn't the recommended path, in a way, the added friction lets people know they're maybe not doing things right. But I could also see an argument for it being consistent with ConfigLoader.
