### ISSUE TITLE
Provide sigv4 apply_to_request_http1x function

### ISSUE THREAD

**Issue by mattklein123** [awslabs/aws-sdk-rust#1041]
### Describe the feature

Please provide a version of https://docs.rs/aws-sigv4/latest/aws_sigv4/http_request/struct.SigningInstructions.html#method.apply_to_request_http0x against the http 1.x crate.

I would do this PR myself and submit but I'm a little hazy on how you all want to handle the features that gate 0.x and 1.x moving forward in the future. Thank you!

### Use Case

Need to call this function with http 1.0 requests. For now I just copied the function but it would be nice to have it included.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
yeah I can add this this morning. Can you remind me of your use cases for needing to sign requests directly?

**Comment by mattklein123** [comment]
> yeah I can add this this morning. Can you remind me of your use cases for needing to sign requests directly?

Amazon Managed Prometheus.
