### ISSUE TITLE
Add a fully worked example for signing requests for API gateway

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#1047]
### Describe the issue

There are currently examples in the aws-sigv4 crate but they don't clearly articulate how to set up the end-to-end signing (e.g. obtaining credentials, producing a request, etc.

### Links

https://docs.rs/aws-sigv4/latest/aws_sigv4/http_request/index.html#example-signing-an-http-request

**Comment by ymwjbxxq** [comment]
Also, remember to add an example without 

```
let identity = Credentials::new(
    "AKIDEXAMPLE",
    "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
    None,
    None,
    "hardcoded-credentials"
```

maybe we link to https://github.com/awslabs/aws-sdk-rust/discussions/1037

**Comment by jmklix** [comment]
Closing as duplicate: https://github.com/awslabs/aws-sdk-rust/issues/948
