### ISSUE TITLE
aws-smithy-runtime 1.1.3 still relies on hyper 0.14

### ISSUE THREAD

**Issue by lcmgh** [awslabs/aws-sdk-rust#1051]
### Describe the bug

I tried to upgrade a bunch of AWS dependencies but could not complete as `aws-smithy-runtime 1.1.3` still relies on hyper 0.14.

https://crates.io/crates/aws-smithy-runtime/1.1.3/dependencies

### Expected Behavior

Rely on latest hyper v1 as the other SDKs do.

### Current Behavior

-

### Reproduction Steps

-

### Version

```text
aws-smithy-runtime = { version = "1.1.3", features = ["connector-hyper-0-14-x", "client"] }
```

### Environment details (OS name and version, etc.)

macOS Montery

**Comment by rcoh** [comment]
I'm going to close this since it's tracked here #977
