### ISSUE TITLE
Init config from SSO provider without profile file

### ISSUE THREAD

**Issue by lcmgh** [awslabs/aws-sdk-rust#1064]
### Describe the feature

Hi!

I would like to authenticate via SSO but without the need of refering to a profile that lives in `~/.aws/config`.

Instead I would like to pass over the "profile information" (region, role_arn, source_profile) programmatically:

Example profile
```rust
[profile myapp_eu-central-1]
output=json
region=eu-central-1
role_arn=arn:aws:iam::12345:role/myRole
source_profile=mycorpsso
```

Is that already feasible? If not I'd like to raise a feature request.

### Use Case

Easier SSO init without the need of creating, parsing, manipulating / maintaining profile INI files.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
try this: https://docs.rs/aws-config/latest/aws_config/sso/credentials/struct.SsoCredentialsProvider.html

**Comment by lcmgh** [comment]
thanks, I also just found it but I can't see how to pass over the value for "source_profile": https://docs.rs/aws-config/latest/aws_config/sso/credentials/struct.Builder.html

**Comment by rcoh** [comment]
Yes, you need to set the fields from source_profile directly on the builder instead of pulling them from the profile.

**Comment by jmklix** [comment]
Did you have any other questions about on how to set this up?
