### ISSUE TITLE
Expose types for Cognito Lambda triggers

### ISSUE THREAD

**Issue by mawallace** [awslabs/aws-sdk-rust#1071]
### Describe the feature

[Cognito Lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) (e.g., [define auth challenge](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-define-auth-challenge.html), [create auth challenge](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html), [verify auth challenge response](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-verify-auth-challenge-response.html)) can be used to create custom authentication workflows.

There are libraries that expose useful types for these triggers in other languages [[example](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7bd4a02ba62ede50a6198bd5b10712ae1a2fe6c8/types/aws-lambda/trigger/cognito-user-pool-trigger/create-auth-challenge.d.ts#L22)], but none that I can find in Rust.

It would be helpful to have event types for each trigger.

### Use Case

Right now, when implementing Cognito Lambda triggers in Rust, one must write their own event types which can be serialized/deserialized that match up with the trigger documentation [[example](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-define-auth-challenge.html)].

It would be much easier if these types could just be imported.

### Proposed Solution

Trigger event types could be defined as structs. An example (not fully fleshed out) for the define auth challenge trigger is shown below.

```
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
pub struct DefineAuthChallengeEvent {
  #[serde(flatten)]
  pub common: CommonParameters,

  #[serde(default)]
  pub request: DefineAuthChallengeRequest,

  #[serde(skip_serializing_if = "Option::is_none")]
  pub response: Option<DefineAuthChallengeResponse>

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
pub struct DefineAuthChallengeRequest {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub session: Vec<ChallengeResult>,
}

#[derive(Serialize, Deserialize, PartialEq, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct DefineAuthChallengeResponse {
    pub issue_tokens: bool,
    pub fail_authentication: bool,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub challenge_name: Option<ChallengeName>,
}
```

### Other Information

I can contribute to this feature, but two things are unclear to me:

1. Whether it is better to hand-write these types, or whether it is possible to automatically generate them (i.e., if there is some underlying Smithy model that can be leveraged)
2. Where these would belong (in one of the crates in this repository and which one, or maybe this doesn't belong in this repository)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
I think you're looking for https://github.com/awslabs/aws-lambda-rust-runtime potentially?

**Comment by mawallace** [comment]
That is absolutely what I was looking for (specifically [`lambda-events/src/event/cognito/mod.rs` in that repository](https://github.com/awslabs/aws-lambda-rust-runtime/blob/a4aa23ecd1d98fdba8f5a671f0959ad743bfe138/lambda-events/src/event/cognito/mod.rs#L464)).

Thank you very much!
