### ISSUE TITLE
Implement Lambda API InvokeWithResponseStream

### ISSUE THREAD

**Issue by nakedible-p** [awslabs/aws-sdk-rust#1075]
### Describe the feature

Lambda currently supports response streaming, but that's used through a separate Invoke API call called `InvokeWithResponseStream`. https://docs.aws.amazon.com/lambda/latest/api/API_InvokeWithResponseStream.html

Currently there doesn't seem to be any support for this API in the Rust SDK, even though it's supported in the Java, Python and JavaScript SDKs.

### Use Case

I need to call Lambda functions that will return more than 6 MB as a response by utilizing the response streaming feature.

### Proposed Solution

Implement the API.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by nakedible-p** [comment]
The response is `application/vnd.amazon.eventstream`. Apparently this SDK already has *some* support for that stream type, but unfortunately it's specialized for the audio stream and not this `InvokeWithResponseStream`.

https://github.com/awslabs/aws-sdk-rust/blob/963342a44e7bd7661647c86623b8d2d2b823928b/sdk/transcribestreaming/src/event_stream_serde.rs#L57

**Comment by jdisanti** [comment]
The code generator already supports event streams for APIs using the Smithy RestJson protocol, so I think this Lambda API would work. We just need to test it and add it to the allow list to let the code generator put in the actual SDK.

**Comment by gautamg795** [comment]
Hi, thanks for getting this implemented so quickly! How often do new releases get pushed to crates.io? We'd love to start using this change with Lambda ASAP. I tried to just add the repository as a Cargo dependency but found that the size of this repo makes fetches in CI extremely slow, so we'll wait for an official release to crates.io to get started.

**Comment by nakedible-p** [comment]
I am not one of the devs, but looking at the release frequency, I doubt it's going to be terribly many days since this is already in pending release: https://github.com/awslabs/aws-sdk-rust/releases

**Comment by jdisanti** [comment]
It'll go out in one of the daily releases the next time we release [smithy-rs](https://github.com/smithy-lang/smithy-rs), which should be pretty soon.

**Comment by jdisanti** [comment]
This went out in [yesterday's release](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-03-13).
