### ISSUE TITLE
Replace FluentBuilders with FluentTypedFuture

### ISSUE THREAD

**Issue by jinyoung-cs** [awslabs/aws-sdk-rust#1086]
### Describe the feature

FluentBuilders are a mechanism used to construct requests prior to being sent. FluentBuilders have two downfalls:
- Request construction is fallible and is represented by [`ConstructionFailure`](https://docs.rs/aws-smithy-runtime-api/1.1.7/aws_smithy_runtime_api/client/result/struct.ConstructionFailure.html)
- Request must be `send` which is basically just boilerplate.

### Use Case

Replacing FluentBuilders with compile-time type checks guarentee that required fields are fulfill upon request. We can await these FluentTypedFutures directly instead of using `send`. It is basically user ergonomics and safety.

### Proposed Solution

I'll use [`aws_sdk_s3::Client::create_bucket`](https://docs.rs/aws-sdk-s3/1.17.0/aws_sdk_s3/client/struct.Client.html#method.create_bucket) for example. If the create-bucket operation does not have [`bucket`](https://docs.rs/aws-sdk-s3/1.17.0/aws_sdk_s3/operation/create_bucket/builders/struct.CreateBucketFluentBuilder.html#method.bucket) set, construction will fail at runtime.

There is a popular alternative to fallible builder pattern called typed builders (See: https://crates.io/crates/typed-builder). We can remove an entire class of runtime errors with such a pattern.

Create bucket builder may look something like this:

```rust
struct Invalid;

struct CreateBucketFuture<Bucket> {
    // required
    bucket: Bucket,
    // non-required
    acl: Option<BucketCannedAcl>,
    ...
}

impl CreateBucketFuture<Bucket> {
    fn bucket(self, bucket: impl Into<String>) -> CreateBucketFuture<String> {
        let CreateBucketFuture { acl, .. } = self;
        CreateBucketFuture {
            bucket: bucket.into(),
            acl,
            ...
        }
    }

    ...
}

// note it is only implemented for `String` not `Invalid`
impl IntoFuture for CreateBucketFuture<String> {
    type Output = Result<CreateBucketOutput, SdkErrorNoConstructionError<CreateBucketError, HttpResponse>>;
    // impl Trait in type alias requires https://github.com/rust-lang/rust/issues/63063, but can be a drop in later, without breaking*
    type IntoFuture = Pin<Box<dyn Future<Output = Self::Output>>>;

    fn into_future(self) -> Self::IntoFuture {
        Box::pin(async { self.send() })
    }
}

impl Client {
    fn create_bucket(&self) -> CreateBucketFuture<Invalid> { // we could type alias here as `Invalid` might be jarring in docs
        CreateBucketFuture {
            ...
        }
    }
}

async fn test(client: Client) {
    client.create_bucket()
        .bucket("123") // guarenteed to construct
        .await // send it off without the `send`
}
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c28dd8b35a8bb3751501e968300f400d)

### Other Information

There are no major issues with the `future` aspect of this change. It can be implemented today for existing builder types with backwards and forward compatibility.

There are three major issues with the `typed` aspect of this change:

1) This cannot directly replace FluentBuilders as existing downstream consumers who already have incorrect construction will encounter compile errors; therefore, this is a breaking change. This would especially be a problem for crates which might be exercising `ConstructionFailures` in tests, though those tests could be removed entirely.
2) Although FluentBuilders adopt an owned builder pattern, taking in `self` as opposed to `&mut self`, FluentTypedFuture would be more difficult to use in branching code. This is particularly true in branching code with multiple required fields e.g. [`aws_sdk_s3::Client::copy_object`](https://docs.rs/aws-sdk-s3/1.17.0/aws_sdk_s3/client/struct.Client.html#method.copy_object) (`bucket`, `copy_source`, and `key` are required)
```rust
// bikeshedding alternative name with _foo
let request = client.copy_object_foo();
let set_bucket_first: bool = todo!();
let bucket_id: String = todo!();
let should_copy_source: bool = todo!();
let key: String = todo!();

// ! Compile error, the type returned by the first branch is different than the type returned by the second branch
// When a user sets required fields, they are changing the underlying type. Type mutations / field setting must be uniform across branches
let request = if set_bucket_first {
    request.bucket(bucket_id)
} else {
    request
};

let request = request
    .copy_source(should_copy_source)
    .key(key);

// Same issue here
let request = if !set_bucket_first {
    request
} else {
    request.bucket(bucket_id)
};
```
The counterargument to this point is that these are owned builder patterns, and the fields should be prepared beforehand. This is generally true in practice as well, but nevertheless, it is a breaking behavioral change.

3) Compile times would increase. I have heard EC2 compile times are already egregious, and typed builders could theoretically create a unique type, per sum of k combinations of required fields, per operation.
- `copy_object` for example could have 2<sup>3</sup> = 8 builders. (Sum of every combination of required fields is the sum of binomial coefficients, i.e. [Pascal's Triangle](https://en.wikipedia.org/wiki/Pascal%27s_triangle) = 2<sup>required fields</sup>). This is the pathological case.
- In practice this would be closer to `n` where `n` represents the number of required fields.

4) The source code in the generated clients would get much larger. Doc comments would need some massaging to look right without having `Invalid` misguiding users.

It's hard to say how much this would impact binary and compile times, but thought it worth mentioning.

### Acknowledgements

- [x] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jinyoung-cs** [comment]
oops just realized this is kind of a duplicate of something I already posted here: https://github.com/awslabs/aws-sdk-rust/issues/1027

**Comment by rcoh** [comment]
Yeah I don't think the typed builder pattern is realistic. I think the most realistic option there is going at it from a custom linting perspective.

The `IntoFuture` implementation, though, I think is a reasonable thing to build.

**Comment by mchoicpe-amazon** [comment]
I see. I thought it worth mentioning, but yeah. I'll close this out since https://github.com/awslabs/aws-sdk-rust/issues/1027 already captures the future implementation.
