### ISSUE TITLE
aws-sqs-sdk: receive_messages is flaky regarding timeout (at wait_time_seconds)

### ISSUE THREAD

**Issue by AvihaiSam** [awslabs/aws-sdk-rust#1094]
### Describe the bug

running vector (vector.dev) with aws_s3 source (through sqs) uses aws-sqs-sdk to poll for new messages.
It uses `loop` with their `run_once()` implementation which calls SDK's `receive_messages`

When running long enough - it has been noticed that there's not alway a timeout on `receive_messages` method even though  `wait_time_seconds` is configured properly, and the async function hangs waiting.

### Expected Behavior

wait_time_seconds must be honored.

### Current Behavior

most of the time, there's no problem, because answer is returned on time, but when it doesn't return - there's no timeout and it hangs...

### Reproduction Steps

run
```rust
loop {
  _ = sqs_client
            .receive_message()
            .queue_url("some-url")
            .max_number_of_messages(10)
            .visibility_timeout(30)
            .wait_time_seconds(15)
            .send()
            .map_ok(|res| res.messages.unwrap_or_default()) => {}
}
```

### Additional Information/Context
https://github.com/vectordotdev/vector/issues/20017

### Version

```text
vector uses sqs-sdk 1.3.0, but didn't see any big difference with latest
```

### Environment details (OS name and version, etc.)

x86

**Comment by jdisanti** [comment]
I recommend setting an [`operation_attempt_timeout`](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/config/timeout/struct.TimeoutConfigBuilder.html#method.operation_attempt_timeout) on the [timeout config](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/config/struct.Builder.html#method.timeout_config) either as a client-level config when you create the client (if this is the only operation you use it for), or using the [`config_override()`](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/client/customize/struct.CustomizableOperation.html#method.config_override) function before calling `send()`. This timeout should be a little bit longer than the `wait_time_seconds` given to the ReceiveMessage call.

I think there generally needs to be a better solution for default timeouts in the SDKs, but this hasn't been tackled yet.

**Comment by jmklix** [comment]
You can use the settings @jdisanti recommended above. We don't currently have any plans to change the default timeouts. Closing this issue
