### ISSUE TITLE
Implement `Eq` and `Hash` for `aws_sdk_ec2::types::IpPermission`

### ISSUE THREAD

**Issue by FalkWoldmann** [awslabs/aws-sdk-rust#1096]
### Describe the feature

We would like to use set operations on sets of `aws_sdk_ec2::types::IpPermission`, but without `Eq` and `Hash`, we cannot construct `HashSet`s containing them. 

### Use Case

Putting this data in a `HashSet`, or even a `HashMap`.

### Proposed Solution

Just add `Eq` and `Hash` to the `derive` call. I tried that out locally and it compiled.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
Yeah I understand the desire for this—unfortunately we can't for backwards compatibility reasons. Suppose, e.g. an f64 was added to the type in the future, then we wouldn't be able to implement Eq/Hash. I'll note that `PartialEq` is implemented, however.

I'd suggest making a struct that extracts a subset of the fields and deriving hash on that instead. Sorry we couldn't be more helpful.
