### ISSUE TITLE
BehaviorVersion's interface is not as future-proof as the doc says

### ISSUE THREAD

**Issue by Ten0** [awslabs/aws-sdk-rust#1111]
### Describe the bug

It is possible to construct a BehaviorVersion:

![image](https://github.com/awslabs/aws-sdk-rust/assets/9094255/9f802851-4ef3-46db-b9b8-a3400e95ef93)

Using the following syntax:
```rust
let behavior: BehaviorVersion = BehaviorVersion {};
```

While the documentation says that `latest` may change behavior but [`v2023_11_09`](https://docs.rs/aws-sdk-bedrock/1.18.0/aws_sdk_bedrock/config/struct.BehaviorVersion.html#method.v2023_11_09) would keep its behavior, that is impossible because one cannot add new fields to BehaviorVersion without that being a breaking change due to the currently allowed explicit construction.

### Expected Behavior

```rust
let behavior: BehaviorVersion = BehaviorVersion {};
```
should not compile, one should be forced to use either `latest` or `v2023_11_09` to instantiate a BehaviorVersion.

### Current Behavior

*compiles*

### Possible Solution

That should be achieved by defining the struct as so:
```rust
pub struct BehaviorVersion {
    _private: (),
}
```

### Additional Information/Context

This is technically a breaking change but since this was released recently and it's documented that this API shouldn't be used, better now than later.

### Version

```text
AWS SDK 1.1.8
```

**Comment by aajtodd** [comment]
This was [merged](https://github.com/smithy-lang/smithy-rs/pull/3513) and released. Closing.
