### ISSUE TITLE
The method `items()` is missing in SSM's paginators

### ISSUE THREAD

**Issue by Veetaha** [awslabs/aws-sdk-rust#1119]
### Describe the feature

As you can see there is no `items()` method on paginators in SSM crate. This method is supposed to return a stream of SSM parameters (flattened). This applies to all paginators in SSM, for example:

- [`aws_sdk_ssm::operation::get_parameters_by_path::paginator::GetParametersByPathPaginator`](https://docs.rs/aws-sdk-ssm/1.20.0/aws_sdk_ssm/operation/get_parameters_by_path/paginator/struct.GetParametersByPathPaginator.html)
- [`aws_sdk_ssm::operation::describe_parameters::paginator::DescribeParametersPaginator`](https://docs.rs/aws-sdk-ssm/1.20.0/aws_sdk_ssm/operation/describe_parameters/paginator/struct.DescribeParametersPaginator.html)

This looks like an oversight, because other AWS service SDK support the `items()` method on the paginatior. Examples:
- [`aws_sdk_scheduler::operation::list_schedules::paginator::ListSchedulesPaginator`](https://docs.rs/aws-sdk-scheduler/1.18.0/aws_sdk_scheduler/operation/list_schedules/paginator/struct.ListSchedulesPaginator.html#method.items)
- [`aws_sdk_backup::operation::list_backup_vaults::paginator::ListBackupVaultsPaginator`](https://docs.rs/aws-sdk-backup/1.20.0/aws_sdk_backup/operation/list_backup_vaults/paginator/struct.ListBackupVaultsPaginator.html#method.items)
- [`aws_sdk_ec2::operation::describe_tags::paginator::DescribeTagsPaginator`](https://docs.rs/aws-sdk-ec2/1.30.0/aws_sdk_ec2/operation/describe_tags/paginator/struct.DescribeTagsPaginator.html#method.items)

### Use Case

The method `items()` returns the flat stream of items which simplifies the development with the SDK. There are such methods in other AWS services, but for some reason there is no such method in SSM.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
This is an issue with the underlying models. We will work with the SSM service to get this rectified

@jmklix to forward to service team

**Comment by jmklix** [comment]
https://github.com/aws/aws-sdk/issues/742
