### ISSUE TITLE
New Service Support: Amazon Timestream

### ISSUE THREAD

**Issue by sethusrinivasan** [awslabs/aws-sdk-rust#114]

**Comment by rcoh** [comment]
Note: requires completion of #smithy-rs#109

**Comment by overheat** [comment]
Any workaround for now, since endpoint discovery not implemented.
We want to insert records to Timestream using rust SDK.

**Comment by Velfi** [comment]
There is no current workaround. We recognize that this is an important feature and will implement it as soon as our priorities allow.

**Comment by rafalwrzeszcz** [comment]
Seems like `smithy-rs` already supports it - is there any update on Timestream support in Rust SDK?

**Comment by jdisanti** [comment]
Support was added to `smithy-rs`, so the next full release (that is, not just a models update) of the SDK should include it. It may be a few weeks before that happens though.

**Comment by jdisanti** [comment]
As of the [August 3rd, 2023](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-08-03) release, the SDK now has experimental support for Timestream. In order to use it, you MUST call `.with_endpoint_discovery_enabled()` on the Client after construction.

**Comment by sethusrinivasan** [comment]
Thank you @jdisanti
