### ISSUE TITLE
SQS `ReceiveMessageFluentBuilder` `fn attribute_names` deprecation 

### ISSUE THREAD

**Issue by Smotrov** [awslabs/aws-sdk-rust#1145]
### Describe the issue

It is written now 
```
pub fn attribute_names(self, input: QueueAttributeName) -> Self
👎Deprecated: AttributeNames has been replaced by MessageSystemAttributeNames
```

But there is no `AttributeNames` in the function definition. Moreover the case is not _something_ is replaced by `MessageSystemAttributeNames` but `fn attribute_names` is replaced. 

So it looks a bit confusing. 

### Links

[Documentation link](https://docs.rs/aws-sdk-sqs/1.24.0/aws_sdk_sqs/operation/receive_message/builders/struct.ReceiveMessageFluentBuilder.html#method.attribute_names)

**Comment by aajtodd** [comment]
Thanks for the issue.

> But there is no AttributeNames in the function definition. 

This deprecation comes directly from the [model](https://github.com/awslabs/aws-sdk-rust/blob/2ce52f62947e00cff0b05bc8277124c8a78a69f3/aws-models/sqs.json#L3339-L3341) and is referring to the modeled shapes [AttributeNames](https://github.com/awslabs/aws-sdk-rust/blob/2ce52f62947e00cff0b05bc8277124c8a78a69f3/aws-models/sqs.json#L3336) and [MessageSystemAttributeNames](https://github.com/awslabs/aws-sdk-rust/blob/2ce52f62947e00cff0b05bc8277124c8a78a69f3/aws-models/sqs.json#L3347). 

> Moreover the case is not something is replaced by MessageSystemAttributeNames but fn attribute_names is replaced.

I'm not sure I follow your point here but the deprecation applies to the input member `AttributeNames` and so any fluent builder function generated to set or get that field is deprecated essentially (e.g. even [`get_attribute_names()`](https://docs.rs/aws-sdk-sqs/1.24.0/aws_sdk_sqs/operation/receive_message/builders/struct.ReceiveMessageFluentBuilder.html#method.get_attribute_names)).

Unfortunately there isn't much we can do here as deprecation text is open ended and so no way to easily link things if we wanted to. I'm going to go ahead and close this as there isn't anything actionable here.
