### ISSUE TITLE
New Service Support: Amazon IoT

### ISSUE THREAD

**Issue by MathiasKoch** [awslabs/aws-sdk-rust#115]

**Comment by gadams999** [comment]
Hi @MathiasKoch , is there a particular set of AWS IoT services you are interested in for support? My suggestion would be to support both control plane and RESTful data plane sets of APIs at minimum:

- [AWS IoT (Control Plane)](https://docs.aws.amazon.com/iot/latest/apireference/API_Operations_AWS_IoT.html)
- [AWS IoT Data Plane](https://docs.aws.amazon.com/iot/latest/apireference/API_Operations_AWS_IoT_Data_Plane.html)

Do you use of have the need for any of the other subset of [AWS IoT Actions](https://docs.aws.amazon.com/iot/latest/apireference/API_Operations.html)?

**Comment by MathiasKoch** [comment]
For me personally i would mostly be interested in the Control Plane, as well as the new Device Advisor API

**Comment by overheat** [comment]
Shadow is another awesome feature.
BTW, do you think IoT core is a little isolated from other aws services, as the iot policy is different from IAM policy?

**Comment by MathiasKoch** [comment]
I think the main thing to be aware of around IoT as a service, is that they require slight changes to the SigV4 signage.

I did the PR for rusoto here: https://github.com/rusoto/rusoto/pull/1940

**Comment by overheat** [comment]
> I think the main thing to be aware of around IoT as a service, is that they require slight changes to the SigV4 signage.
> 
> I did the PR for rusoto here: [rusoto/rusoto#1940](https://github.com/rusoto/rusoto/pull/1940)

Do you think X.509 auth is a better way?

**Comment by MathiasKoch** [comment]
I think X.509 auth is mostly relevant for data plane access, right?

I do think this SDK should support the IoT SigV4, but i was just raising the note that the IoT team at AWS seems to have implemented it slightly different than the rest.

**Comment by jdisanti** [comment]
All of the IoT services are now available as of [`v0.0.14-alpha`](https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.0.14-alpha).

@MathiasKoch - Thanks for the pointer on the signature difference. I tested the IoT Data Plane client manually to verify it's working, but I think the signature difference fixed in rusoto/rusoto#1940 affects pre-signed URLs, which we haven't implemented yet. These are being tracked in #139. Please up-vote that issue if you need them.
