### ISSUE TITLE
Link to amazon envvars configuration

### ISSUE THREAD

**Issue by Jasper-Bekkers** [awslabs/aws-sdk-rust#1162]
### Describe the issue

There are quite a few code samples out there, for example this one on the main page of the `aws_sdk_s3` crate, that just use `load_from_env()` without ever documenting which env vars (or maybe I missed it but at least it wasn't clear from the get-go). Please just link to the relevant documentation, or include the relevant documentation here somewhere.

```rust
use aws_sdk_s3 as s3;

#[::tokio::main]
async fn main() -> Result<(), s3::Error> {
    let config = aws_config::load_from_env().await;
    let client = aws_sdk_s3::Client::new(&config);

    // ... make some calls with the client

    Ok(())
}
```

https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html

### Links

https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html
https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/client/struct.Client.html

**Comment by ysaito1001** [comment]
Thank you for bringing this up to our attention. The name [load_from_env](https://docs.rs/aws-config/1.5.1/aws_config/fn.load_from_env.html) is historical, not necessarily referring to just environment variables; it is currently a convenience wrapper around [load_defaults](https://docs.rs/aws-config/1.5.1/aws_config/fn.load_defaults.html). That said, I agree that the rustdoc does not provide information as to what those defaults are.

We can probably link to [this page](https://docs.aws.amazon.com/sdkref/latest/guide/creds-config-files.html).

**Comment by Jasper-Bekkers** [comment]
Thanks yeah I had to spend quite some time figuring out what they were, even from code its not super clear. Probably this could be a good first issue for someone to pick up also.

**Comment by ysaito1001** [comment]
Will be addressed by https://github.com/smithy-lang/smithy-rs/pull/3694

**Comment by ysaito1001** [comment]
The suggested link has been added to docs as of [release-2024-06-18 ](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-06-18) ([example](https://docs.rs/aws-config/latest/aws_config/fn.load_defaults.html))
