### ISSUE TITLE
Allow AWS_ENDPOINT_URL_<SERVICE>

### ISSUE THREAD

**Issue by 1oglop1** [awslabs/aws-sdk-rust#1213]
### Describe the feature

Since there is already a support for AWS_ENDPOINT_URL  #1193, I think the sdk should support all  `AWS_ENDPOINT_URL_<SERVICE>` and other typical env vars.

https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html#envvars-list-AWS_ENDPOINT_URL_SERVICE

### Use Case

I run local dynamo DB from the amazon container but emulate other services with the localstack.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by aajtodd** [comment]
The SDK does support `AWS_ENDPOINT_URL_<service>`, can you provide an actual reproduction of something not working?

**Comment by 1oglop1** [comment]
@aajtodd could you point me to the code that's responsible for this, it may be entirely possible I am a few versions behind because it is really difficult to keep the multiple versions in sync. I wish the entire SDK could have a single version to follow similarly to JS or Python.

I am using
```
name = "aws-sdk-dynamodb"
version = "1.20.0"

name = "aws-config"
version = "1.1.9"
```

but here I found that it should indeed work https://github.com/awslabs/aws-sdk-rust/blob/68dbb5933ca5a2ec74aedecf6d2909cf3f475fe9/sdk/aws-config/test-data/profile-provider/assume_role_override_service_env_url/env.json#L3

In my case 
```
AWS_ENDPOINT_URL_DYNAMODB=http://localhost:5001 # does not work
AWS_ENDPOINT_URL=http://localhost:5001 # works
```

**Comment by 1oglop1** [comment]
Okay I can confirm that, supports definitely AWS_ENDPOINT_URL_DYNAMODB
```
name = "aws-config"
version = "1.5.10"
```

@aajtodd thanks for the help. a bit OT, would you be able to guess what is preventing `cargo update` from updating AWS packages to the latest version? can it be any of the aws packages listed?
