### ISSUE TITLE
[request]: New Service Support: Amazon Cognito

### ISSUE THREAD

**Issue by michaetto** [awslabs/aws-sdk-rust#124]
For us it would be great to have especially client for Cognito Identity Provider for user management in Cognito UserPool.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
note that this won't be directly usable as a credential provider yet, but you'll be able to use the API directly
