### ISSUE TITLE
rustc versioning for features and overall min req. Sample smithy-http.

### ISSUE THREAD

**Issue by johnsoncarlp** [awslabs/aws-sdk-rust#129]
## Bug Report

Rustc version required. Update README and if possible add to toml for packages.

### Version

all up to 0.0.9-alpha

### Platform

Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Description

https://github.com/rust-lang/rust/issues/63514

rustc min version for features used. For example, poll was an unstable feature until early 2021, so if features like poll are used we should put the min rustc version required in the Cargo.toml so the user compiling can quickly diagnose vs hunting for a supported version.

In this sample the version required is 1.51.0 and of course I was on 1.49.0 .. 

https://github.com/awslabs/aws-sdk-rust/blob/00c6d6f350cf45e2cdd8e3a9fdec6e24bbb63142/sdk/smithy-http/Cargo.toml

**Comment by jdisanti** [comment]
Thanks for reporting this!

It looks like support for specifying the minimum supported Rust version [isn't implemented in Cargo yet](https://github.com/rust-lang/rfcs/pull/2495), so we'll have to settle for a README update for now.

Related issue: #128
