### ISSUE TITLE
Creation of ResolveAwsEndpoint forces leaking of string

### ISSUE THREAD

**Issue by zekisherif** [awslabs/aws-sdk-rust#140]
### Version

aws-endpoint v0.1.

### Description

When creating something that implements [`ResolveAwsEndpoint`](https://awslabs.github.io/aws-sdk-rust/aws_endpoint/trait.ResolveAwsEndpoint.html) I am forced to leak `static` strings. 

e.g. Below is a snippet from my `MapRequest` impl in my endpoint stage.

```rust
fn string_to_static_str(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}

let provider: Arc<dyn ResolveAwsEndpoint> =
                Arc::new(aws_endpoint::partition::endpoint::Metadata {
                    uri_template: string_to_static_str(self.endpoint.clone()),
                    protocol: Protocol::Http,
                    credential_scope: self.credential_scope.clone(),
                    signature_versions: SignatureVersion::V4,
                });

let endpoint = provider
    .resolve_endpoint(&self.region)
    .map_err(AwsEndpointStageError::EndpointResolutionError)?;
```

[`AwsEndpoint`](https://awslabs.github.io/aws-sdk-rust/aws_endpoint/struct.AwsEndpoint.html) cannot be structured arbitrarily. Is there a way to not leak strings here?

**Comment by jdisanti** [comment]
I don't think we intended `AwsEndpoint`, `ResolveAwsEndpoint`, or `endpoint::Metadata` to be used outside of the AWS SDK's generated code. They are catered to the specific use-case of using [endpoints.json](https://github.com/awslabs/smithy-rs/blob/main/aws/sdk-codegen/src/main/resources/software/amazon/smithy/rustsdk/endpoints.json) for resolving endpoints for specific AWS SDKs.

Recommend using the [`Endpoint` struct](https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/smithy-http/src/endpoint.rs#L14) from `smithy-http` instead for your use-case. Something along the lines of:

```rust
let endpoint = Endpoint::immutable(Uri::from_str(my_uri).unwrap());
endpoint.set_endpoint(http_req.uri_mut(), None);
```

Thanks!
