### ISSUE TITLE
Use a basic config to create all types of clients

### ISSUE THREAD

**Issue by cemoktra** [awslabs/aws-sdk-rust#145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

I just played around with the Rust SDK to replace an mfa tool. And it seems a bit awkward to create the "same" (not same struct but containing same data) config twice to create `iam` and `sts` client. It would be nice to be able to reuse the same config

**Comment by rcoh** [comment]
We have an RFC out for this: https://github.com/awslabs/smithy-rs/pull/655, please feel free to leave a comment with your thoughts!

**Comment by rcoh** [comment]
this is done and shipped with v0.0.17-alpha. Thanks for the feedback!

**Comment by cemoktra** [comment]
@rcoh btw can the same applied to region? There is a Region for for each service
