### ISSUE TITLE
set_endpoint cannot set URI with custom endpoint

### ISSUE THREAD

**Issue by yzzhaa** [awslabs/aws-sdk-rust#155]
### Version

aws-auth = "0.1.0"
aws-hyper = "0.1.0"
aws-types = "0.1.0"
aws-endpoint = "0.1.0"
aws-sig-auth = "0.1.0"
smithy-client = "0.1.0"
smithy-http = "0.0.1"
smithy-http-tower = "0.1.0"

### Platform

Linux desktop x86_64 GNU/Linux

### Description

When using the `set_endpoint` with a custom endpoint, the URI isn't respected. 

e.x.

```
fn apply(
        &self,
        request: smithy_http::operation::Request,
    ) -> Result<smithy_http::operation::Request, Self::Error> {
        request.augment(|mut http_req, config| {

        let endpoint_str = String::from("https://service.region.amazonaws.com/uri/")
        let endpoint: Endpoint = Endpoint::mutable(Uri::from_str(&endpoint_str).unwrap());
        let uri = http_req.uri_mut();
        endpoint.set_endpoint(uri, None);
        ...

    })
}
```
After this, the endpoint would ignore `/uri/` and will still be `https://service.region.amazonaws.com`

**Comment by rcoh** [comment]
fixed in smithy-rs, this will land in the next release
