### ISSUE TITLE
S3: Pre-signed Download URLs

### ISSUE THREAD

**Issue by mbergkvist** [awslabs/aws-sdk-rust#157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Presigned urls for AWS S3 Upload

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Generate a pre-signed URL for an Amazon S3 objects to give users temporary access to objects.

**Additional context**
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/presign.html
https://github.com/awslabs/aws-sdk-rust/issues/139

**Comment by jdisanti** [comment]
Tracking this in #139 since the pre-sign functionality will be implemented generically across all services and operations.
