### ISSUE TITLE
New Service Support: S3

### ISSUE THREAD

**Issue by vishaalt** [awslabs/aws-sdk-rust#16]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Tell us about your request**
Add support for a basic S3 client

**Comment by chadbrewbaker** [comment]
Any interest a shell wrapper for the AWS CLI to get the crate on feature parity ASAP? I'm going to need it anyway as I have a lot of aws cli scripts lying around that make little sense re-coding.

**Comment by rcoh** [comment]
S3 has landed! Please keep an eye out for bugs an issue and let us know!
