### ISSUE TITLE
[request]: S3 DNS re-lookup on retry

### ISSUE THREAD

**Issue by keetonian** [awslabs/aws-sdk-rust#160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
I would like the ability to tell the S3 client to force a DNS lookup when retrying a request. This is a recommendation from S3 to improve latency.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This is one of the latency improvements suggested by S3:

> For latency-sensitive applications, Amazon S3 advises tracking and aggressively retrying slower operations. When you retry a request, we recommend using a new connection to Amazon S3 and performing a fresh DNS lookup.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance-design-patterns.html

**Are you currently working around this issue?**
We're not, but we looked into it. We're currently using Rusoto, which would require us to create a custom HttpConnector and create our own DNS retry logic inside of it. It's possible, but would be a pain and require several modifications.

**Comment by jdisanti** [comment]
That the SDK doesn't do DNS lookup on retry is actually a bug, so I'm correcting the label on this.

**Comment by jdisanti** [comment]
Issue in hyper that tracks making this possible: https://github.com/hyperium/hyper/issues/2605
