### ISSUE TITLE
Sign API GW requests

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#176]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/133
Self contained signing module with documentation in the guide
<div type='discussions-op-text'>

<sup>Originally posted by **mbergkvist** June 29, 2021</sup>
I have an API GW with IAM authorization on the endpoints. How can I use this SDK to sign the request?</div>

**Comment by jdisanti** [comment]
Tracking implementation of this in https://github.com/awslabs/smithy-rs/issues/1792

**Comment by phyber** [comment]
Previously (before 0.57.x) I was signing requests for API Gateway as follows:

```rust
// Sign a given HTTP request. Signs the request in place.
// Returning the Signature here is to enable testing, we don't actually need
// that in normal use of the program.
pub async fn v4(
    request: &mut Request<SdkBody>,
    timestamp: SystemTime,
    credentials_provider: &(impl ProvideCredentials + ?Sized),
    region: &Region,
    service_name: &SigningService,
) -> Result<Signature> {
    let request_config = RequestConfig {
        payload_override: None,
        region: &SigningRegion::from(region.clone()),
        request_ts: timestamp,
        service: service_name,
    };

    let signer = SigV4Signer::new();

    let signature = signer.sign(
        &OperationSigningConfig::default_config(),
        &request_config,
        &credentials_provider.provide_credentials().await?,
        request,
    )?;

    Ok(signature)
}
```

With 0.57.x lots of things have moved around, and the documentation is nharder to read in this area. Before, it was easy to figure out signing from the types, but less so now.

Could an example of signing a request be added?
Thanks.

**Comment by phyber** [comment]
I've actually figured this out now. I'm not sure which version I was looking at before, but when I returned a few days later, it was fairly obvious what I needed to do. I'll post some updated code later for others that come across this issue.

**Comment by jmklix** [comment]
Closing as duplicate: https://github.com/awslabs/aws-sdk-rust/issues/948
