### ISSUE TITLE
Add support for S3 Select

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#179]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/178

<div type='discussions-op-text'>

<sup>Originally posted by **cobbinma** August  3, 2021</sup>
Is S3 Select supported?</div>

**Comment by jdisanti** [comment]
S3 Select landed in [v0.0.17-alpha](https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.0.17-alpha).
