### ISSUE TITLE
[request]: Add guide section about using aws-sdk-rust on lambda

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Add a section to the usage guide about using the Rust SDK on AWS lambda. There are a number of sources, but there are some gotchas eg. #186 that would be good to proactively call out.

**Comment by Doug-AWS** [comment]
Work in progress.
