### ISSUE TITLE
DynamoDb localhost

### ISSUE THREAD

**Issue by nuvanti** [awslabs/aws-sdk-rust#188]
How do I access a local DynamoDB at http://localhost:8000 ? 

Can you please provide an example?

**Comment by rcoh** [comment]
You can access `dynamodb` local by overriding the endpoint resolver. In this case, you want to specify a static endpoint:
```rust
use http::Uri;
let endpoint = Endpoint::immutable(Uri::from_static("http://localhost:8000"));
let conf = aws_sdk_dynamodb::Config::builder().endpoint_resolver(endpoint).build();
let local_client = aws_sdk_dynamodb::from_conf(conf);
```

**Comment by nuvanti** [comment]
Thanks. This compiles but I get the following error:

Error: Unhandled(ConstructionFailure(NoRegion))

**Comment by rcoh** [comment]
yes, you need to set a region explicitly if there is no region specified in the environment variable:
Either:
- `export REGION=us-east-1` (or any region)
- ```rust
   use aws_sdk_dynamodb::Region;
   let conf = Config::builder().region(Region::new("us-east-1")).endpoint(...).build();
   ```
