### ISSUE TITLE
[request]: Add guide section about dynamodb local & endpoint overrides

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

See #188

**Comment by Doug-AWS** [comment]
https://docs.aws.amazon.com/sdk-for-rust/latest/dg/dynamodb-local.html
