### ISSUE TITLE
Invoke lambda with payload example

### ISSUE THREAD

**Issue by nuvanti** [awslabs/aws-sdk-rust#195]
Can you provide an example with invoking a lambda function with a payload/body?

**Comment by vladinator1000** [comment]
I was trying something like this. How do you get the lambda response from the [invoke struct](https://awslabs.github.io/aws-sdk-rust/aws_sdk_lambda/operation/struct.Invoke.html)? If we can figure this out it can be really useful for unit testing.
```rs
    let request_body = serde_json::to_vec(&request_body).unwrap();
    let blob = aws_lambda::Blob::new(request_body);

    let lambda_call = InvokeInput::builder()
        .set_function_name(Some("my-lambda".into()))
        .set_payload(Some(blob))
        .build()
        .unwrap();

    let lambda_config = aws_lambda::Config::builder()
        .endpoint_resolver(Endpoint::immutable(Uri::from_static(
            "http://localhost:4566",
        )))
        .build();

    let _invoke = lambda_call.make_operation(&lambda_config).unwrap();
```

**Comment by vladinator1000** [comment]
Thanks @rcoh! ([fixed link](https://github.com/awslabs/aws-sdk-rust/blob/main/examples/lambda/src/bin/invoke-function.rs))
