### ISSUE TITLE
New Service Support: Cloudwatch Metrics

### ISSUE THREAD

**Issue by vishaalt** [awslabs/aws-sdk-rust#20]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Tell us about your request**
Add support for Cloudwatch

**Comment by Oliboy50** [comment]
since there is already a "Cloudwatch Logs" feature request

I'd suggest to precise here that we're (probably) talking about being able to send metrics to Cloudwatch such as:

> New Service Support: Cloudwatch Metrics

?
