### ISSUE TITLE
[request]: Provide a mechanism to select a different profile

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Currently, it's possible to override the profile with the `AWS_PROFILE` environment variable. However, it would be great to override the profile directly during client construction.

**Comment by Sentinent** [comment]
Leaving some example code here since it wasn't immediately obvious to me how to do this:

```rust
use aws_config::default_provider::{
    credentials::DefaultCredentialsChain, region::DefaultRegionChain,
};

// ...

let credentials_provider = DefaultCredentialsChain::builder()
    .profile_name("profilename")
    .build()
    .await;
let region_provider = DefaultRegionChain::builder()
    .profile_name("profilename")
    .build();

let aws_config = aws_config::from_env()
    .credentials_provider(credentials_provider) /* of course you can omit these lines to use the default profiles */
    .region(region_provider) /* ^ ditto */
    .load()
    .await;
let client = aws_sdk_s3::Client::new(&aws_config);
```
