### ISSUE TITLE
EC2 describe_instance_types

### ISSUE THREAD

**Issue by tschuett** [awslabs/aws-sdk-rust#210]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution

**Platform/OS/Device**
OSX

**Describe the question**
```python
session = boto3.Session(region_name="us-east-2")
    ec2_client = session.client('ec2')

    result = ec2_client.describe_instance_types(
        Filters=[
            {
                'Name': 'network-info.efa-supported',
                'Values': [
                    'true'
                ]
            },
        ],
    )
    for instance in result['InstanceTypes']:
        print(instance['InstanceType'])
```

```rust
let ec2_conf = aws_sdk_ec2::config::Config::builder()
            .credentials_provider(aws_auth_providers::default_provider())
            .region(Some(Region::new("us-east-2")))
            .build();

        let ec2_client = aws_sdk_ec2::Client::from_conf(ec2_conf);

        let filters = vec![Filter::builder()
            .set_name(Some("network-info.efa-supported".to_string()))
            .set_values(Some(vec!["true".to_string()]))
            .build()];

        let result = ec2_client
            .describe_instance_types()
            .set_filters(Some(filters))
            .send()
            .await?;

        Ok(result
            .instance_types
            .unwrap_or_default()
            .into_iter()
            .filter_map(|instance| instance.instance_type)
            .collect::<Vec<_>>())
```

In both cases I get: ```[I3en24xlarge, C6gn16xlarge, G4dnMetal]```

For 
```bash
 aws ec2 describe-instance-types \
--region us-east-2 \
--filters Name=network-info.efa-supported,Values=true \
--query "InstanceTypes[*].[InstanceType]" \
--output text
```

I get 20 instances?!? What am I doing wrong?

**Comment by rcoh** [comment]
interesting! Can you use `--debug` with the CLI and `RUST_LOG='smithy_http=trace'` (you'll need add `tracing_subscriber::fmt::init()`) on the SDK to compare what request is going across the wire in both cases? That should hopefully narrow it down.

**Comment by tschuett** [comment]
[cli.txt](https://github.com/awslabs/aws-sdk-rust/files/7071581/cli.txt)
[rust.txt](https://github.com/awslabs/aws-sdk-rust/files/7071582/rust.txt)

Thank you for the timely reply!!!

**Comment by tschuett** [comment]
Note that neither ```MaxResults``` nor ```set_max_results``` gave any changes. I didn't bother with pagination.

**Comment by rcoh** [comment]
looks the CLI is implicitly paginating for you behind the scenes. Pagination is on our roadmap (#47) but isn't implemented yet. Until then, you'll need to manually construct a new request from the pagination token of the previous request.
