### ISSUE TITLE
[request]: SIGv4A signing

### ISSUE THREAD

**Issue by jdisanti** [awslabs/aws-sdk-rust#232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
SIGv4A is needed to use S3 Multi-region Access Points.

**Comment by jdisanti** [comment]
Tracking implementation in https://github.com/awslabs/smithy-rs/issues/1797

**Comment by ymwjbxxq** [comment]
Do we have an ETA, more or less? 
Today I stumble upon this problem and would be great to know a date more or less
```
Signature Version 4 is the AWS signing protocol. AWS also supports an extension, Signature Version 4A, which supports signatures for multi-Region API requests. For more information, see the [sigv4a-signing-examples](https://github.com/aws-samples/sigv4a-signing-examples) project on GitHub.

 https://docs.aws.amazon.com/general/latest/gr/signing-aws-api-requests.html
```

**Comment by jdisanti** [comment]
SigV4a was shipped in the [November 2nd release](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-11-02).
