### ISSUE TITLE
[request]: Support Adaptive Retry Mode

### ISSUE THREAD

**Issue by Velfi** [awslabs/aws-sdk-rust#247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Please add support to the SDK for the [Adaptive retry mode](https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html).

**Comment by graelo** [comment]
I'd like to upvote, but I find the description of Adaptive mode to be not quite precise. Could you improve it a bit?

Thanks!

**Comment by jdisanti** [comment]
This was implemented a while ago (before GA), and can be configured on the retry config.
