### ISSUE TITLE
[request]: Add support for the external-process credential provider

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Add support for the external process credential provider: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
- [ ] usable directly
- [ ] loaded from `~/.aws/config` via `credential_process = ...`

**Are you currently working around this issue?**
How are you currently solving this problem?

- Registering a custom named provider
- implementing my own credentials file provider

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jszwedko** [comment]
Hi all! Just wondering if there is an external roadmap that I could check to see if this feature is on. We (https://github.com/vectordotdev/vector) have some users that we're relying on `rusoto`'s `credential_process` support to have Hashicorp's Vault provide credentials.

**Comment by jszwedko** [comment]
Started a PR for this here: https://github.com/awslabs/smithy-rs/pull/1356
