### ISSUE TITLE
[request]: sdk model structs should not have `Optional` type if the field is marked as `required` in smithy. 

### ISSUE THREAD

**Issue by asanthan-amazon** [awslabs/aws-sdk-rust#267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Currently, all the fields in generated types are marked as Optional. But, the sdk should generate types where fields should not be marked as Optional if it is marked as @required in Smithy.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The generated sdk model types should not have `Optional` type if the field is marked as `required` in smithy. 

**Are you currently working around this issue?**
Because, it is marked as Optional,  there is no compile-time validation to say if the entire type is fully constructed or not. 
As a work around, we create another wrapper type which does not use Optional for required fields. 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rcoh** [comment]
see also #163

**Comment by asanthan-amazon** [comment]
I think if the service team removes `required` trait, that is backward incompatible change from my perspective. In which case, a new version of SDK needs to be generated that customer can use. 

In that way, customer will come to know explicitly that an optional field now becomes mandatory or vice-versa.

**Comment by jdisanti** [comment]
Tracking this in #536.
