### ISSUE TITLE
New Service Support: SES

### ISSUE THREAD

**Issue by vishaalt** [awslabs/aws-sdk-rust#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Tell us about your request**
Add support for SES

**Comment by uwatr** [comment]
This SDK missing SES is what is preventing us from using it in our project...This is a pretty basic and critical function for any web app...

**Comment by Velocity-** [comment]
I know a "me too" is unwelcome, but I just want to back up @uwatr here - we, too, are blocked by SES. We'd love to adopt it (early as it is) but SES is the only component that we rely on and stubbing it with Rusoto makes so little sense.

I think the majority of projects contain some form of email logic, and while I understand things like EC2 are much more relevant to the general public, SES is an incredibly common component that I feel would be relatively lightweight, but make a lot of adopters leap.

Once again, I know it's a "me too" type of comment, but we're excited to use Rust with our AWS chain and I can imagine there's a bunch more who ran into the absense of SES that would hold them back.

Keep up the good work, this is absolutely going in the right direction!

**Comment by rcoh** [comment]
thanks for the feedback! This will go out in tomorrow's release: https://github.com/awslabs/smithy-rs/pull/499
