### ISSUE TITLE
Profile name validation does not allow `@` character

### ISSUE THREAD

**Issue by dennis-kuypers** [awslabs/aws-sdk-rust#270]
### Version

`v0.0.22-alpha`

### Description

Profile names are validated using [validate_identifier](https://github.com/awslabs/aws-sdk-rust/blob/6c874ba3c63387254ecd00d651fe04c367070132/sdk/aws-config/src/profile/parser/normalize.rs#L131-L137).

I am using profile names of the pattern `<role>@<account>`, e.g.: `admin@prod`. Those profile names are not an issue in other places, such as the aws cli. This is an established pattern that is not easy to change for me. 

Due to this validation I can not use such profiles.  Is this something that can be fixed by adding `@` to the list of acceptable characters or are there other limitations that prevent this?

**Comment by rcoh** [comment]
thanks for the report! We'll work on a fix for this. We're planning on expanding the scope of allowed characters to be a bit more lenient. It won't behave _exactly_ like the CLI (which actually uses `shlex.split(..)`), but it behave identically for most use cases.

**Comment by aripalo** [comment]
Yeah, shout-out for this feature as well 👍 `role@account` is quite common pattern for naming profiles when you're working in the enterprise with multitudes of AWS accounts.

**Comment by rcoh** [comment]
fixed in 0.0.26-alpha
