### ISSUE TITLE
[request]: Rust API Reference Guide

### ISSUE THREAD

**Issue by allan2** [awslabs/aws-sdk-rust#280]
![rust_api_reference](https://user-images.githubusercontent.com/6740989/140551096-09a35e80-e87f-4a3e-80ca-15fa1338fd66.jpg)

This request is for a Rust-specific API reference guide. All the cool languages have one.

Could it be added to the roadmap?

**Comment by rcoh** [comment]
we're working on it! You can follow along with the progress here: https://github.com/awsdocs/aws-rust-developer-guide-v1

It will eventually be hosted exactly where you've linked above.
