### ISSUE TITLE
aws_sdk_apigatewaymanagement post_to_connection seems to double url encode connectionId

### ISSUE THREAD

**Issue by surt666** [awslabs/aws-sdk-rust#300]
### Version

0.0.25-alpha

### Platform
Lambda aarch64

### AWS Services
apigatewaymanagementapi

### Description
When doing post_to_connection i get an InvalidSignatureException, which makes no sense to me as the api should be doing the signing to my knowledge. I think it's related to a double url encoding of the connectionId, so that a path like /prod/%40connections/I9M02cP4DoECIJA%3D becomes /prod/%40connections/I9M02cP4DoECIJA%253D. Using awscurl with the modified path seems to work, at least it doesn't complain about anything.

I tried to enable the tracing, but only seems to get 

```
[2m2021-11-17T16:04:50.063032Z[0m [32m INFO[0m [1msend_operation[0m[1m{[0moperation="PostToConnection" service="apigatewaymanagementapi"[1m}[0m: aws_config::meta::credentials::chain: loaded credentials provider=Environment |
```

Not sure why it truncates the output

**Comment by Velfi** [comment]
Thanks for reporting this, we'll look into it. It's super strange that it's truncating the logs like that.

**Comment by surt666** [comment]
The truncating might be due to the function being async, as I can see the tracing docs mentioning this, but not sure how to set it up correctly in that case. Further just to explain how the client is set up, this is the code
```
async fn get_apig_client() -> APIGClient {
    let shared_config = aws_config::load_from_env().await;
    let creds = shared_config.credentials_provider().unwrap().clone();
    let config = aws_sdk_apigatewaymanagement::Config::builder().credentials_provider(creds).region(Region::from(shared_config.region().unwrap().clone())).endpoint_resolver(Endpoint::immutable(Uri::from_static(CONNECT_URL))).build();
    APIGClient::from_conf(config)
}
```
Is there anything obvioulsly wrong with this. It seems too convoluted, but was the only way I could see to specify the CONNECT_URL endpoint for a websocket

**Comment by rcoh** [comment]
I've reproduced this issue and I'm working on a fix. Thanks for reporting!
