### ISSUE TITLE
Extra `xmlns` attributes break object notifications in localstack

### ISSUE THREAD

**Issue by benesch** [awslabs/aws-sdk-rust#301]
### Version

v0.25.0-alpha

### AWS Services

S3, at least, but likely any API that uses XML as the encoding format.

### Description

This is arguably a bug in localstack, but it is a deviation from how other SDKs encode XML, so I figure I'd raise it here first. The generated XML encoding code adds an `xmlns` attribute to every element, rather than just the root element, even when the namespace of the child element matches the namespace of the parent. Here's an example of what I mean:

https://github.com/awslabs/aws-sdk-rust/blob/d029624f25715f2083b504eeba04fb83caa3962b/sdk/s3/src/xml_ser.rs#L839-L881

Notice how `TopicConfiguration`, `QueueConfiguration`, and `CloudFunctionConfiguration` all get serialized with an explicit `xmlns` attribute. Normally just the root [`NotificationConfiguration`](https://github.com/awslabs/aws-sdk-rust/blob/d029624f25715f2083b504eeba04fb83caa3962b/sdk/s3/src/xml_ser.rs#L210-L212) would get the namespace.

This causes localstack's handling of the PutBucketNotificationConfiguration API to get confused: https://github.com/localstack/localstack/blob/5d11af78ae1d19560f696a9e1abb707bd115c390/localstack/services/s3/s3_listener.py#L1052. Normally that unparses to a dict like `{'QueueConfiguration': {'Events': ['s3::ObjectCreated']}}`, but with the AWS Rust SDK, that unparses instead to a dict like `{'QueueConfiguration': {'Events': [{'@xmlns': 'http://s3.amazonaws.com/doc/2006-03-01/', '#text':'s3::ObjectCreated'}]}`. And so localstack gets confused and doesn't properly understand the event you're attempting to subscribe to.

Now, arguably this is a localstack bug because I think the XML that the AWS Rust SDK generates is perfectly valid. But I figured I'd raise here first, because it is at variance with what all the other AWS SDKs generate.

**Comment by benesch** [comment]
I opened a PR to fix this in localstack: https://github.com/localstack/localstack/pull/4979. I'm not sure that PR should actually be merged, but it does help demonstrate the issue.

**Comment by rcoh** [comment]
thanks for reporting this! This has been on my list for a while although the lack of impact didn't make it a high priority. A fix will go out in the next release that is more precise about where `xmlns` is applied.
