### ISSUE TITLE
Make it possible to remove rustls from the crate graph?

### ISSUE THREAD

**Issue by benesch** [awslabs/aws-sdk-rust#304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**

Thanks very much for fixing #265. However, even after enabling the `native-tls` feature and disabling the `rustls` feature, e.g. via

```toml
[dependencies]
aws-sdk-s3 = { version = "0.0.25-alpha", default-features = false, features = ["client", "native-tls"] }
```

the `rustls` crate (and friends) still appear in the crate graph (i.e., in Cargo.lock). This makes it hard to verify that the correct TLS implementation is in use. At @MaterializeInc we statically analyze Cargo.lock and would like to restore our ban of `rusttls` in our tree, so we can be sure that the native TLS stack is in use instead.

The issue, as best as I can ascertain, is that the `aws-hyper` crate declares a default feature of `rustls`:

https://github.com/awslabs/aws-sdk-rust/blob/501f03d0dd03310435b05aac426400eb0ef6f9f8/sdk/aws-smithy-client/Cargo.toml#L14

That means that when a crate like aws-sdk-s3 depends upon it

https://github.com/awslabs/aws-sdk-rust/blob/501f03d0dd03310435b05aac426400eb0ef6f9f8/sdk/s3/Cargo.toml#L21-L24

the rustls feature is enabled by default. I _think_ it would be sufficient just to drop that feature from the default set of features in `aws-hyper`. The downstream crates already seem to do the correct thing of enabling their own `rustls` feature by default, and using that to control the `aws-hyper/rustls` feature:

https://github.com/awslabs/aws-sdk-rust/blob/501f03d0dd03310435b05aac426400eb0ef6f9f8/sdk/s3/Cargo.toml#L94-L96

**Comment by rcoh** [comment]
thanks for the detailed bug report and diagnosis! We'll see if we can get this fix in the next release.

**Comment by Velfi** [comment]
We have a fix for this but it requires we make some changes to how we handle default features. I'm working on those changes this week.

**Comment by benesch** [comment]
Awesome, thanks very much for the update!

**Comment by Velfi** [comment]
This change will be included in the upcoming release

**Comment by benesch** [comment]
v0.3.0 works perfectly! Thank you very much!
