### ISSUE TITLE
Timout warnings

### ISSUE THREAD

**Issue by fredrik-jansson-se** [awslabs/aws-sdk-rust#317]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution

**Platform/OS/Device**
Ubuntu Linux 20.04.3
SDK version: 0.0.26-alpha

**Describe the question**

```
    let cw_cfg = aws_sdk_cloudwatch::Config::builder() 
        .region(aws_sdk_sts::Region::new(
            aws_credentials.get("AWS_DEFAULT_REGION").unwrap().clone(),
        ))
        .credentials_provider(credentials_provider)
        .timeout_config(Default::default())
        .build();
```

When I post metrics I keep getting these warnings, I added the `timeout_config(Default::default())`, but doesn't seem to make any difference.
```
2021-11-30T19:22:55.184303Z  WARN aws_smithy_client::timeout: One or more timeouts were set but no async_sleep fn was passed. No timeouts will occur.
Timeouts:
Connect (time to first byte):(unset)
TLS negotiation:(unset)
HTTP read:(unset)
API requests:(unset)
HTTP requests:(unset)
```

What do I need to configure to get rid of these warnings?

**Comment by jdisanti** [comment]
Can you post the dependency line for the `aws-config` package from your Cargo.toml?

The async_sleep should have a default implementation depending on which features are enabled, and the default feature set should include it (it's the `rt-tokio` feature).

**Comment by fredrik-jansson-se** [comment]
Hey, thanks for getting back so quick!

Just upgraded from 0.0.22 to 0.0.26, made no changes but adding aws-smithy-types-convert.

```
aws-config = { version = "0.0.26-alpha"}
aws-sdk-cloudwatch = { version="0.0.26-alpha"}
aws-sdk-cloudwatchlogs = { version="0.0.26-alpha"}
aws-sdk-sts = { version ="0.0.26-alpha"}
aws-smithy-types-convert = { version ="0.30.0-alpha", features=["convert-chrono"]}
```

**Comment by jdisanti** [comment]
I was able to reproduce the issue locally. This definitely seems like a bug to me. Will fix. Thanks!

**Comment by jdisanti** [comment]
Also, if you need a workaround for this while we get a fix out, you can manually set a sleep implementation by doing the following:

1. Depend on `aws-smithy-client`:
```toml
aws-smithy-async = "0.30.0-alpha"
```
2. Modify the client creation code to set the sleep impl:
```rust
    let cw_cfg = {
        let mut builder = aws_sdk_cloudwatch::Config::builder()
            .region(aws_sdk_cloudwatch::Region::new(
                aws_credentials.get("AWS_DEFAULT_REGION").unwrap().clone(),
            ))
            .credentials_provider(credentials_provider);
        // This sets the sleep impl to the default Tokio implementation:
        builder.set_sleep_impl(aws_smithy_async::rt::sleep::default_async_sleep());
        builder.build()
    };
```

**Comment by fredrik-jansson-se** [comment]
Fantastic, many thanks for the help!!

**Comment by rcoh** [comment]
@fredrik-jansson-se I just wanted to follow up to learn more about your use case for not using `aws-config` to construct the client: https://crates.io/crates/aws-config

**Comment by fredrik-jansson-se** [comment]
Hey,

so first, I actually converted the code from Rusoto to this SDK, and I'm totally open to having taken the "shortest path" when creating my clients (cloudwatch metrics and logs).

The reason for my code being a bit involved is that I get access-key, region, roles etc from another source (vs reading from env or ~/.aws).

If I could simplify the code below, no one would be happier than me :)

That said, I'm not sure I understand your question: "not using aws-config to construct the client", I assumed I needed an aws_sdk_cloudwatch::Client and an aws_sdk_cloudwatchlogs::Client. 

Can/should those clients be created from something in the aws-config crate? If I totally misunderstand your question, let me know :)

```
 let sts_credentials = aws_sdk_sts::Credentials::new(
        aws_credentials
            .get("AWS_ACCESS_KEY_ID")
            .ok_or(anyhow::Error::msg("Failed to read AWS_ACCESS_KEY_ID"))?
            .to_string(),
        aws_credentials
            .get("AWS_SECRET_ACCESS_KEY")
            .ok_or(anyhow::Error::msg("Failed to read AWS_SECRET_ACCESS_KEY"))?
            .to_string(),
        None,
        None,
        "fredrik",
    );

    let sts_config = aws_sdk_sts::Config::builder()
        .credentials_provider(sts_credentials.clone())
        .region(aws_sdk_sts::Region::new(
            aws_credentials.get("AWS_DEFAULT_REGION").unwrap().clone(),
        ))
        .build();

    let sts_client = aws_sdk_sts::Client::from_conf(sts_config);

    let credentials_provider = match aws_credentials.get("AWS_ROLE_ARN") {
        Some(role_arn) => {
            let mut assume_role = sts_client
                .assume_role()
                .role_arn(role_arn)
                .role_session_name("fredrik")
                .send()
                .await?;
            let mut credentials = assume_role.credentials.take().unwrap();

            aws_sdk_cloudwatch::Credentials::new(
                credentials.access_key_id.take().unwrap(),
                credentials.secret_access_key.take().unwrap(),
                credentials.session_token,
                None,
                "fredrik",
            )
        }
        None => sts_credentials,
    };

    let cw_cfg = {
        let mut builder = aws_sdk_cloudwatch::Config::builder()
            .region(aws_sdk_sts::Region::new(
                aws_credentials.get("AWS_DEFAULT_REGION").unwrap().clone(),
            ))
            .credentials_provider(credentials_provider);

        // This can be removed in a later release than 0.0.26
        builder.set_sleep_impl(aws_smithy_async::rt::sleep::default_async_sleep());
        builder.build()
    };

    let cw = aws_sdk_cloudwatch::Client::from_conf(cw_cfg);
```

**Comment by rcoh** [comment]
A few things:
- all of the credential logic lives in `aws-config`. `aws-config` can create a cross service configuration object you can use to construct a service. This includes support for automatically loading the region from `AWS_DEFAULT_REGION`
- It looks like you are creating STS credentials from environment variables. We actually provide an assume role provider for that exact use case: https://docs.rs/aws-config/0.0.26-alpha/aws_config/sts/struct.AssumeRoleProvider.html

The most direct path would then be something like this:

```rust
use aws_config::sts::AssumeRoleProvider;
use aws_config::meta::credentials::LazyCachingCredentialsProvider;

 let base_credentials = aws_sdk_sts::Credentials::new(
        aws_credentials
            .get("AWS_ACCESS_KEY_ID")
            .ok_or(anyhow::Error::msg("Failed to read AWS_ACCESS_KEY_ID"))?
            .to_string(),
        aws_credentials
            .get("AWS_SECRET_ACCESS_KEY")
            .ok_or(anyhow::Error::msg("Failed to read AWS_SECRET_ACCESS_KEY"))?
            .to_string(),
        None,
        None,
        "fredrik",
    );
let region = aws_config::default_provider::region::default_provider().region().await;
let credentials = aws_config::AssumeRoleProvider::builder("arn:aws:iam::123456789012:role/demo")
  .region(region)
  .session_name("<todo>")
  .build(base_credentials);
let cached_credentials = LazyCachingCredentialsProvider::builder().load(credentials);
let shared_config = aws_config::env_loader().credentials(credentials).load().await;
let cloudwatch_client = aws_sdk_cloudwatch::Client::new(&shared_config);
```

That said, I'd be interested in knowing more about where your credentials actually come from to see if there's a built-in provider that might work with less friction

**Comment by fredrik-jansson-se** [comment]
That said, I'd be interested in knowing more about where your credentials actually come from to see if there's a built-in provider that might work with less friction. 

> aws_credentials is a wrapper around a secure store we use for credentials, I choose to keep the same key names as the standard AWS environment variables. So from the clients pov, it looks like a Map, hence the `.get(xx).ok_or(yy)`.

I'm not sure what aws_credentials is exactly in your example, but you could also impl ProvideCredentials for YourType to remove another level of boilerplate.

> I really like that idea and I'll definitely do that, thank you for that idea!
