### ISSUE TITLE
Invalid URL character cause panic

### ISSUE THREAD

**Issue by DCjanus** [awslabs/aws-sdk-rust#331]
### Version
aws_sdk_s3 0.2.0 and main branch on github which commit hash is 6feb50dd219ec5bf8cb7527d6142e46ec5311b9e

### Platform

Linux DCjanusArchLinuxNUC10 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000 x86_64 GNU/Linux

### AWS Services
S3

### Description

This code cause panic 

```Rust
#[tokio::test]
async fn test_invalid_key() {
    let config = aws_sdk_s3::Config::builder().build();

    aws_sdk_s3::input::HeadObjectInput::builder()
        .bucket("test")
        .key("<")
        .build()
        .unwrap()
        .make_operation(&config)
        .await;
}
```
Panic message: 

```
thread 'test_invalid_key' panicked at 'should be valid request: http::Error(InvalidUri(InvalidUriChar))', sdk\s3\src\input.rs:14854:28
```

**Comment by rcoh** [comment]
thanks for the report! we'll investigate and get a fix out ASAP

**Comment by DCjanus** [comment]
Code from here: https://github.com/awslabs/aws-sdk-rust/blob/6feb50dd219ec5bf8cb7527d6142e46ec5311b9e/sdk/aws-smithy-http/src/label.rs#L18

Looks like we percent encode when character hit the blacklist, but in the real world, input could be really unexpected, and we should encode characters that not on the whitelist

**Comment by DCjanus** [comment]
BTW, maybe we should avoid `unwrap` or `expect` as much as we can, since most AWS SDK type is not [UnwindSafe](https://doc.rust-lang.org/std/panic/trait.UnwindSafe.html).

Which means, I can't use [futures::future::FutureExt::catch_unwind](https://docs.rs/futures/latest/futures/future/trait.FutureExt.html#method.catch_unwind) to recover my server from panic, which is really horrible.

I don't think `expect` like this is a good idea:

```Rust
    fn assemble(
        builder: http::request::Builder,
        body: aws_smithy_http::body::SdkBody,
    ) -> http::request::Request<aws_smithy_http::body::SdkBody> {
        builder.body(body).expect("should be valid request")
    }
```

**Comment by rcoh** [comment]
yeah we will add more exhaustive testing—generally the SDK should never panic when dispatching requests, so this is a bug (and the `expect` here quickly alerted you to the issue)

**Comment by DCjanus** [comment]
Sounds good to me, thanks for your help.

**Comment by rcoh** [comment]
Thanks for reporting & debugging! the fix for this has landed upstream and will go out in the next release!
