### ISSUE TITLE
aws_sdk_s3::Client with custom ca_cert example

### ISSUE THREAD

**Issue by oxlade39** [awslabs/aws-sdk-rust#334]
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

I'm trying to find an example of creating an `aws_sdk_s3::Client` with a custom cert.
I seem to be going around in circles trying the various TLS options with the various client/connector options.

with the following code:

```rust
extern crate dotenv;

use aws_sdk_s3::{Client, Error};
use aws_config::meta::region::RegionProviderChain;

use dotenv::dotenv;

#[tokio::main]
async fn main() -> Result<(), Error> {
    dotenv().ok();
    env_logger::init();
    let region_provider = RegionProviderChain::default_provider().or_else("us-east-1");
    let config = aws_config::from_env().region(region_provider).load().await;
    let client = Client::new(&config);

    let b = client.list_buckets().send().await?;

    println!("b: {:?}", b);

    Ok(())
}
```

I'm currently getting a `Connection reset by peer` error. I'm fairly certain this is because of my corporate network setup and the need to a custom cert chain. I've explored various option in order to use a custom `crt` file. 
I've tried various combinations of `rusttls` and `native-tls` and composing `hyper` and `hyper-tls` as well as `smithy` but I can't work out the correct combination, let alone when or why I would choose one combination over another.

Any help appreciated.

### Platform/OS/Device

Linux vdiopcuk00065 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Language Version

rustc 1.57.0

**Comment by rcoh** [comment]
The next release will include a way to (relatively) easily provide your own connector for AWS config and generated clients. This isn't super ergonomic at the moment and we'll keep iterating on it

**Comment by Velfi** [comment]
We now have a ca-cert example
