### ISSUE TITLE
Special characters in AWS_SECRET_ACCESS_KEY lead to "request signature does not match"  error

### ISSUE THREAD

**Issue by kingpalethe** [awslabs/aws-sdk-rust#343]
### What is the problem?

I was using this as an environment variable:

`AWS_SECRET_ACCESS_KEY=...9ZpA0...p...Oagz/gCn/5DM+IqB+XOoI6p....`

(This is obfuscated by replacing some characters with ...)

Do you see the `+` and `/` in that?

It let to this error:

`request signature we calculated does not match the signature you provided`

EASY FIX:
---
When I generated a new secret key with just letters and numbers, it worked fine.
---

so -- 

Clearly there is some encoding issue.

Note -- this secret key with `+` and `/` symbols worked without issue in Python, JS, Ruby .....

### Version

aws-config v0.2.0, aws-sdk-sqs v0.2.0

### Platform

ubuntu 18

### Logs

`Error { code: "SignatureDoesNotMatch", message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

**Comment by rcoh** [comment]
we've definitely tested keys with special characters. Is it possible that you're accidentally omitting the session token?

**Comment by rcoh** [comment]
it would also be helpful if you could share the source of the secret key to aid in reproducing the issue

**Comment by kingpalethe** [comment]
I don't want to share the secret key because it is, uh, "secret". 

Actually we don't use `session token` and never have in other languages.

I am going to close this issue now, if someone else comes here, and finds the same thing, they can reopen, but if not, and nobody else reports this issue, let's assume I did something else wrong on my end. Thanks.

**Comment by rcoh** [comment]
Apologies, I wasn't asking for your secret key but rather source (eg. STS, downloaded via the console, IMDS, etc.)

**Comment by kingpalethe** [comment]
Oh, it's from an environment variable. I can print it out like this and it looks fine.

```
let aws_secret_key = env::var("AWS_SECRET_ACCESS_KEY").expect("AWS_SECRET_ACCESS_KEY not found in env");
println!("aws_secret_key: {:#?}", aws_secret_key);
```
