### ISSUE TITLE
Make ec2 `DescribeInstances` builder `Clone`

### ISSUE THREAD

**Issue by ojacobson** [awslabs/aws-sdk-rust#345]
### Tell us about your request

Many of the request builders in this library implement `Clone`, but not all of them. The EC2 DescribeInstances request builder appears to only capture `Clone` values, but is not itself `Clone`.

### Tell us about the problem you're trying to solve.

My underlying goal is to write a generic request paginator trait, so that I can be sure that (up to bugs in request-specific code) pagination is handled consistently and correctly across my codebase. To do so, I use the `Clone` trait to make copies of the caller's initial request builder, per page, to attach page-specific properties to.

### Are you currently working around this issue?

This can somewhat be worked around with a fn that returns a configured builder, rather than cloning an existing builder, but it complicates the definition of my paginator trait to support that.

### Additional context

There are probably other builders that should implement `Clone` but don't. I only know about this one because it affected me.

**Comment by Jacco** [comment]
Think this might be solved by 

https://github.com/awslabs/smithy-rs/pull/985

**Comment by rcoh** [comment]
> Think this might be solved by
> 
> [awslabs/smithy-rs#985](https://github.com/awslabs/smithy-rs/pull/985)

I think that's correct, you could include an integration test in smithy-rs#985 for this specific operation to be sure

**Comment by ojacobson** [comment]
This has been obviated by the built-in paginator (which is great!), so I no longer wish for `DescribeInstances` to be `Clone`. I wouldn't object, but I also won't need it.

**Comment by jdisanti** [comment]
It looks like `DescribeInstances` implements `Clone` now.
