### ISSUE TITLE
aws_sdk_dynamodb::[...]::ScalarAttributeType is missing variant API documentation

### ISSUE THREAD

**Issue by carllerche** [awslabs/aws-sdk-rust#349]
### What is the problem?

The [`aws_sdk_dynamodb::model::ScalarAttributeType`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/model/enum.ScalarAttributeType.html) enum is missing variant API documentation

### Version

0.3.0

### Platform

Linux

### AWS Services

dynamodb

**Comment by jdisanti** [comment]
Thanks for reporting this! I've contacted the AWS service team responsible for the DynamoDB service model and asked them to update the documentation.
