### ISSUE TITLE
[request]: Could aws_config::Config implement Clone?

### ISSUE THREAD

**Issue by benesch** [awslabs/aws-sdk-rust#352]
### Tell us about your request

Could `aws_config::Config` implement `Clone`? 

### Tell us about the problem you're trying to solve.

I'd like to await the call to `load` in one place and then pass the resulting object around in places where managing the lifetime would be annoying.

### Are you currently working around this issue?

We currently have our own version of `aws_config::Config` in MaterializeInc/materialize that does support `Clone`: https://github.com/MaterializeInc/materialize/blob/8ea7ff3af8c842e3e54105d585fdf8b4b1f8b4ab/src/aws-util/src/config.rs#L18-L24. This opens us up to issues like https://github.com/awslabs/aws-sdk-rust/issues/317.

### Additional context

https://github.com/awslabs/smithy-rs/issues/364 seems related?

**Comment by rcoh** [comment]
I think making it clone should work. However since services are created
with a reference to aws config you should be able to arc it on your side as
a stopgap

**Comment by benesch** [comment]
> you should be able to arc it on your side as a stopgap

Oh great point, thanks. Works great: https://github.com/MaterializeInc/materialize/pull/9651

**Comment by benesch** [comment]
> but your callout in the PR about endpoints is a good one. Do you mind sharing your usecase for setting the same endpoint across multiple services?

Ah, yeah, that's how we just blindly point all of our AWS clients at [LocalStack](https://localstack.cloud) in our tests. I'm not sure it's particularly useful outside the case of LocalStack. It's definitely weird that LocalStack manages to expose every AWS API on the same endpoint. Come to think of it I'm really not sure how they make that work.

Using one endpoint for all services seemed not all that generalizable, so I didn't bother filing a feature request. If there's a way to do it that make sense, though, I'm all for it!

**Comment by rcoh** [comment]
that totally makes sense. I think we should probably support it. I assume you saw: https://docs.aws.amazon.com/sdk-for-rust/latest/dg/localstack.html

I might convert the client builder into a macro? But I think a global endpoint override is probably not a bad idea.

**Comment by benesch** [comment]
> that totally makes sense. I think we should probably support it. I assume you saw: https://docs.aws.amazon.com/sdk-for-rust/latest/dg/localstack.html

Oh, no, I hadn't! Exciting. I didn't realize Localstack was (semi?) officially recognized by Amazon.

**Comment by rcoh** [comment]
fix in https://github.com/awslabs/smithy-rs/pull/1002/files

**Comment by benesch** [comment]
Sweet! Want me to file a separate issue for the global endpoint override?

**Comment by benesch** [comment]
> Sweet! Want me to file a separate issue for the global endpoint override?

A little slow, but I filed #396 for this!
