### ISSUE TITLE
[request]: Allow passing in aws_access_key_id and secret (or document if already possible)

### ISSUE THREAD

**Issue by dspadea** [awslabs/aws-sdk-rust#356]
### Tell us about your request

I can't seem to find a way to pass in an arbitrary `aws_access_key_id` and `aws_secret_access_key` when configuring a client. Please provide a way, or provide docs/examples of how it can be done currently. 

### Tell us about the problem you're trying to solve.

My use case is that I need to be able to supply an arbitrary key/secret per request, and use that for the client. 

I'd like to be able to do something like the following, but with `.credentials(key, secret)` or similar. 

```
let shared_config = aws_config::from_env().region(region_provider).load().await;
```

I looked into how to build a CredentialsProvider, but that looks way too complicated for such a simple thing, and I figured I was going down the wrong road.

### Are you currently working around this issue?

```
    std::env::set_var("AWS_ACCESS_KEY_ID", creds.0);
    std::env::set_var("AWS_SECRET_ACCESS_KEY", creds.1);

    let shared_config = aws_config::from_env().region(region_provider).load().await;

    let client = Client::new(&shared_config);

   [... do stuff...]

    std::env::remove_var("AWS_ACCESS_KEY_ID");
    std::env::remove_var("AWS_SECRET_ACCESS_KEY");

```

I suspect this introduces a race condition between concurrent runs, and is insecure to boot, but it's just a stopgap until I figure out how to do it properly so I can write the rest of my logic in the meantime.

**Comment by rcoh** [comment]
https://docs.rs/aws-types/0.3.0/aws_types/credentials/struct.Credentials.html#method.from_keys

Note that you'll need to enable the `hardcoded-credentials` feature.
