### ISSUE TITLE
Missing documentation links

### ISSUE THREAD

**Issue by zamazan4ik** [awslabs/aws-sdk-rust#357]
### What is the problem?

There are places in the documentation with broken links. As an example consider [this](https://docs.rs/aws-sdk-gamelift/latest/aws_sdk_gamelift/client/fluent_builders/struct.ClaimGameServer.html) "(using UpdateGameServer )" and many others places.

I guess it should be linked to something: related Rust primitive or to the corresponding AWS documentation - I don't know which way will be better.

### Version

Any

### Platform

Any

### AWS Services

I've checked only AWS Gamelift related documentation but possibly other services are affected too.

**Comment by Velfi** [comment]
I looked into the cause of this and it comes down to the models including anchor tags (`<a></a>`) with no `href` attribute. Long term, it would be good if we could parse these out and manually insert the correct link but that involves a non-trivial amount of work. In the short term, the fix will be to strip the anchor tags or replace them with preformatted tags (`<pre></pre>`) as some of the other SDKs do.
