### ISSUE TITLE
aws_sdk_dynamodb KeysAndAttributes not accepting params in docs

### ISSUE THREAD

**Issue by PatrickMcLennan** [awslabs/aws-sdk-rust#358]
### What is the problem?

I'm attempting to invoke the `batch_get_item` method on the `aws_sdk_dynamodb::Client`.

The [BatchGetItem](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/client/fluent_builders/struct.BatchGetItem.html) docs here list a `KeysAndAttributes` param as the 2nd argument to the `request_items` function.  The [KeysAndAttributes](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/model/struct.KeysAndAttributes.html) docs lists a `Vec<HashMap<String, AttributeValue>>` as the param type for it's `keys` function.

Pictured below -- I'm unable to get the `keys` method to accept this kind of argument (`get_keys`). Conversely, I _can_ get `keys()` to accept a single `HashMap`, but my `batch_get_item()` then fails as I'm querying by multiple composite primary keys, which I don't think I can do via a single `(k, v)`.  The `Vec` type in the docs makes sense to me and I have a feeling the code in the crate doesn't reflect that.

![Screen Shot 2021-12-20 at 11 42 47 AM](https://user-images.githubusercontent.com/33186346/146802772-20d08829-59ce-4240-b3bb-4a2e30816e0c.png)

Here's the error:

```
error: the trait bound `HashMap<std::string::String, AttributeValue>: From<Vec<HashMap<std::string::String, AttributeValue>>>` is not satisfied
label: the trait `From<Vec<HashMap<std::string::String, AttributeValue>>>` is not implemented for `HashMap<std::string::String, AttributeValue>`
note: required because of the requirements on the impl of `Into<HashMap<std::string::String, AttributeValue>>` for `Vec<HashMap<std::string::String, AttributeValue>>`
label: the trait `From<Vec<HashMap<std::string::String, AttributeValue>>>` is not implemented for `HashMap<std::string::String, AttributeValue>`
```

I'll admit that I am not the greatest with Rust, so there may be a stupid mistake here :) .  If so, please consider this a request for working examples of both `batch_get_item` (with a composite primary key) and `batch_write_item`.

### Version

0.2.0

### Platform

root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### AWS Services

DynamoDB

### Description

Documented types for `KeysAndAttributes` method `keys` not being accepted on `batch_get_item` call.

**Comment by rcoh** [comment]
`keys` is a convenience method that will _append_ a single item (so you don't need to maintain the vec yourself). Since you already have a `Vec`, you should use `set_keys`: https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/model/keys_and_attributes/struct.Builder.html#method.set_keys

You'll find this pattern everywhere that a HashMap or Vec is expected (`set_xyz` accepts a collection) vs. `xyz` accepting an element of the collection.

**Comment by PatrickMcLennan** [comment]
Yup, this was the issue.  Changing

```rust
.keys(get_keys)
```

to 
```rust
.set_keys(Some(get_keys))
```

works as intended.

Thanks for the quick help and tips @rcoh.
