### ISSUE TITLE
How to fix sleep_impl warning when ECS credential provider is used?

### ISSUE THREAD

**Issue by eagletmt** [awslabs/aws-sdk-rust#359]
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

I'm running applications with aws-sdk-rust v0.3.0 in ECS. When I set RUST_LOG=warn, it always displays a warning about sleep_impl.

```
% cat Cargo.toml
[package]
name = "rust-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.3"
aws-sdk-sts = "0.3"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
% cat src/main.rs
#[tokio::main]
async fn main() -> Result<(), aws_sdk_sts::Error> {
    tracing_subscriber::fmt::init();

    let config = aws_config::load_from_env().await;
    let client = aws_sdk_sts::Client::new(&config);
    client.get_caller_identity().send().await?;

    Ok(())
}
% RUST_LOG=warn AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/credentials/fake cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/rust-sandbox`
2021-12-20T16:47:59.784867Z  WARN aws_smithy_client::builder: Retries require a `sleep_impl`, but none was passed into the builder. No retries will occur with the current configuration. If this was intentional, you can suppress this message with `Client::set_sleep_impl(None). Otherwise, unless you have a good reason to use the low-level service client API, consider using the `aws-config` crate to load a shared config from the environment, and construct a fluent client from that. If you need to use the low-level service client API, then pass in a sleep implementation to make timeouts and retry work.
2021-12-20T16:48:01.788144Z  WARN aws_config::meta::credentials::chain: provider failed to provide credentials provider=EcsContainer error=Unexpected credentials error: timeout: error trying to connect: HTTP connect timeout occurred after 2s
Error: Unhandled(ConstructionFailure(CredentialsLoadingError(Unhandled { cause: DispatchFailure(ConnectorError { err: hyper::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 2s }), kind: Timeout }) })))
```

The second warning is ok; the timeout was caused by my fake AWS_CONTAINER_CREDENTIALS_RELATIVE_URI value.
I cannot figure out how to fix the first `sleep_impl` warning. The same warning is also displayed in my real ECS environment when RUST_LOG is set.

### Platform/OS/Device

Linux

### Language Version

Rust 1.57.0

**Comment by rcoh** [comment]
this looks like a bug! we'll get a fix out in the next release

**Comment by rcoh** [comment]
A fix will go out in 0.4.0! Thanks as always for your keen eye. It's worth noting that the message is accurate in that there won't be retries for the ECS provider until this bug is fixed

**Comment by Velfi** [comment]
If I understand your issue correctly, it's because you're using the low-level config creation API instead of loading it from your environment. We tried to explain it in that warning message and I'd love to hear if you have any suggestions on how to make it clearer.

> Otherwise, unless you have a good reason to use the low-level service client API, consider using the `aws-config` crate to load a shared config from the environment, and construct a fluent client from that.

Is there a reason you are using the low-level API instead of `let config = aws_config::load_from_env().await;`? You may be able to update your code like this to start benefiting from the defaults it sets:

```rust
let config = aws_config::from_env()
 .endpoint_resolver(Endpoint::immutable(endpoint))
 .region(Region::new(region))
 .credentials_provider(Credentials::new(
   "access-key"
   "secret-access-key",
   None,
   None,
   "environment",
 ))
.load().await;
let client = Client::from_conf(config);
```

> If you need to use the low-level service client API, then pass in a sleep implementation to make timeouts and retry work.

If you really do need to use the low-level API, then you need to set your own sleep implementation. If you're using tokio, then you can use the sleep impl that we default to in the high-level API:

```rust
use aws_smithy_async::rt::sleep::default_async_sleep;

let config = Config::builder()
 .endpoint_resolver(Endpoint::immutable(endpoint))
 .region(Region::new(region))
 .sleep_impl(default_async_sleep())
 .credentials_provider(Credentials::new(
   "access-key"
   "secret-access-key",
   None,
   None,
   "environment",
 ))
 .build();
let client = Client::from_conf(config);
```

**Comment by sdlarsen** [comment]
I see this too using aws-sdk-s3 0.11 with the following code:
```
        let region_provider = RegionProviderChain::first_try(region)
            .or_default_provider()
            .or_else(Region::new("us-east-1"));

        let config = aws_config::from_env()
            .region(region_provider.region().await)
            .load()
            .await;

        client: Client::new(&config),
```
I'm off to try adding retry config explicitly...

**Comment by sdlarsen** [comment]
Thanks @jdisanti, all is well now. Sorry for the noise.
