### ISSUE TITLE
can i use se sdk for other s3 compatible services?

### ISSUE THREAD

**Issue by SamyakGangwal** [awslabs/aws-sdk-rust#365]
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

I have digitlaocean spaces api with me, I wanted to ask how I can use the s3 sdk with digitalocean spaces.

### Platform/OS/Device

Ubuntu

### Language Version

rust 1.58.0

**Comment by rcoh** [comment]
It's possible to set a custom endpoint: https://docs.aws.amazon.com/sdk-for-rust/latest/dg/dynamodb-local.html

We can't guarantee compatibility with s3-compatible services, of course, but if you have problems, feel free to file an issue or update the ticket here.

**Comment by Velfi** [comment]
Closing this since Russell answered it.
