### ISSUE TITLE
Missing crates for 0.4.0 release

### ISSUE THREAD

**Issue by mlafeldt** [awslabs/aws-sdk-rust#388]
### What is the problem?

There are no updated crates for the latest release (https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.4.0) on crates.io.

For example, https://crates.io/crates/aws-sdk-s3 is still at 0.3.0. Forgot to publish them? :)

### Version

0.4.0

### Platform

-

**Comment by rcoh** [comment]
Sorry, they're coming out today

**Comment by rcoh** [comment]
release is going out as we speak
