### ISSUE TITLE
How to enable path style for s3 services?

### ISSUE THREAD

**Issue by Xuanwo** [awslabs/aws-sdk-rust#390]
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

How to enable path style for s3 compatible service?

For example, to use minio, we need to enable path style so that we can send request to `127.0.0.1:3000/bucket`.

### Platform/OS/Device

All

### Language Version

Rust 1.17.0

**Comment by rcoh** [comment]
currently the SDK will _only_ use path style, I believe. Let me know if you see different behavior.

**Comment by Xuanwo** [comment]
Oh, because the [deprecation plan of path style](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/), I thought the new sdk will use virtual host api style by default.

Please allow me to correct my question: How to control the api style between virtual host style and path style?

Thanks!

**Comment by rossng** [comment]
I just bumped into this issue because the SDK was generating virtual-host style URLs that didn't work with my Minio server. I'm guess that it might be due to [this call](https://github.com/awslabs/aws-sdk-rust/blob/39d457149ac9ed01e73bb274dfe4341e82c8bbc3/sdk/s3/src/endpoint/internals.rs#L1982), which appears to hardcode construction of a virtual-host style URL in some cases. (My server has a hostname like `my-machine.local`, which triggers whatever logic is deciding here).

**Comment by rcoh** [comment]
see this section of the [changelog](https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md):
```
Before, all requests hit the path-style endpoint. Going forward, all requests that can be routed to the virtually hosted bucket will be routed there automatically.

force_path_style: Requests will now default to the virtually-hosted endpoint <bucketname>.s3.<region>.amazonaws.com
```

You want to set `force_path_style(true)` on `aws_sdk_s3::Config` during client construction. Here's an example from the S3 tests: https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/s3/tests/endpoints.rs#L36-L43

**Comment by rossng** [comment]
Excellent - somehow I missed that on the config object. Thanks!
