### ISSUE TITLE
[request]: Add global endpoint override to `aws_config::Config`

### ISSUE THREAD

**Issue by benesch** [awslabs/aws-sdk-rust#396]
### Tell us about your request

Add an `endpoint` field to `aws_config::Config` that serves a global endpoint override. See discussion here: https://github.com/awslabs/aws-sdk-rust/issues/352#issuecomment-996777899

### Tell us about the problem you're trying to solve.

Configure all SDK clients to point at a LocalStack instance for testing.

### Are you currently working around this issue?

Yes, at @MaterializeInc we wrap the `aws_config::Config` type in our own configuration type to attach a global endpoint override: https://dev.materialize.com/api/rust/mz_aws_util/config/struct.AwsConfig.html

**Comment by necaris** [comment]
@rcoh any chance you've got an estimate for when this might land, or would accept a PR to implement it?

**Comment by benesch** [comment]
Great! I sent https://github.com/awslabs/smithy-rs/pull/1300. Unfortunately it ends up being a much larger change than I'd hoped, because it introduces a circular dependency between `aws-endpoint` and `aws-types`. I just merged the `aws-endpoint` crate into the `aws-types` crate in my PR, but I can imagine that you'd want to do something more principled.

**Comment by rcoh** [comment]
released in v0.10.1. Thanks @benesch for your work on this!!
