### ISSUE TITLE
Warnings on Lambda due to failure to select default profile

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-sdk-rust#398]
### What is the problem?

When using the AWS SDK for Rust in a Lambda function, it generates 14 tracing events with INFO and WARN log levels during initialization, due to a lack of `~/.aws` folder and default profile in a Lambda environment.

### Version

├── aws-config v0.4.1 │   ├── aws-http v0.4.1 │   │   ├── aws-smithy-http v0.34.1 │   │   │   ├── aws-smithy-types v0.34.1 │   │   ├── aws-smithy-types v0.34.1 (*) │   │   ├── aws-types v0.4.1 │   │   │   ├── aws-smithy-async v0.34.1 │   │   │   ├── aws-smithy-types v0.34.1 (*) │   ├── aws-sdk-sts v0.4.1 │   │   ├── aws-endpoint v0.4.1 │   │   │   ├── aws-smithy-http v0.34.1 (*) │   │   │   ├── aws-types v0.4.1 (*) │   │   ├── aws-http v0.4.1 (*) │   │   ├── aws-sig-auth v0.4.1 │   │   │   ├── aws-sigv4 v0.4.1 │   │   │   │   ├── aws-smithy-http v0.34.1 (*) │   │   │   ├── aws-smithy-http v0.34.1 (*) │   │   │   ├── aws-types v0.4.1 (*) │   │   ├── aws-smithy-async v0.34.1 (*) │   │   ├── aws-smithy-client v0.34.1 │   │   │   ├── aws-smithy-async v0.34.1 (*) │   │   │   ├── aws-smithy-http v0.34.1 (*) │   │   │   ├── aws-smithy-http-tower v0.34.1 │   │   │   │   ├── aws-smithy-http v0.34.1 (*) │   │   │   ├── aws-smithy-protocol-test v0.34.1 │   │   │   ├── aws-smithy-types v0.34.1 (*) │   │   ├── aws-smithy-http v0.34.1 (*) │   │   ├── aws-smithy-http-tower v0.34.1 (*) │   │   ├── aws-smithy-query v0.34.1 │   │   │   ├── aws-smithy-types v0.34.1 (*) │   │   ├── aws-smithy-types v0.34.1 (*) │   │   ├── aws-smithy-xml v0.34.1 │   │   ├── aws-types v0.4.1 (*) │   ├── aws-smithy-async v0.34.1 (*) │   ├── aws-smithy-client v0.34.1 (*) │   ├── aws-smithy-http v0.34.1 (*) │   ├── aws-smithy-http-tower v0.34.1 (*) │   ├── aws-smithy-json v0.34.1 │   │   └── aws-smithy-types v0.34.1 (*) │   ├── aws-smithy-types v0.34.1 (*) │   ├── aws-types v0.4.1 (*) ├── aws-sdk-dynamodb v0.4.1 │   ├── aws-endpoint v0.4.1 (*) │   ├── aws-http v0.4.1 (*) │   ├── aws-sig-auth v0.4.1 (*) │   ├── aws-smithy-async v0.34.1 (*) │   ├── aws-smithy-client v0.34.1 (*) │   ├── aws-smithy-http v0.34.1 (*) │   ├── aws-smithy-http-tower v0.34.1 (*) │   ├── aws-smithy-json v0.34.1 (*) │   ├── aws-smithy-types v0.34.1 (*) │   ├── aws-types v0.4.1 (*) ├── aws-sdk-eventbridge v0.4.1 │   ├── aws-endpoint v0.4.1 (*) │   ├── aws-http v0.4.1 (*) │   ├── aws-sig-auth v0.4.1 (*) │   ├── aws-smithy-async v0.34.1 (*) │   ├── aws-smithy-client v0.34.1 (*) │   ├── aws-smithy-http v0.34.1 (*) │   ├── aws-smithy-http-tower v0.34.1 (*) │   ├── aws-smithy-json v0.34.1 (*) │   ├── aws-smithy-types v0.34.1 (*) │   ├── aws-types v0.4.1 (*) ├── aws-smithy-client v0.34.1 (*) ├── aws-smithy-http v0.34.1 (*) ├── aws-types v0.4.1 (*) ├── aws-types v0.4.1 (*)

### Platform

Darwin <REDACTED> 19.6.0 Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64 x86_64

### AWS Services

DynamoDB
EventBridge

### Description

When using the AWS SDK for Rust in an AWS Lambda, it produces 14 INFO and WARN tracing events for CloudWatch Logs entries related to loading files in the `~/.aws` folder (non-existent on Lambda) or failure to get the default profile (also non-existent on Lambda).

I expect to not see any INFO/WARN message related to the initialization of the SDK, or at least not that many, as this is a different behavior than the other AWS SDK.

Here's the part of the code that initialize the AWS Config:

```rust
let config = aws_config::load_from_env().await;
```

The complete code can be found [in this repository](https://github.com/aws-samples/serverless-rust-demo/blob/main/src/utils.rs#L17).

This is similar in nature to https://github.com/awslabs/aws-sdk-rust/issues/307, but the warning messages are different.

### Logs

Log entries from CloudWatch Logs using INFO level:

```json
{"timestamp":"Jan 12 11:56:18.763","level":"INFO","fields":{"message":"config file not found","path":"~/.aws/config"},"target":"aws_config::profile::parser::source","span":{"name":"load_config_file"},"spans":[{"name":"get_store"},{"name":"load_config_file"}]}
{"timestamp":"Jan 12 11:56:18.763","level":"INFO","fields":{"message":"config file loaded","path":"~/.aws/config","size":"0"},"target":"aws_config::profile::parser::source","span":{"name":"load_config_file"},"spans":[{"name":"get_store"},{"name":"load_config_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file not found","path":"~/.aws/credentials"},"target":"aws_config::profile::parser::source","span":{"name":"load_credentials_file"},"spans":[{"name":"get_store"},{"name":"load_credentials_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file loaded","path":"~/.aws/credentials","size":"0"},"target":"aws_config::profile::parser::source","span":{"name":"load_credentials_file"},"spans":[{"name":"get_store"},{"name":"load_credentials_file"}]}
{"timestamp":"Jan 12 11:56:18.764","level":"WARN","fields":{"message":"failed to get selected 'default' profile"},"target":"aws_config::profile::retry_config","span":{"name":"get_store"},"spans":[{"name":"get_store"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file not found","path":"~/.aws/config"},"target":"aws_config::profile::parser::source","span":{"name":"load_config_file"},"spans":[{"name":"get_store"},{"name":"load_config_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file loaded","path":"~/.aws/config","size":"0"},"target":"aws_config::profile::parser::source","span":{"name":"load_config_file"},"spans":[{"name":"get_store"},{"name":"load_config_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file not found","path":"~/.aws/credentials"},"target":"aws_config::profile::parser::source","span":{"name":"load_credentials_file"},"spans":[{"name":"get_store"},{"name":"load_credentials_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file loaded","path":"~/.aws/credentials","size":"0"},"target":"aws_config::profile::parser::source","span":{"name":"load_credentials_file"},"spans":[{"name":"get_store"},{"name":"load_credentials_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file not found","path":"~/.aws/config"},"target":"aws_config::profile::parser::source","span":{"name":"load_config_file"},"spans":[{"name":"get_store"},{"name":"load_config_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file loaded","path":"~/.aws/config","size":"0"},"target":"aws_config::profile::parser::source","span":{"name":"load_config_file"},"spans":[{"name":"get_store"},{"name":"load_config_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file not found","path":"~/.aws/credentials"},"target":"aws_config::profile::parser::source","span":{"name":"load_credentials_file"},"spans":[{"name":"get_store"},{"name":"load_credentials_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"INFO","fields":{"message":"config file loaded","path":"~/.aws/credentials","size":"0"},"target":"aws_config::profile::parser::source","span":{"name":"load_credentials_file"},"spans":[{"name":"get_store"},{"name":"load_credentials_file"}]} 
{"timestamp":"Jan 12 11:56:18.764","level":"WARN","fields":{"message":"failed to get selected 'default' profile, skipping it"},"target":"aws_config::profile::timeout_config","span":{"name":"get_store"},"spans":[{"name":"get_store"}]} 
```

**Comment by Velfi** [comment]
This was fixed in v0.5.2
