### ISSUE TITLE
[request]: Add support for modeled waiters

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#400]
### Tell us about your request

Add support for waiters https://awslabs.github.io/smithy/1.0/spec/waiters.html

### Tell us about the problem you're trying to solve.

deal with eventually consistent APIs like DynamoDB create table

### Are you currently working around this issue?

manually implementing my own retry policy

**Comment by jdisanti** [comment]
Implementation is being tracked in https://github.com/awslabs/smithy-rs/issues/119

**Comment by jmklix** [comment]
https://github.com/smithy-lang/smithy-rs/issues/119#issuecomment-2067193091
> Implemented in [smithy-rs#3595](https://github.com/awslabs/smithy-rs/issues/3595), [smithy-rs#3593](https://github.com/awslabs/smithy-rs/issues/3593), [smithy-rs#3585](https://github.com/awslabs/smithy-rs/issues/3585), [smithy-rs#3571](https://github.com/awslabs/smithy-rs/issues/3571), and [smithy-rs#3569](https://github.com/awslabs/smithy-rs/issues/3569).
