### ISSUE TITLE
[request]: Common struct Tag

### ISSUE THREAD

**Issue by imp** [awslabs/aws-sdk-rust#402]
### Tell us about your request

Tagging is very common feature used universally across most (if not all) the AWS services. However this SDK defines `struct Tag` independently in every service crate, thus making them all incompatible. It may be beneficial to define this struct in some common place and use it in downstream crates instead of redefining it all over again. Along with making all tags compatible (Rust-wise) it will also reduce compilation time a [tiny] bit.

### Tell us about the problem you're trying to solve.

I am trying to tag various resources coming from different service crates. I would like to create a common `Tag` structure and use it everywhere. Right now I need to recreate `struct Tag` for every service individually because all of them are incompatible (despite being literally same).

### Are you currently working around this issue?

No

**Comment by rcoh** [comment]
Please see (and feel free to leave your thoughts!) at https://github.com/awslabs/aws-sdk-rust/discussions/75
