### ISSUE TITLE
[request]: Share `AttributeValue` model between dynamodb and dynamodbstreams

### ISSUE THREAD

**Issue by simonvandel** [awslabs/aws-sdk-rust#404]
### Tell us about your request

Would it be possible to use the same model for `AttributeValue` for `aws-sdk-dynamodb` and `aws-sdk-dynamodbstreams`? AFAICT they are exactly the same.

https://docs.rs/aws-sdk-dynamodb/0.4.1/src/aws_sdk_dynamodb/model.rs.html#6521-6563
https://docs.rs/aws-sdk-dynamodbstreams/latest/src/aws_sdk_dynamodbstreams/model.rs.html#822-864

### Tell us about the problem you're trying to solve.

I was looking at [serde_dynamo](https://docs.rs/serde_dynamo/3.0.0-alpha.3/serde_dynamo/index.html) which has support for `aws-sdk-dynamodb` but not for `aws-sdk-dynamodbstreams`.

If the two crates shared the same model, `serde_dynamo` would trivially support both use cases.

### Are you currently working around this issue?

-

**Comment by rcoh** [comment]
Please see (and feel free to leave your thoughts!) at https://github.com/awslabs/aws-sdk-rust/discussions/75
