### ISSUE TITLE
Automatically detect and prevent breaking changes

### ISSUE THREAD

**Issue by Velfi** [awslabs/aws-sdk-rust#410]
### Tell us about your request

Create a CI script that scans the SDK at some point before a release and ensures that no breaking changes were introduced that broke backwards compatibility

### Tell us about the problem you're trying to solve.

Breaking changes are a significant event. This tool would ensure that we don't unintentionally release a new version with a breaking change.

### Are you currently working around this issue?

n/a

### Additional context

- [ ] additional tooling around rust semVerVer run it
- [ ] https://github.com/awslabs/smithy-rs/pull/1194

**Comment by jdisanti** [comment]
Opting to track this exclusively in https://github.com/awslabs/smithy-rs/issues/535
