### ISSUE TITLE
No `SentTimestamp` variant for `aws_sdk_sqs::model::QueueAttributeName`

### ISSUE THREAD

**Issue by jszwedko** [awslabs/aws-sdk-rust#411]
### What is the problem?

It looks like there is no `SentTimestamp` variant on `aws_sdk_sqs::model::QueueAttributeName` though it is listed as an example variant on https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/client/fluent_builders/struct.ReceiveMessage.html#method.attribute_names. Instead you have to pass `Unknown("SentTimestamp")`.

I think this is likely to be a problem in the data model for the `ReceiveMessage` API. You can see on https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html that the examples listed don't all appear in the "Valid Values" section.

### Version

```
├── aws-config v0.4.1
│   ├── aws-http v0.4.1
│   │   ├── aws-smithy-http v0.34.1
│   │   │   ├── aws-smithy-types v0.34.1
│   │   ├── aws-smithy-types v0.34.1 (*)
│   │   ├── aws-types v0.4.1
│   │   │   ├── aws-smithy-async v0.34.1
│   │   │   ├── aws-smithy-types v0.34.1 (*)
│   ├── aws-sdk-sts v0.4.1
│   │   ├── aws-endpoint v0.4.1
│   │   │   ├── aws-smithy-http v0.34.1 (*)
│   │   │   ├── aws-types v0.4.1 (*)
│   │   ├── aws-http v0.4.1 (*)
│   │   ├── aws-sig-auth v0.4.1
│   │   │   ├── aws-sigv4 v0.4.1
│   │   │   │   ├── aws-smithy-http v0.34.1 (*)
│   │   │   ├── aws-smithy-http v0.34.1 (*)
│   │   │   ├── aws-types v0.4.1 (*)
│   │   ├── aws-smithy-async v0.34.1 (*)
│   │   ├── aws-smithy-client v0.34.1
│   │   │   ├── aws-smithy-async v0.34.1 (*)
│   │   │   ├── aws-smithy-http v0.34.1 (*)
│   │   │   ├── aws-smithy-http-tower v0.34.1
│   │   │   │   ├── aws-smithy-http v0.34.1 (*)
│   │   │   ├── aws-smithy-types v0.34.1 (*)
│   │   ├── aws-smithy-http v0.34.1 (*)
│   │   ├── aws-smithy-http-tower v0.34.1 (*)
│   │   ├── aws-smithy-query v0.34.1
│   │   │   ├── aws-smithy-types v0.34.1 (*)
│   │   ├── aws-smithy-types v0.34.1 (*)
│   │   ├── aws-smithy-xml v0.34.1
│   │   ├── aws-types v0.4.1 (*)
│   ├── aws-smithy-async v0.34.1 (*)
│   ├── aws-smithy-client v0.34.1 (*)
│   ├── aws-smithy-http v0.34.1 (*)
│   ├── aws-smithy-http-tower v0.34.1 (*)
│   ├── aws-smithy-json v0.34.1
│   │   └── aws-smithy-types v0.34.1 (*)
│   ├── aws-smithy-types v0.34.1 (*)
│   ├── aws-types v0.4.1 (*)
├── aws-sdk-sqs v0.4.1
│   ├── aws-endpoint v0.4.1 (*)
│   ├── aws-http v0.4.1 (*)
│   ├── aws-sig-auth v0.4.1 (*)
│   ├── aws-smithy-async v0.34.1 (*)
│   ├── aws-smithy-client v0.34.1 (*)
│   ├── aws-smithy-http v0.34.1 (*)
│   ├── aws-smithy-http-tower v0.34.1 (*)
│   ├── aws-smithy-query v0.34.1 (*)
│   ├── aws-smithy-types v0.34.1 (*)
│   ├── aws-smithy-xml v0.34.1 (*)
│   ├── aws-types v0.4.1 (*)
├── aws-types v0.4.1 (*)
```

### Platform

Darwin COMP-C02DV25MML87 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,2 Darwin

### AWS Services

AWS SQS

**Comment by Velfi** [comment]
Thanks for reporting this!

**Comment by Velfi** [comment]
I have submitted an internal ticket to the SQS service team. I'll keep an eye on it and update this issue as things progress. I don't know what priority it will be assigned so I don't have an estimate on when this will be fixed. Sorry about that and thank you for your patience.

**Comment by Velfi** [comment]
I have asked the service team for an update on this issue and I'm waiting to hear back from them.

**Comment by Velfi** [comment]
Apparently this has been an issue for some time and it's been reported in other SDKs:
https://github.com/aws/aws-sdk-java-v2/issues/1892
https://github.com/aws/aws-sdk-java-v2/issues/1117
https://github.com/aws/aws-sdk-java/issues/2061
https://github.com/aws/aws-sdk-java/issues/2324
https://github.com/aws/aws-sdk-php/issues/2007

The main difficulty is that updating the operation to point to the correct model would be a breaking change. I'm still not sure when they'll get to fixing this.

**Comment by jszwedko** [comment]
Thanks for the update @Velfi . I was afraid that might be the case. Maybe the SDK docs for this function could be updated instead?

**Comment by jmklix** [comment]
closing this issue after opening issue [here](https://github.com/aws/aws-sdk/issues/233) so it can be fixed for all sdks
