### ISSUE TITLE
[request]: Anonymous Credentials Provider

### ISSUE THREAD

**Issue by seddonm1** [awslabs/aws-sdk-rust#425]
### Community Note
Please upvote this issue by reacting with 👍🏻  to help us prioritize!

### Tell us about your request

The Java SDK has an Anonymous Credentials Provider (https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AnonymousCredentialsProvider.java) which allows accessing AWS Open Data like (https://registry.opendata.aws/nyc-tlc-trip-records-pds/) without having to provide credentials (see `aws s3 ls s3://nyc-tlc/ --no-sign-request`)

There does not appear to be an equivalent for the Rust SDK.

### Tell us about the problem you're trying to solve.

Access AWS Open Data, e.g. https://registry.opendata.aws/nyc-tlc-trip-records-pds/ 

### Are you currently working around this issue?

No workaround.

**Comment by seddonm1** [comment]
Thank you for your thorough response @rcoh and I appreciate you providing a workaround.

I hope you are able to work out (as you say) a more ergonomic answer than this and potentially add it to the default credentials chain even if this is not necessarily a common requirement.

**Comment by Xuanwo** [comment]
Maybe we can change `signing_config.signing_requirements` in the `DefaultMiddleware` so that we don't need to `make_unsigned` for every operation.

**Comment by Xuanwo** [comment]
Hello, everyone here, I got it works via middleware: https://github.com/datafuselabs/opendal/pull/97

No need to operate on a low-level request, everything works.

@rcoh Can you take a look at this PR? I'm willing to submit a PR back to `aws-sdk-rust` if there is an actionable route.

**Comment by Velfi** [comment]
This will soon be slightly easier to do pending the release of the changes from smithy-rs#1647:

```rust
#[tokio::main]
async fn main() {
    let conf = aws_config::load_from_env().await;
    let client = aws_sdk_s3::Client::new(&conf);
    let res = client
        .list_objects_v2()
        .bucket("genome-browser")
        .customize()
        .await
        .unwrap()
        .map_operation(make_unsigned)
        .unwrap()
        .send()
        .await
        .expect("request should succeed");

    for obj in res.contents().unwrap_or_default() {
        println!("{}", obj.key().unwrap_or_default());
    }
}

fn make_unsigned<O, Retry>(
    mut operation: aws_smithy_http::operation::Operation<O, Retry>,
) -> Result<aws_smithy_http::operation::Operation<O, Retry>, std::convert::Infallible> {
    {
        let mut props = operation.properties_mut();
        let mut signing_config = props
            .get_mut::<aws_sig_auth::signer::OperationSigningConfig>()
            .expect("has signing_config");
        signing_config.signing_requirements = aws_sig_auth::signer::SigningRequirements::Disabled;
    }

    Ok(operation)
}
```

The "Customizable Operations" feature will ship with versions `0.49.0`/`0.19.0` which will _(famous last words)_ probably arrive some time next week.

**Comment by seddonm1** [comment]
Thank you @Velfi . We can probably close this issue then?

**Comment by jdisanti** [comment]
> We can probably close this issue then?

Keeping this open because it seems like there should be an easier way to do this.

**Comment by jdisanti** [comment]
The `aws-config` now has a `no_credentials()` method on it to specify anonymous auth. If you're not using `aws-config`, then you can have the same behavior by not setting a credentials provider for services that support it.
