### ISSUE TITLE
Build on nightly fails 

### ISSUE THREAD

**Issue by imp** [awslabs/aws-sdk-rust#446]
### What is the problem?

Building on recent `nightly` channel (as of Feb 10, 2022) fails with
```
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-0.36.0/src/operation.rs:272:48
    |
272 |             let properties: &mut PropertyBag = &mut self.properties.acquire_mut();
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `PropertyBag`, found opaque type
    |
   ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/aws-smithy-http-0.36.0/src/property_bag.rs:213:34
    |
213 |     pub fn acquire_mut(&self) -> impl DerefMut<Target = PropertyBag> + '_ {
    |                                  ---------------------------------------- the found opaque type
    |
    = note:   expected struct `PropertyBag`
            found opaque type `impl Deref<Target = PropertyBag> + DerefMut`
```

### Version

├── aws-config v0.6.0 │   ├── aws-http v0.6.0 │   │   ├── aws-smithy-http v0.36.0 │   │   │   ├── aws-smithy-types v0.36.0 │   │   ├── aws-smithy-types v0.36.0 (*) │   │   ├── aws-types v0.6.0 │   │   │   ├── aws-smithy-async v0.36.0 │   │   │   ├── aws-smithy-types v0.36.0 (*) │   ├── aws-sdk-sso v0.6.0 │   │   ├── aws-endpoint v0.6.0 │   │   │   ├── aws-smithy-http v0.36.0 (*) │   │   │   ├── aws-types v0.6.0 (*) │   │   ├── aws-http v0.6.0 (*) │   │   ├── aws-sig-auth v0.6.0 │   │   │   ├── aws-sigv4 v0.6.0 │   │   │   │   ├── aws-smithy-http v0.36.0 (*) │   │   │   ├── aws-smithy-http v0.36.0 (*) │   │   │   ├── aws-types v0.6.0 (*) │   │   ├── aws-smithy-async v0.36.0 (*) │   │   ├── aws-smithy-client v0.36.0 │   │   │   ├── aws-smithy-async v0.36.0 (*) │   │   │   ├── aws-smithy-http v0.36.0 (*) │   │   │   ├── aws-smithy-http-tower v0.36.0 │   │   │   │   ├── aws-smithy-http v0.36.0 (*) │   │   │   ├── aws-smithy-types v0.36.0 (*) │   │   ├── aws-smithy-http v0.36.0 (*) │   │   ├── aws-smithy-http-tower v0.36.0 (*) │   │   ├── aws-smithy-json v0.36.0 │   │   │   └── aws-smithy-types v0.36.0 (*) │   │   ├── aws-smithy-types v0.36.0 (*) │   │   ├── aws-types v0.6.0 (*) │   ├── aws-sdk-sts v0.6.0 │   │   ├── aws-endpoint v0.6.0 (*) │   │   ├── aws-http v0.6.0 (*) │   │   ├── aws-sig-auth v0.6.0 (*) │   │   ├── aws-smithy-async v0.36.0 (*) │   │   ├── aws-smithy-client v0.36.0 (*) │   │   ├── aws-smithy-http v0.36.0 (*) │   │   ├── aws-smithy-http-tower v0.36.0 (*) │   │   ├── aws-smithy-query v0.36.0 │   │   │   ├── aws-smithy-types v0.36.0 (*) │   │   ├── aws-smithy-types v0.36.0 (*) │   │   ├── aws-smithy-xml v0.36.0 │   │   ├── aws-types v0.6.0 (*) │   ├── aws-smithy-async v0.36.0 (*) │   ├── aws-smithy-client v0.36.0 (*) │   ├── aws-smithy-http v0.36.0 (*) │   ├── aws-smithy-http-tower v0.36.0 (*) │   ├── aws-smithy-json v0.36.0 (*) │   ├── aws-smithy-types v0.36.0 (*) │   ├── aws-types v0.6.0 (*) ├── aws-sdk-cloudformation v0.6.0 │   ├── aws-endpoint v0.6.0 (*) │   ├── aws-http v0.6.0 (*) │   ├── aws-sig-auth v0.6.0 (*) │   ├── aws-smithy-async v0.36.0 (*) │   ├── aws-smithy-client v0.36.0 (*) │   ├── aws-smithy-http v0.36.0 (*) │   ├── aws-smithy-http-tower v0.36.0 (*) │   ├── aws-smithy-query v0.36.0 (*) │   ├── aws-smithy-types v0.36.0 (*) │   ├── aws-smithy-xml v0.36.0 (*) │   ├── aws-types v0.6.0 (*) ├── aws-sdk-ec2 v0.6.0 │   ├── aws-endpoint v0.6.0 (*) │   ├── aws-http v0.6.0 (*) │   ├── aws-sig-auth v0.6.0 (*) │   ├── aws-smithy-async v0.36.0 (*) │   ├── aws-smithy-client v0.36.0 (*) │   ├── aws-smithy-http v0.36.0 (*) │   ├── aws-smithy-http-tower v0.36.0 (*) │   ├── aws-smithy-query v0.36.0 (*) │   ├── aws-smithy-types v0.36.0 (*) │   ├── aws-smithy-xml v0.36.0 (*) │   ├── aws-types v0.6.0 (*)

### Platform

Darwin hellride.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Description

Compiling code that uses  AWS SDK. Compilation failure is in `aws-smithy-http`, which is not a direct dependency, so code example is not relevant. However, compiling `examples/ec2` exhibits the same issue.

**Comment by jdisanti** [comment]
Thanks for reporting!

I think this is caused by this stable-to-nightly regression: https://github.com/rust-lang/rust/issues/93841

It looks like it compiles on `nightly-2022-02-08` if you need to get unblocked.

**Comment by jdisanti** [comment]
I believe this has been fixed.
