### ISSUE TITLE
S3 PutObject appears to buffer entire body into memory

### ISSUE THREAD

**Issue by jclulow** [awslabs/aws-sdk-rust#453]
### What is the problem?

It doesn't seem like there is a way to pass a streaming buffer as the `body()` of an S3 request made via the `put_object()` builder without the client copying the whole body into memory (even if it is, say 800MB) prior to or during upload.

### Version

aws-sdk-s3 v0.6.0

### Platform

SunOS matrix-db0 5.11 omnios-r151038-31a842e2c6 i86pc i386 i86pc

### Description

It's totally possible I'm not holding this correctly, but I've tried a few different things; e.g.,

```rust
let tf = tokio::fs::File::from_std(largetempfile);
let res = s3
    .put_object()
    .bucket(&bucket)
    .key(&key)
    .metadata("md5", &md5_hex)
    .content_md5(&md5_base64)
    .content_length(size.try_into().unwrap())
    .body(aws_sdk_s3::ByteStream::from_file(tf.into()).await?)
    .send()
    .await;
```

I've also tried:

```rust
let tf = tokio::fs::File::from_std(tf);
let tfs = tokio_util::io::ReaderStream::new(tf);
let body = hyper::Body::wrap_stream(tfs);
let res = s3
    .put_object()
    .bucket(&bucket)
    .key(&key)
    .metadata("md5", &md5_hex)
    .content_md5(&md5_base64)
    .content_length(size.try_into().unwrap())
    .body(aws_sdk_s3::ByteStream::new(body.into()))
    .send()
    .await;
```

In both cases, as soon as we hit this call, the RSS of the process jumps from ~20MB right up to the ~800MB or so that would hold the contents of the temporary file.

Given that I am providing the content length already during request construction, is there some way that this could just be a streaming read without causing an explosion of memory usage?

Thanks.

**Comment by rcoh** [comment]
actually, if it's not too much of a pain, do you mind trying [`from_path`] as well? That's what you'll want to use anyway as `from_file` doesn't enable retries on server failure

**Comment by jclulow** [comment]
In this case I can't use a path because the file doesn't have one.  It's an anonymous temporary file; i.e., it has been unlinked and the only way to access it is through the file descriptor I have kept open.

I am managing my own retries in this case.

**Comment by rcoh** [comment]
I'm having trouble reproducing this—would it be possible to send a more complete program? The following program uses between 30-60MB for me:

```
➜  s3-buffer-size git:(main) ✗ du -h testfile
767M      testfile
```

```rust
use std::time::Duration;

use aws_sdk_s3::ByteStream;
#[tokio::main]
async fn main() {
    let file = tokio::fs::File::from_std(std::fs::File::open("testfile").unwrap());
    let meta = file.metadata().await.unwrap();

    let body = ByteStream::from_file(file).await.unwrap();
    let conf = aws_config::load_from_env().await;
    let client = aws_sdk_s3::Client::new(&conf);
    client
        .put_object()
        .bucket(".....")
        .content_length(meta.len() as i64)
        .key("test-object")
        .body(body)
        .send()
        .await
        .unwrap();
    println!("done");
    tokio::time::sleep(Duration::from_secs(10)).await;
}
```

```
➜  ~ ps x -o rss,vsz,command | grep s3-buffer | grep -v grep
 32976  4488352 target/debug/s3-buffer-size
```

**Comment by jclulow** [comment]
Sorry, got distracted with other projects.  I'll put together a standalone reproduction.
