### ISSUE TITLE
[request]: aws-config: Allow to set `load_timeout` when constructing with `DefaultCredentialsChain`

### ISSUE THREAD

**Issue by yerke** [awslabs/aws-sdk-rust#462]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

Provide a way to set `load_timeout` on `LazyCachingCredentialsProvider` when constructing with `DefaultCredentialsChain`. Right now I don't see a way to override it without reimplementing `DefaultCredentialsChain`. 

### Tell us about the problem you're trying to solve.

I was getting `Error: failed to construct request: Failed to load credentials from the credentials provider: Credentials provider timed out after 5 seconds` when trying to get secret from `aws_sdk_secretsmanager::Client`.

### Are you currently working around this issue?

I had to use `WebIdentityTokenCredentialsProvider` directly, which is not recommended AFAIK.

### Additional context

```
aws-config = "0.6.0"
aws-sdk-secretsmanager = "0.6.0"
aws-types = "0.6.0"
```

This code was causing the issue.
```rust
let config = aws_config::from_env().load().await;
let client = Client::new(config);
let response = client.get_secret_value().secret_id("secret").send().await?;
```

Had to change into this
```rust
let provider = WebIdentityTokenCredentialsProvider::builder()
        .configure(&ProviderConfig::with_default_region().await)
        .build();
let config = aws_config::from_env()
        .credentials_provider(provider)
        .load()
        .await;
let client = Client::new(config);
let response = client.get_secret_value().secret_id("secret").send().await?;
```

**Comment by jdisanti** [comment]
Thanks for bringing this to our attention!

As of [v0.8.0](https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.8.0), it is now possible to set the load timeout (among other things) on the default credential chain. For example:
```rust
let default_provider = DefaultCredentialsChain::builder()
    .load_timeout(Duration::from_secs(20))
    .build();
let config = aws_config::from_env()
    .credentials_provider(default_provider)
    .load()
    .await;
let client = Client::new(config);
```
