### ISSUE TITLE
No longer able to initialize client

### ISSUE THREAD

**Issue by dallin-defimono** [awslabs/aws-sdk-rust#471]
### What is the problem?

Aws secret manager with aws_config no longer working.

```
expected struct `aws_types::config::Config`, found struct `aws_config::Config` 
Note: expected reference `&aws_types::config::Config` found reference `&aws_config::Config`
Note: perhaps two different versions of crate `aws_types` are being used?
```

No longer can initialize the clients following examples.

```
aws-sdk-secretsmanager = "0.7"
aws-config = "0.8"
```

The code block that fails, this is a barebones new project.

```
use aws_config::meta::region::RegionProviderChain;
use aws_sdk_secretsmanager::{Client, Error, PKG_VERSION, Region};
...

let region_provider: RegionProviderChain = RegionProviderChain::default_provider();
let shared_config = aws_config::from_env().region(region_provider).load().await;
let client = Client::new(&shared_config);
```

According to the error there are multiple initializations of the aws_types crate being exported and seem to be conflicting. I have seen this type of error when the compiler does not know which version to use and dies. Perhaps aws_config from the examples is no longer needed?

Note, this still fails too.

```
let shared_config: aws_sdk_secretsmanager::Config = aws_sdk_secretsmanager::Config::builder().build();
let client: aws_sdk_secretsmanager::Client = Client::new(&shared_config);
```
with message

```
expected struct `aws_types::config::Config`, found struct `aws_sdk_secretsmanager::Config` 
Note: expected reference `&aws_types::config::Config` found reference `&aws_sdk_secretsmanager::Config`
```

The docs inside the crate also fail:

```
let shared_config = aws_config::load_from_env().await;
let built_config = aws_sdk_secretsmanager::config::Builder::from(&shared_config).build();
let client = aws_sdk_secretsmanager::Client::from_conf(built_config);
```

with message

```
the trait bound `aws_sdk_secretsmanager::config::Builder: std::convert::From<&aws_config::Config>` is not satisfied 
E0277 the trait `std::convert::From<&aws_config::Config>` is not implemented for `aws_sdk_secretsmanager::config::Builder` Help: the following implementations were found: <aws_sdk_secretsmanager::config::Builder as std::convert::From<&aws_types::config::Config>>
```

### Version

aws-sdk-secretsmanager = "0.7" 
aws-config = "0.8"

### Platform

Ubuntu 20.04

### AWS Services

aws secret manager
aws config

### Description

Aws client initialization failure

**Comment by dallin-defimono** [comment]
Ah, it seems there needs to be some updating/syncing done to how types are exported and shared from crates. There exists a conflict between the aws_config and other sdk crates. When the crate versions match, the error resolves.

**Comment by rcoh** [comment]
Yeah, that's correct, the crate versions always need to match. Once we have moved to 1.0 it will be less of an issue as the minor versions will be considered compatible by Cargo.
