### ISSUE TITLE
[request]: Pre-signed URL for ListObjectsV2

### ISSUE THREAD

**Issue by stefanhoelzl** [awslabs/aws-sdk-rust#472]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

I would like to be able to pre-signed a URL for a ListObjectsV2 command, with a pre-signed prefix.

### Tell us about the problem you're trying to solve.

I want to be able to send out pre-signed links where the receiver of the link can perform a ListObjectsV2 command with a pre-defined prefix.
The receiver must be able to use the pre-signed URL multiple times in case of pagination.

### Are you currently working around this issue?

List operations are currently routed through my backend, so my backend performs the List operations and send the result back to the user.

**Comment by jdisanti** [comment]
Thank you for the feature request! I'm going to close this in favor of #488, which is tracking adding presigning to all the S3 operations.
