### ISSUE TITLE
How to use aws-sdk-iam `get_role`

### ISSUE THREAD

**Issue by craigkai** [awslabs/aws-sdk-rust#478]
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

I am looking to use `aws_sdk_iam` and the `get_role` method to get some info on one of my IAM roles and it is not clear to me how to provide the `roleName` argument for this. I know this must be easy but I am drawing a blank. I'd have thought I could provide the roleName here:
```
let resp = client
        .get_role(roleName)
        .send()
        .await?;
```
But that doesn't seem to the case as `get_role` does not accept any arguments. But if I pass nothing, I see the following error:

```
Err(Unhandled(Error { code: Some("ValidationError"), message: Some("1 validation error detected: Value null at 'roleName' failed to satisfy constraint: Member must not be null"), request_id: Some("..."), extras: {} }))
```

### Platform/OS/Device

Mac OSX

### Language Version

rustc 1.57.0

**Comment by jdisanti** [comment]
The role name is given as a separate builder function:
```rust
let resp = client.get_role()
    .role_name("some-role")
    .send()
    .await?;
```

The [`get_role`](https://docs.rs/aws-sdk-iam/0.8.0/aws_sdk_iam/client/struct.Client.html#method.get_role) client method merely returns a builder, which then [has methods on it](https://docs.rs/aws-sdk-iam/0.8.0/aws_sdk_iam/client/fluent_builders/struct.GetRole.html) to set the various arguments for the request.

**Comment by craigkai** [comment]
Thank you, I knew it must have been something obvious!
