### ISSUE TITLE
[request]: Allow specifying the role session length for AssumeRoleProvider

### ISSUE THREAD

**Issue by jbg** [awslabs/aws-sdk-rust#479]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

The ability to set the `DurationSeconds` field of the `sts:AssumeRole` request that `AssumeRoleProvider` makes behind the scenes.

### Tell us about the problem you're trying to solve.

We're using an assumed role to presign `s3:GetObject` URLs, and we want to be able to control the length of time the URLs are valid for. Presigned URLs produced using temporary credentials are valid for the _lesser_ of the signature validity period and the credential validity period, so using `AssumeRoleProvider` we can't produce any URLs that are valid for longer than 3600 seconds (the default validity period for `sts:AssumeRole`).

### Are you currently working around this issue?

We can manually call `sts:AssumeRole` using `aws-sdk-sts` and then produce the signed URLs using `aws-sig-auth`, but it's not nearly as ergonomic.

**Comment by rcoh** [comment]
This would be a useful feature 👍🏻 

In the short term, you can workaround this while maintaining ergonomics by using `sts::AssumeRole` to implement `ProvideCredentials`. You can pass that in as a credentials provider, enabling you to use the normal flow with longer-lived creds. It is also probably a fairly small change here: https://github.com/awslabs/smithy-rs/blob/main/aws/rust-runtime/aws-config/src/sts/assume_role.rs and we'd be happy to mentor / accept a PR.

**Comment by rcoh** [comment]
released in 0.10.1
