### ISSUE TITLE
[request]: Add Greengrass V2 example.

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/aws-sdk-rust#484]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

Add Greengrass V2 example, as well as Greengrass V1 (classic).
Like [list-core-devices](https://awscli.amazonaws.com/v2/documentation/api/2.1.30/reference/greengrassv2/list-core-devices.html).
Thanks.

### Tell us about the problem you're trying to solve.

Greengrass V2 example

### Are you currently working around this issue?

Yes

**Comment by jdisanti** [comment]
Tracking this in https://github.com/awsdocs/aws-doc-sdk-examples/issues/2963
