### ISSUE TITLE
[request]: Migrate to Rust 2021 edition

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-sdk-rust#490]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

Migrate to Rust 2021 edition.
Looks lots of examples works under 2021 edition now.

### Tell us about the problem you're trying to solve.

modernize.

### Are you currently working around this issue?

Yes.

**Comment by Velfi** [comment]
Hey @overheat, this isn't currently a high-priority issue for us and we don't expect to get to it soon but we encourage you to submit a PR if this is important to you.

**Comment by Velfi** [comment]
I had some free time and implemented this in [smithy-rs#1268](https://github.com/awslabs/smithy-rs/pull/1268). It'll go out in the next release

**Comment by rcoh** [comment]
released in v0.10.1
