### ISSUE TITLE
How to use client.list_time_series() method?

### ISSUE THREAD

**Issue by robertsarkozi** [awslabs/aws-sdk-rust#491]
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

I have the following piece of code, trying to get the time series/data streams information for one of my Assets in AWS IoT SiteWise:

```rust
use aws_config::meta::region::RegionProviderChain;
use aws_sdk_iotsitewise::{Error, Client};

#[tokio::main]
async fn main() -> Result<(), Error> {
    let region_provider = RegionProviderChain::default_provider().or_else("eu-central-1");
    let config = aws_config::from_env().region(region_provider).load().await;
    let client = Client::new(&config);

    let time_series_summaries = client.list_time_series().asset_id("7982cee4-affa-4488-9c92-e6210ef2065e").send().await?;

    for time_series_summary in time_series_summaries.time_series_summaries().unwrap_or_default() {
        println!("          {}", time_series_summary.alias().unwrap_or_default());
    }

    Ok(())
}
```
The code seems to fail with the following error message in the `...client.list_time_series()...send().await?` line, when I do `cargo run`:
```
    Finished dev [unoptimized + debuginfo] target(s) in 4.44s
     Running `target/debug/sitewise`
    Error: Unhandled(Error { code: None, message: Some("Unknown Operation"), request_id: None, extras: {} })
```
It doesn't reach the for loop, I get the same error if I execute without the loop.
`client.list_asset_models()` and `client.list_assets()` methods work.

`Cargo.toml` contains:
```
[dependencies]
aws-config = "0.8.0"
aws-sdk-iotsitewise = "0.8.0"
tokio = { version = "1", features = ["full"] }
```
Using AWS CLI version 2.4.27 works: `aws iotsitewise list-time-series --asset-id 7982cee4-affa-4488-9c92-e6210ef2065e`:
```
{
    "TimeSeriesSummaries": [
        {
            "assetId": "7982cee4-affa-4488-9c92-e6210ef2065e",
            "propertyId": "5349e4ec-8fe4-4007-b27f-3142753e6209",
            "alias": "/S7-Sim/DataBlocks/Datatypes_All/Real",
            "timeSeriesId": "6f92e33d-0cd3-4323-97e2-275a77173ade",
            "dataType": "DOUBLE",
            "timeSeriesCreationDate": "2021-11-24T10:29:45+02:00",
            "timeSeriesLastUpdateDate": "2021-11-24T10:50:36+02:00"
        }
    ]
}
```

Any help is appreciated.
NOTE: I'm new to Rust.

### Platform/OS/Device

arch linux/x86_64

### Language Version

rust 1.59; edition = '2021'

**Comment by rcoh** [comment]
Thanks for reporting! This seems likely to be a bug and we'll investigate. If you'd like, running the CLI with --debug and the rust sdk with trace logging enabled will reveal the difference between the http requests

**Comment by robertsarkozi** [comment]
The CLI tool with --debug parameter shows the request and response details, but in code I didn't manage to catch anything, maybe my lack of experience with rust debugging.

I also adapted this example here to try, maybe I'm not setting some environment stuff correctly, but I get the same error:
https://github.com/awslabs/aws-sdk-rust/pull/452/commits/186fa18a7bb82049d865e43cdf2bcfe523ce3942

How do I turn on trace logging for the SDK?

**Comment by jdisanti** [comment]
You can enable trace logging by installing the `tracing-subscriber` crate with the `env-filter` feature enabled, and initializing it with `tracing_subscriber::fmt::init();`. Then set the environment variable `RUST_LOG` before  running your program, as follows:

```
RUST_LOG='aws_smithy_http_tower::dispatch=trace,aws_smithy_http::middleware=trace'
```

For example:
```
RUST_LOG='aws_smithy_http_tower::dispatch=trace,aws_smithy_http::middleware=trace' cargo run
```

Note: The SDK redacts sensitive information such as auth headers in these trace logs, but please look through them before posting just to be sure.

**Comment by robertsarkozi** [comment]
Ok, I got the output, see them attached. I also upgraded to 0.9.0, error still occurs.

I'm not sure I see the difference, though:
[sitewise_example_output.txt](https://github.com/awslabs/aws-sdk-rust/files/8321880/sitewise_example_output.txt)
[aws_cli_output.txt](https://github.com/awslabs/aws-sdk-rust/files/8321882/aws_cli_output.txt)

**Comment by robertsarkozi** [comment]
Some more info:
// cli
// https://api.iotsitewise.eu-central-1.amazonaws.com/assets?assetModelId=314285b7-07b5-4a5c-8d13-036e9ba95b8f -- works
// https://api.iotsitewise.eu-central-1.amazonaws.com/timeseries/?assetId=7982cee4-affa-4488-9c92-e6210ef2065e -- works; uses '/'

// aws-sdk-rust code 
// https://api.iotsitewise.eu-central-1.amazonaws.com/assets?assetModelId=314285b7-07b5-4a5c-8d13-036e9ba95b8f -- works
// https://api.iotsitewise.eu-central-1.amazonaws.com/timeseries?assetId=7982cee4-affa-4488-9c92-e6210ef2065e -- does not work, may need '/'

I've run the same commands and API calls for getting the Asset Summaries as well, and the link used for them are above.
It seems a '/' may be needed to the `timeseries` endpoint, and CLI knows this.
In the SDK the code is generated using the smithy tool, which may not know about this "exception"...

**Comment by rcoh** [comment]
thanks for digging into this! I've reproduced this (and actually got a "fix" with a patched Rust SDK that sends a trailing slash). This seems to be an issue with the underlying models of this service which we're working on getting resolved. Thanks for reporting this!

**Comment by robertsarkozi** [comment]
Good to hear, thank you, too!

**Comment by rcoh** [comment]
this ended up being a bug in iotsitewise which was fixed upstream. Thanks again for reporting this!!
