### ISSUE TITLE
[request]: Add paginator for Route53 ListResourceRecordSets API

### ISSUE THREAD

**Issue by ojacobson** [awslabs/aws-sdk-rust#495]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

### Tell us about your request

The new pagination support is great, and I'd like to use it in more places. Please add support to it to the [ListResourceRecordSets](https://docs.rs/aws-sdk-route53/latest/aws_sdk_route53/client/fluent_builders/struct.ListResourceRecordSets.html) API client method.

### Tell us about the problem you're trying to solve.

I want to be able to iterate over multiple pages of resource record sets in a hosted zone reliably.

### Are you currently working around this issue?

My existing code uses a loop and maintains its own pagination:

```rust
    let mut next_record_name = Some(dns_suffix.to_ascii());
    let mut next_record_type = None;
    let mut next_record_identifier = None;

    loop {
        let records_resp = aws_context
            .route53()
            .list_resource_record_sets()
            .hosted_zone_id(zone_id)
            .set_start_record_name(next_record_name)
            .set_start_record_type(next_record_type)
            .set_start_record_identifier(next_record_identifier)
            .send()
            .await?;

        /* ... process one page of results ... */

        if records_resp.is_truncated() {
            next_record_name = records_resp.next_record_name().map(String::from);
            next_record_type = records_resp.next_record_type().map(Clone::clone);
            next_record_identifier = records_resp.next_record_identifier().map(String::from);
        } else {
            break;
        }
    }

```

**Comment by Velfi** [comment]
This is a modeling issue with the upstream service. I'll report it to them using our internal system. It can take some time for them to address issues like this depending on their workload. I'll update this ticket when I hear back from them.

**Comment by jmklix** [comment]
Opened an issue in aws/aws-sdk which is used to track issues across multiple sdks. Closing this issue
