### ISSUE TITLE
Config file credential providers

### ISSUE THREAD

**Issue by vishaalt** [awslabs/aws-sdk-rust#5]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

-->

**Tell us about your request**
Add support for config file credential providers
- [x] IMDS
- [x] ECS
- [x] EKS
- [x] WebIdentityToken
- [x] STS assume role

**Comment by rcoh** [comment]
IMDS support has landed and will go out in the next release
