### ISSUE TITLE
[request]: Provide a async API for different async runtime crates and also a sync API

### ISSUE THREAD

**Issue by jmklix** [awslabs/aws-sdk-rust#506]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/79

<div type='discussions-op-text'>

<sup>Originally posted by **howard-quantrend** May 12, 2021</sup>
Maybe the sdk could support both popular async runtimes, tokio and async-std using feature flags? In my case, our project only uses the async-std crate, so we need to rewrite the necessary parts of the Rusoto crate ourselves using async-std runtime. It will be great if the aws-sdk-rust supports both runtimes using feature flags, and even better if it provides a blocking sync API too, to support different kind of projects. Actually, this is what the [MongoDB rust driver](https://github.com/mongodb/mongo-rust-driver) does. Thanks.</div>

>You can actually use async-std today by providing your own implementation of the [HttpService](https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/aws-hyper/src/conn.rs#L98-L117) trait.
>
>If there's enough customer interest, we may consider providing first-class support, but it's worth noting that the workaround exists today. In the current SDK, you would still need to run a 1-threaded Tokio runtime to support retries (which have not yet been made runtime agnostic, although they are planned to be)

**Comment by jdisanti** [comment]
Multiple async runtime support is tracked in https://github.com/awslabs/aws-sdk-rust/issues/52. Sync API is tracked in https://github.com/awslabs/aws-sdk-rust/issues/505
