### ISSUE TITLE
[request]: Add support for pagination/streaming

### ISSUE THREAD

**Issue by jmklix** [awslabs/aws-sdk-rust#508]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **geekingfrog** June 10, 2021</sup>
There are many requests in many services which returns paginated responses. For example, ListObject or ListBuckets in S3, Scan in DDB and so on.

It would be really nice to have a unified way to provide a method which returns a [futures::stream](https://docs.rs/futures/0.3.15/futures/stream/index.html), or I guess, a `TryStream` since the items are likely to be `Results`.</div>

>Yes absolutely! We have an RFC design for paginators, would love your thoughts: https://github.com/awslabs/smithy-rs/discussions/346

**Comment by jdisanti** [comment]
Paginators have already been implemented.
