### ISSUE TITLE
Add Glue support

### ISSUE THREAD

**Issue by matthewmturner** [awslabs/aws-sdk-rust#510]
### Describe the feature

I would like an API for connecting to a Glue metastore.

### Use Case

I am working on [datafusion](https://github.com/apache/arrow-datafusion) and we recently enabled querying data on s3 with aws-sdk-rust.  As a next step we are looking to connect to a Glue Catalog as a metastore (more details [here](https://github.com/apache/arrow-datafusion/issues/2206)).

### Other Information

I didnt see Glue mentioned anywhere in any issues or on the Roadmap - so I presume it will be some time before it would be available but I wanted to get the request in anyway to gauge community interest and hopefully get it added to backlog.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
We do currently generate an [SDK for Glue](https://github.com/awslabs/aws-sdk-rust/tree/main/sdk/glue). Looking at [the docs](https://docs.rs/aws-sdk-glue/0.9.0/aws_sdk_glue/struct.Client.html#method.get_table), it does seem to support most of what you need. However, _(from a casual perusal)_ it doesn't seem like the Glue team has modeled a way to create "catalogs". It's not up to my team whether or not they'll implement that feature but I'd be happy to try and connect you with a PM on their team if you'd like to talk to them about it.

**Comment by matthewmturner** [comment]
@Velfi i apologize for missing that.  we can look into the functionality and report back with our findings!

thanks for your quick response!

**Comment by Velfi** [comment]
No problem, we aim to please 😄

**Comment by rcoh** [comment]
closing this for now—feel free to re-open if you discover the Glue client doesn't do what you need :-)
