### ISSUE TITLE
lambda create_function_url_config cor doesnt fully work

### ISSUE THREAD

**Issue by mrhoden-ghmc** [awslabs/aws-sdk-rust#515]
### Describe the bug

When creating a lambda function, I add a function url. I set cors to allow origins *. In the console I see everything set properly, but curling the function returns "Forbidden". In the console, I open the configuration of cors, change nothing and hit save, the url now works properly using a curl. 

### Expected Behavior

Function Cors should allow a curl to return output from the function url.

### Current Behavior

{"Message":"Forbidden"}

### Reproduction Steps

    let cors = Cors::builder() 
        .allow_origins("*".to_string())
        .allow_methods("*".to_string())
        .build();

    let result_url = client
        .create_function_url_config()
        .set_function_name(Some("foo-function".to_string()))
        .set_auth_type(Some(FunctionUrlAuthType::None))
        .set_cors(Some(cors))
        .send()
        .await?;

### Possible Solution

Seems like something in the console is setting a CORs value properly but the rust API for function CORS may only be partially implemented. 

### Additional Information/Context

I tried setting all variables in https://docs.rs/aws-sdk-lambda/0.10.1/aws_sdk_lambda/model/struct.Cors.html
and it doesnt seem to effect the outcome. Also tried "update_function_url_config" to see if the issue was only on "create_function_url_config" but no change in the result. 

### Version

aws-sdk-lambda = "0.10.1" aws-config = "0.10.1"

### Environment details (OS name and version, etc.)

Lambda Runtime "0.5.1" is being used to create second function

### Logs

curl -X POST https://b7**************.lambda-url.us-east-1.on.aws/ -H 'Content-Type: application/json' -d '***some json payload***'
{"Message":"Forbidden"}

**Comment by rcoh** [comment]
thanks, I'll look into this. By the way, you can also use the methods without `set_` that don't require wrapping in an option:
```rust
let result_url = client
    .create_function_url_config()
    .function_name("foo-function")
    .auth_type(FunctionUrlAuthType::None)
    .cors(cors)
    .send()
    .await?;
```

**Comment by calavera** [comment]
This is because you need to add the permissions to allow functionUrl invocations before calling that function. The console, and the aws cli do that for you, but sdks don't. I bumped into this problem last week, look at this code to learn how to do that:

https://github.com/cargo-lambda/cargo-lambda/blob/main/crates/cargo-lambda-deploy/src/lib.rs#L305-L328

**Comment by mrhoden-ghmc** [comment]
Thank you David! Adding the permissions to the Lambda Function allows the function url to invoke it. Code below. This issue can be resolved.

 lambda_client
        .add_permission()
        .function_name(lambda_function_name.to_string())
        .action("lambda:InvokeFunctionUrl")
        .principal("*")
        .statement_id("FunctionUrlAllowPublicAccess")
        .function_url_auth_type(FunctionUrlAuthType::None)
        .send()
        .await?;
