### ISSUE TITLE
Add Kinesis leasing strategy

### ISSUE THREAD

**Issue by lcmgh** [awslabs/aws-sdk-rust#518]
### Describe the feature

The Java KCL implements a leasing strategy with DynamoDB that takes care of orchestrating shards to worker nodes. As this is a pretty common use case I would love to see the same and an in-memory based strategy implemented in rust.

References:
* https://docs.aws.amazon.com/streams/latest/dev/shared-throughput-kcl-consumers.html

### Use Case

Users can focus on writing custom record-processing logic instead of solving complex tasks associated with distributed computing.

### Proposed Solution

* Provide a trait that leasing strategy implementors have to fullfil
* Implement the same sharding strategy the KCL is using
* Implement a in-memory sharding strategy for subscribers that do not need to scale with help of additional worker nodes.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jmklix** [comment]
Thanks for this suggestion, but we currently don't have any plans in the near future to add this to this sdk.
