### ISSUE TITLE
Support IMDSv1 for authentication

### ISSUE THREAD

**Issue by jszwedko** [awslabs/aws-sdk-rust#520]
### Describe the feature

When switching from `rusoto` to `aws-sdk-rust` for https://github.com/vectordotdev/vector, we realized there wasn't support for IMSDv1 for authentication.

I know IMDSv2 is preferred nowadays but we believe we are likely to still have users running without it.

Would you be open to a PR adding support for IMDSv1?

### Use Case

When IMDSv2 is unavailable, we'd like to fallback to trying IMDSv1.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
The plan is to fully remove IMDSv1 support so we actually can't provide support for it in the SDK at this time.

If you have customers currently on hosts that do not support IMDSv2 I'd be interested in hearing more about the cause.

In any case, it is possible to extend credential providers to add support–you can do it in an external crate by wrapping the default chain and adding a fallback to your own ImdsV1 implementation.
