### ISSUE TITLE
Rust docs failed to build for `aws-config` 0.11.0

### ISSUE THREAD

**Issue by jszwedko** [awslabs/aws-sdk-rust#526]
### Describe the issue

Sorry for the noise if you are already aware of this, but it looks like the docs failed to build for the latest release of the `aws-config` crate: https://docs.rs/crate/aws-config/0.11.0/builds

### Links

https://docs.rs/crate/aws-config/latest

**Comment by rcoh** [comment]
thanks for reporting! Looks like it's https://github.com/rust-lang/rust/issues/96429 which had a fix merged recently—I will retrigger a build in a couple of days

**Comment by Velfi** [comment]
[The fix PR](https://github.com/rust-lang/rust/pull/96447) isn't merged yet but I'm keeping an eye on it.

**Comment by rcoh** [comment]
fix was merged
