### ISSUE TITLE
Add support for EventBridge Global Endpoints

### ISSUE THREAD

**Issue by Armiixteryx** [awslabs/aws-sdk-rust#588]
### Describe the feature

EventBridge Global Endpoint is a new feature that allows setting up a backup event bus in other region as fallback when the principal region is down. [AWS Blog entry.](https://aws.amazon.com/blogs/compute/introducing-global-endpoints-for-amazon-eventbridge/)

### Use Case

When a region is down, Global Endpoint switch events automatically into the backup event bus in other region. This is useful to avoid service disruptions for a long period of time.

### Other Information

According from @jdisanti reply in this discussion https://github.com/awslabs/aws-sdk-rust/discussions/585#discussioncomment-3183562, this feature needs the AWS Common Runtime, a set of C libraries that are not supported in Rust yet.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
Thanks for filing this!

I did a little more digging, and it looks like this requires the AWS CRT in the other SDKs since it requires a SigV4a implementation, which currently is only provided in the CRT. So implementing this support will also require finishing #232.

**Comment by indykish** [comment]
@jdisanti  Hey team, is there an update on this? We see the SignV4a was merged.

Or any pointers on how to fix this will greatly be appreciated so we can give a hand.

**Comment by rcoh** [comment]
This works! This issue was just never closed. Closing now. If you run into any issues, please let me know, but I tested this yesterday for an unrelated project so I suspect all will be well.
