### ISSUE TITLE
signed_headers for presigned PUT urls?

### ISSUE THREAD

**Issue by penso** [awslabs/aws-sdk-rust#589]
### Describe the feature

I can't find a way to add signed headers when creating presigned URLs:

```Rust
    client
        .put_object()
        .bucket(&s3_config.bucket)
        .key(key)
        // .metadata("some-metadata", "abcd") <- that works for metadata
        // .signed_headers() <- nothing like this
        .presigned(expires_in.clone())
        .await?
```

I need the presigned urls to include those signed headers in the `X-Amz-SignedHeaders` url field as well as in the resulted requested `headers()` to let the client know it must include those when doing a direct upload. The Ruby implementation I had does it and need to replicate that in Rust.

I'm looking to sign the following headers: content-length content-md5 content-type Bhost

### Use Case

I need to ensure uploaded data is correct.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
To clarify, you want to enforce that the user of the presigned URL has to set these headers, and you don't know the values of those headers when creating the presigned URLs?

If you do know the values of those headers at creation time, you can set the [`content_length`](https://docs.rs/aws-sdk-s3/0.15.0/aws_sdk_s3/client/fluent_builders/struct.PutObject.html#method.content_length), [`content_md5`](https://docs.rs/aws-sdk-s3/0.15.0/aws_sdk_s3/client/fluent_builders/struct.PutObject.html#method.content_md5), and [`content_type`](https://docs.rs/aws-sdk-s3/0.15.0/aws_sdk_s3/client/fluent_builders/struct.PutObject.html#method.content_type) builder methods on the operation to have these headers included. Something like:
```rust
    client
        .put_object()
        .bucket(&s3_config.bucket)
        .key(key)
        .content_length(10)
        .content_md5("some-md5")
        .content_type("application/something")
        .presigned(expires_in.clone())
        .await?
```

I don't think we have support for just requiring the additional values though without their values being known.

**Comment by penso** [comment]
That's what I needed! I do have those values obviously (else you can't sign them I guess) but I was looking at a generic way of presigned headers instead of those specifics.
