### ISSUE TITLE
Support cargo workspaces?

### ISSUE THREAD

**Issue by evbo** [awslabs/aws-sdk-rust#597]
### Describe the feature

I have to upload many documents (csv) to S3 and so I thought I'd create a `lib.rs` that does the main business logic and then have several `main.rs` workspaces with implementation details such as the name of the file or bucket to upload to with other custom behaviors.

So in my root directory I have a cargo.toml with my workspaces listed as usual, and in each workspace I correctly list the dependency on the `lib.rs` workspace , but when I go to run:

`cargo clean && cargo lambda build --release --output-format zip `

Although it successfully builds, there is no `lambda` in release in the `target` folder of the root of the project.

So are workspaces not yet intended to be supported? If not, could they be given a spot on the backlog?

### Use Case

workspaces help cut down on build time tremendously and allow customizing behavior of reused code (from the `lib`).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
The AWS SDK for Rust doesn't have any opinion or requirements around cargo workspaces. Did you mean to create this issue on the [`cargo lambda`](https://github.com/cargo-lambda/cargo-lambda) project?

**Comment by evbo** [comment]
ah sorry I thought it was part of this one
