### ISSUE TITLE
New Service Support: SageMaker

### ISSUE THREAD

**Issue by FarhanTejani** [awslabs/aws-sdk-rust#61]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Add support for SageMaker

**Comment by alistaim** [comment]
Split into 4 services 

Sagemaker
Sagemaker A2I
Sagemaker Edge
Sagemaker Runtime

**Comment by alistaim** [comment]
Added two examples, one lists notebook details and one lists training job details.
