### ISSUE TITLE
Feature request: universal `DateTime` type across crates

### ISSUE THREAD

**Issue by allan2** [awslabs/aws-sdk-rust#613]
### Describe the feature

Can `DateTime` be universal across crates?

I've seen the [discussion on duplicate types](https://github.com/awslabs/aws-sdk-rust/issues/71) but it seemed to be more focused on service-related types.

### Use Case

It would be more evident to SDK users that all crates share a `DateTime` type.

~~Currently, conversions to other times via `DateTimeExt` only work on `aws_smithy_types` (https://github.com/awslabs/smithy-rs/issues/1688)~~
~~It would also be easier to add  `From` and `Into` (https://github.com/awslabs/smithy-rs/issues/1690)~~

### Proposed Solution

Use `aws_smithy_types::date_time::DateTime` as the universal type.

IMO it'd be nice to use `chrono` or `time` implementations as the universal type, but I am not sure how practical that is.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
The `DateTime` type in each individual SDK crate is just a re-export of the `DateTime` type in `aws_smithy_types`, so this should already work seamlessly. If it's not, the first thing you should check is that the `aws-smithy-types` and `aws-smithy-types-convert` dependencies in your `Cargo.toml` are the same versions that the SDK crate depends on. If they're not, then the Rust compiler isn't going to treat them as the same types.
