### ISSUE TITLE
Expose endpoint from SdkConfig

### ISSUE THREAD

**Issue by namse** [awslabs/aws-sdk-rust#618]
### Describe the feature

For now, `AwsEndpoint`'s `Endpoint` doesn't expose uri. it's only set-able, not get-able. I hope `Endpoint` has a function that return reference of uri.

### Use Case

I tried to return public object url not using presigned url.

### Proposed Solution

`rust 
// endpoint.rs
impl Endpoint {
  fn uri(&self) -> &Uri {
    &self.uri
  }
}
`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
For your use-case, do you want the top-level endpoint (e.g., `s3.us-east-1.amazonaws.com`), or the full _unsigned_ URL to the object?

**Comment by kastolars** [comment]
I'm interested in taking on this issue, might have some questions on it

**Comment by jdisanti** [comment]
@namse - I think `Endpoint` actually does have a getter here: https://docs.rs/aws-smithy-http/0.48.0/aws_smithy_http/endpoint/struct.Endpoint.html#method.uri

Were you looking for something else?

@kastolars - I really appreciate the offer! However, endpoints might not be the best place to contribute right now as we're doing a pretty large overhaul of the endpoint component of the SDK right now. If you're interested in contributing in general, you can take a look at our [contribution guide](https://github.com/awslabs/aws-sdk-rust/blob/main/CONTRIBUTING.md), and there's also a [list of good first issues](https://github.com/awslabs/smithy-rs/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) in our smithy-rs code generator. Contributions are welcome and I'm happy to help out!

**Comment by namse** [comment]
@jdisanti I found that uri getter is new at 0.48, and I used 0.47..! Thank you for information, I close this issue.
