### ISSUE TITLE
New Service Support: Lambda

### ISSUE THREAD

**Issue by stephenmuss** [awslabs/aws-sdk-rust#65]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Add support for Lambda

**Comment by msdrigg** [comment]
Is this request ticket only include the ability to create/update lambdas using rust? Or does this ticket also include support for a lambda runtime and the ability to write lambda functions in rust?

**Comment by rcoh** [comment]
This ticket is specifically for adding the `lambda` service for the Rust SDK. The lambda Runtime (https://crates.io/crates/lambda_runtime) is separate

**Comment by rcoh** [comment]
This has landed in smithy-rs and will go out in the next release. Thanks for voting everyone! 🎉

**Comment by stephenmuss** [comment]
Amazing turnaround. Thanks!

**Comment by rcoh** [comment]
🚢
