### ISSUE TITLE
`provide_credentials` span should be debug level

### ISSUE THREAD

**Issue by jdisanti** [awslabs/aws-sdk-rust#653]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/652

This should be a `debug_span`:
https://github.com/awslabs/smithy-rs/blob/374a0a25f83f5bae92bfac785cf783891bbb1937/aws/rust-runtime/aws-config/src/default_provider/credentials.rs#L73

**Comment by jdisanti** [comment]
This was included in [release-2022-12-14](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2022-12-14).

**Comment by jiashiwen** [comment]
hi

**Comment by jdisanti** [comment]
The `credentials cache miss occurred` is an info level log statement. If you don't want to see it, you can configure the log level for the `aws_credential_types` crate to be `warn`.
