### ISSUE TITLE
`receive_message` docs for attribute names do not line up with `QueueAttributeName` model

### ISSUE THREAD

**Issue by GeorgeHahn** [awslabs/aws-sdk-rust#655]
### Describe the issue

I'd like to use [`Client::receive_message`](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/client/struct.Client.html#method.receive_message) to receive a message along with metadata like `SentTimestamp`. This uses the [`attribute_names`](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/client/fluent_builders/struct.ReceiveMessage.html#method.attribute_names) builder function, which accepts a [`QueueAttributeName`](https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/model/enum.QueueAttributeName.html). The `Client::receive_message` documentation does not line up with the variants of that enum.

### Links

https://docs.rs/aws-sdk-sqs/latest/aws_sdk_sqs/client/struct.Client.html#method.receive_message

**Comment by Velfi** [comment]
Closing as a duplicate of #411 which is now being track for all SDKs here: https://github.com/aws/aws-sdk/issues/233
