### ISSUE TITLE
S3: Make it possible to determine when a get has failed due to a condition if specified

### ISSUE THREAD

**Issue by hkolbeck** [awslabs/aws-sdk-rust#656]
### Describe the feature

At present it seems to be impossible to determine whether a fetch failed due to a 304/412 or some other network error. There may be a way that I'm currently missing. This is necessary to make these functions on `GetObject` meaningful:

- `if_modified_since()`
- `if_unmodified_since()`
- `if_match()`
- `if_none_match()`

### Use Case

I would like use `if_modified_since()` to only fetch an object if there's a new version available.

### Proposed Solution

This is related to https://github.com/awslabs/aws-sdk-rust/issues/572, but for now I'd propose adding `NotModified` and `PreconditionFailed` to the `GetObjectErrorKind` enum.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @hkolbeck, thanks for uncovering this problem and taking the time to submit an issue. I'm going to reclassify this as a bug since we should already be supporting this use case.

**Comment by Velfi** [comment]
@DavidSouther do you have any time this week to create an example of how this should be working and check whether or not we actually support this somehow?

**Comment by DavidSouther** [comment]
I can prioritize this for the upcoming docs sprint - https://github.com/awsdocs/aws-doc-sdk-examples/issues/3918

**Comment by hkolbeck** [comment]
I put this down for a bit, and found that you can get the HTTP status code from the raw response packaged with the existing error, however that's not obvious and it would seem better to make it more easily checked for.

Here's what I landed on:

```rust
        match result {
            Ok(resp) => Ok(Some((resp.last_modified().cloned(), resp.body))),
            Err(SdkError::ServiceError{err, raw}) => {
                if raw.http().status() == StatusCode::NOT_MODIFIED {
                    Ok(None)
                } else {
                    Err(err.into())
                }
            },
            Err(err) => Err(err.into())
        }
```

**Comment by DavidSouther** [comment]
I've expanded this example in https://github.com/awsdocs/aws-doc-sdk-examples/pull/4031
