### ISSUE TITLE
New Service Support: EBS

### ISSUE THREAD

**Issue by Veetaha** [awslabs/aws-sdk-rust#66]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Add support for EBS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are developing a backup solution for the cloud, so we need to communicate with the EBS APIs to take EBS snapshots, attach and detach the block devices.

**Are you currently working around this issue?**
We've been using [`rusoto_ebs`](https://docs.rs/rusoto_ebs/0.46.0/rusoto_ebs/) crate for now.

**Comment by rcoh** [comment]
needs customization to explicitly disable signing the body
