### ISSUE TITLE
aws-sdk-lambda Environment Builder accepting an IntoIterator

### ISSUE THREAD

**Issue by nipunn1313** [awslabs/aws-sdk-rust#670]
### Describe the feature

https://docs.rs/aws-sdk-lambda/latest/aws_sdk_lambda/model/environment/struct.Builder.html

Currently, the `set_variables` accepts an `Option<HashMap>`.

It would be more ergonomic if it accepted (or had an option to accept) an `Option<IntoIterator<Item=(String, String)>>` so as not to limit inputs to just HashMaps. Eg BTreeMap.

### Use Case

Ergonomics of passing in environments.

### Proposed Solution

You could change the existing impl to an `IntoIterator` or add another broader implementation method that takes in an iterator.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @nipunn1313, this is an interesting request. Thanks for submitting it.

**Comment by ysaito1001** [comment]
The signature of `set_variables` is code-generated. While it's true that taking `impl IntoIterator<Item=(String, String)>` will make the API accept more types, we're not planning to update the codegen to implement that.
