### ISSUE TITLE
Cloudformation - DescribeStacksErrorKind only contains "Unhandled"

### ISSUE THREAD

**Issue by scottgerring** [awslabs/aws-sdk-rust#678]
### Describe the bug

The [DescribeStacksErrorKind](https://github.com/awslabs/aws-sdk-rust/blob/31cfae2cf23be0c68a47357070dea1aee9227e3a/sdk/cloudformation/src/error.rs#L3858-L3861) only contains the value "Unhandled", and it is necessary to match against the error string to decide how to respond to an error. For instance, a quick way to check if a stack exists is to use this call to list, filtering for the given stack name, and then checking that the error returned indicates the stack doesn't exist.

### Expected Behavior

The known responses to be parsed out and exposed as different `kind`s to avoid the caller having to do this themselves (like the other APIs?) 

### Current Behavior

Code like this:

```rust
return if e.to_string().contains("does not exist") {
                Ok(false)
            } else {
                // This is less great
               ...
            }
```

### Reproduction Steps

call DescribeStacks and try and parse the response

### Possible Solution

Parse the response out to the different types within the SDK

### Version

```text
0.21.0
```

### Environment details (OS name and version, etc.)

osx 12.5.1

**Comment by jmklix** [comment]
Thanks @scottgerring for creating this issue. This is a problem with the modeling of the cloudformation api. Because this effects all of the sdks I have opened a new github issue [here](https://github.com/aws/aws-sdk/issues/431) to track this and I will be closing this issue.

**Comment by jmklix** [comment]
Re-opening this issue to track it here. 

P76904203
