### ISSUE TITLE
New Service Support: Textract

### ISSUE THREAD

**Issue by jasonmccampbell** [awslabs/aws-sdk-rust#69]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
In particular, the DetectDocumentText and related page description data model.

**Comment by msuiche** [comment]
Just to say that this would be amazing, I'm currently trying to use `rusoto_textract` and can't tell what's an official doc/crate from a non official doc/crates

**Comment by rcoh** [comment]
It's supported: https://crates.io/crates/aws-sdk-textract
