### ISSUE TITLE
Documentation the EC2 SDK is missing

### ISSUE THREAD

**Issue by tschuett** [awslabs/aws-sdk-rust#691]
### Describe the issue

On https://crates.io/crates/aws-sdk-ec2, there is no documentation for the 0.22.0 release.

### Links

https://crates.io/crates/aws-sdk-ec2

**Comment by jdisanti** [comment]
It's still on [the docs.rs build queue](https://docs.rs/releases/queue). Docs.rs just hasn't caught up yet.

**Comment by tschuett** [comment]
Thank you for your help and giving me the SDK!
