### ISSUE TITLE
[request] Ability to specify creds at the request level

### ISSUE THREAD

**Issue by DanielBauman88** [awslabs/aws-sdk-rust#696]
### Describe the feature

Currently the AWS SDKs do not allow for creds to be specified at the request level, only at the client level.

### Use Case

There are many valid use-cases where a web service might want to make requests with different creds. A good example is a web service interacting with customer resources. Amazon recommends a pattern where the web service can use creds to isolate permissions to resources owned by the customer making the call ([talk](https://youtu.be/egskuX3YYO4?t=1627), [iam feature helping with federated creds](https://aws.amazon.com/blogs/security/simplify-granting-access-to-your-aws-resources-by-using-tags-on-aws-iam-users-and-roles/)).

The SDK clients handle tcp connection pooling which provides better performance and fewer higher-percentile spikes than you get  if you create a new client and new TCP connections on every call.

### Proposed Solution

It would be a benefit to SDK customers to support this use-case in the SDK by providing a mechanism to override the creds provider on a per-request basis so that customers using a federated connection model aren't hurt by needing to create a new sdk each time they want to change creds.

### Other Information

I'm asking this question in the aws-sdk-rust repo because the SDK I want this for is Rust, but this applies to the AWS SDKs more generally. As far as I know no sdk in any language supports a documented interface for this, but it can be achieved in some languages with looser controls like javascript.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @DanielBauman88, thanks for submitting this issue. We'll add it to our backlog.

@jmklix Can you follow up on whether we should add a copy of this issue to the cross-SDK issues repo?

**Comment by rcoh** [comment]
This is complete—You can use `config_override` to specify per-request credentials
