### ISSUE TITLE
should ConcurrentModificationException be included in AwsResponseRetryClassifier ?

### ISSUE THREAD

**Issue by michaetto** [awslabs/aws-sdk-rust#700]
### Describe the feature

should ConcurrentModificationException be included in AwsResponseRetryClassifier ?

### Use Case

retries

### Proposed Solution

include ConcurrentModificationException in THROTTLING_ERRORS for AwsResponseRetryClassifier

### Other Information

version aws-http 0.52

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
good question! we will investigate and get back to you. What operation are you using that's running into this issue?

**Comment by michaetto** [comment]
aws-sdk-eventbridge:

**Comment by jdisanti** [comment]
This doesn't strike me as an error that everyone would want to retry. It is possible to configure you're own retry classifier in order to have the client retry it for your use-case: https://docs.rs/aws-sdk-eventbridge/latest/aws_sdk_eventbridge/config/struct.Builder.html#method.retry_classifier

Going to close this.
