### ISSUE TITLE
missing SRP_A in Cognito ChallengeNameType

### ISSUE THREAD

**Issue by michaetto** [awslabs/aws-sdk-rust#702]
### Describe the feature

"SRP_A" challenge type is missing, one can only handle it via Unknown(crate::types::UnknownVariantValue)

### Use Case

cognito custom auth flow lambda triggers implementation

### Proposed Solution

add "SRP_A" SrpA to ChallengeNameType

### Other Information

aws-sdk-cognitoidentityprovider = "0.22"

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
thanks for filing this issue! this appears to be an issue in the upstream `CognitoIdentity` model. Assigning to @jmklix to triage and move to `aws-sdk`

**Comment by jmklix** [comment]
Opened new issues [here](https://github.com/aws/aws-sdk/issues/442). Closing this one
