### ISSUE TITLE
Add support for bearer authentication and SSO token providers

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#703]
### Describe the feature

Add support for bearer-token authentication & `sso-session`

### Use Case

these changes are required to support AWS Code Catalyst and the `smithy.api#httpBearerAuth` trait

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by goenning** [comment]
Is there a workaround for this? SSO sessions are becoming increasingly more popular. If not, any hints on what changes are necessary to have this implemented?

**Comment by Velfi** [comment]
We're working on this and we expect it to be complete at or before GA. I can't give a date for GA at this time.

**Comment by utkarshgupta137** [comment]
We're using it in a CLI tool right now. So I'm doing `aws configure sso` followed by `cargo run -p <crate> -- <args>`. Just reverting the versions worked for us. Not using it in any app.
Can you share the env/config for logging?

**Comment by rcoh** [comment]
https://github.com/awslabs/aws-sdk-rust/issues/703 just be careful to redact any sensitive data prior to sending

**Comment by rcoh** [comment]
cc @ysaito1001, I wonder if this is related to credentials caching changes. If you're preloading this doesn't seem to be related to the profile parse issue.

**Comment by rcoh** [comment]
do you use `credential_source` in your profile? If possible an anonymized version of your profile file would be very helpful

**Comment by rcoh** [comment]
ah! I found it—are you using `no-default-features`? You need to add `credentials_sso`

**Comment by utkarshgupta137** [comment]
> do you use `credential_source` in your profile? If possible an anonymized version of your profile file would be very helpful

Nope.

> ah! I found it—are you using `no-default-features`? You need to add `credentials_sso`

Yep, that fixed it. Would've been nice to have a better error message or a mention in the changelogs.

**Comment by rcoh** [comment]
yep I'm fixing the error as we speak, new error:
```
the credentials provider was not properly configured: ProfileFile provider could not be built: This behavior requires following cargo feature(s) enabled: credentials-sso 
```

**Comment by gyuho** [comment]
@rcoh We also ran into this error:

>"ProfileFile provider could not be built: profile `...` was not defined: `sso_region` was missing"

```
[profile ...]
sso_session = ...
sso_account_id = ...
sso_role_name = ...
region = us-west-2

[sso-session ava]
sso_start_url = https://....awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

**Comment by mohsen-alizadeh** [comment]
any update?

**Comment by jdisanti** [comment]
Sorry for the long delay in providing an update here. I'm working on adding this support now. It'll take a while, so I appreciate everyone's patience.

**Comment by akbog** [comment]
What's the timeline on this? This sso nonsense has been broken in aws sdks across the board for wayy too long

**Comment by rcoh** [comment]
work is ongoing: https://github.com/awslabs/smithy-rs/pull/2917

**Comment by vmaerten** [comment]
First of all, thanks for your hard work, this feature is highly appreciated!

Since the PR has been merged, do you have an ETA for the next release?

Thanks

**Comment by jdisanti** [comment]
Just to clarify, for that PR, it's making the existing credentials provider work with the latest CLI. It's not adding SSO token support to the AWS config/profile files (e.g., `~/.aws/credentials`). That will still require more work.

We should be releasing in the next 2-3 weeks.

**Comment by vaneek** [comment]
This also appears to be broken with Cloud9 using AWS managed temporary credentials.

$ cargo lambda deploy
Error:   × failed to create function role
  ├─▶ service error
  ├─▶ unhandled error
  ├─▶ unhandled error
  ╰─▶ Error { code: "InvalidClientTokenId", message: "The security token included in the request is invalid", request_id: "01406350-d28b-4873-a31c-4d64d0936b4a" }

**Comment by jdisanti** [comment]
This was resolved in error. Re-opening.

**Comment by nresare** [comment]
For people just looking for a workaround to be able to use `aws-sdk-rust` when using the currently recommended way to grant privileges to developers, [AIM Identity Center](https://aws.amazon.com/iam/identity-center/), you need the following:

1. Enable the `sso` feature in the aws-config create configuration in your `Cargo.toml`
2. Manually edit your `$HOME/.aws/config` to merge the contents of the profile you want to use with the referenced `sso-session`. This undoes the changes that are described in [this PR](https://github.com/aws/aws-cli/pull/7364)
3. Obtain new tokens using `aws sso login` and your web browser

This is a snippet that I use from my `Cargo.toml`:
```toml
[dependencies]
aws-config = {  version="0.57.1" , features = ["sso"]}
aws-sdk-sts = "0.35.0"
```

And these are the changes I made to my (anonymised) `$HOME/.aws/config`
```diff
--- config.old	2023-11-14 21:39:14
+++ config	2023-11-14 21:39:32
@@ -1,10 +1,8 @@
 [default]
-sso_session = s0
 sso_account_id = 87654321098
 sso_role_name = AdministratorAccess
 region = eu-north-1
 output = json
-[sso-session s0]
 sso_start_url = https://d-deadbeef.awsapps.com/start#
 sso_region = eu-north-1
 sso_registration_scopes = sso:account:access
```

Hopefully, teaching `aws-sdk-rust` the new style `$HOME/.aws/config` sso config with the `sso_session` is not too far off, and steps 2 and 3 will no longer be needed.

**Comment by athielen2** [comment]
Any timeline for this being implemented and released?

**Comment by rustrust** [comment]
Just ran into this, it would be great if this was resolved soon.

**Comment by Henkoglobin** [comment]
Where does everyone live? Do we want to get a beach house for a weekend [or something](https://xkcd.com/2881/)?

**Comment by jdisanti** [comment]
> Any timeline for this being implemented and released?

Can't give a timeline, but I'm picking up work on this again. Hopefully soon.

**Comment by jdisanti** [comment]
The [January 25th](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-01-25) release of the SDK includes support for `[sso-session]` in the AWS config file for SSO assume role credentials.

I'll continue working on SSO bearer token auth to support CodeCatalyst.

**Comment by RDarrylR** [comment]
Thanks a lot for this! I will check it out soon.

**Comment by bryantbiggs** [comment]
@jdisanti does that mean #699 is complete?

**Comment by jdisanti** [comment]
The bearer token support went out in [yesterday's release](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-03-13).
