### ISSUE TITLE
Filter builder negation

### ISSUE THREAD

**Issue by bryantbiggs** [awslabs/aws-sdk-rust#708]
### Describe the feature

Ability to negate a filter pattern to explicitly exclude it from the results

Here is one example using the AWSCLI where the user is requesting AMI IDs *except where the platform is windows

```sh
aws ec2 describe-images --image-ids ami-** --region us-east-2 --query 'Images[?Platform != `windows`]'
```

### Use Case

To be able to construct filters that will return all results *except those that match the filter

### Proposed Solution

(Pseudo-code)

```rs
let filter = Filter::builder()
    .set_name(Some("tag-key".to_string()))
    .set_values(Some(keys))
    .negate() // or perhaps .exclude() ? 
    .build();
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
@jmklix Can you confirm that it's not possible to set exclusionary filters when calling `DescribeImages`

@bryantbiggs Adding this would likely require a codegen customization on our part. We'd like to support this, but it's not going to be a priority for a while yet.

To whomever picks this issue up: How do other SDKs handle this?

**Comment by jmklix** [comment]
There are no exclusionary filters for `DescribeImages`, but as @bryantbiggs noticed you can manually build queries that exclude what you want.

**Comment by jmklix** [comment]
Sorry, but this is something that we don't have any plans to add to this sdk. We want to clearly communicate this, so I will be closing this issue.
