### ISSUE TITLE
aws-sdk-s3 v0.24 depends on rustls even when disabled

### ISSUE THREAD

**Issue by benesch** [awslabs/aws-sdk-rust#722]
### Describe the bug

`aws-sdk-s3` at v0.24 depends on `rustls`, even when the `rustls` feature is disabled and the `native-tls` feature is enabled instead.

### Expected Behavior

Cargo.lock does not include `rustls` and friends.

### Current Behavior

Cargo.lock includes `rustls` by way of `aws-smithy-client`:

```
[[package]]
name = "aws-smithy-client"
version = "0.54.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "17d44078855a64d757e5c1727df29ffa6679022c38cfc4ba4e63ee9567133141"
dependencies = [
 "aws-smithy-async",
 "aws-smithy-http",
 "aws-smithy-http-tower",
 "aws-smithy-protocol-test",
 "aws-smithy-types",
 "bytes",
 "fastrand",
 "http",
 "http-body",
 "hyper",
 "hyper-rustls",
 "hyper-tls",
 "lazy_static",
 "pin-project-lite",
 "serde",
 "tokio",
 "tower",
 "tracing",
]

[[package]]
name = "hyper-rustls"
version = "0.23.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1788965e61b367cd03a62950836d5cd41560c3577d90e40e0819373194d1661c"
dependencies = [
 "http",
 "hyper",
 "log",
 "rustls",
 "rustls-native-certs",
 "tokio",
 "tokio-rustls",
]
```

### Reproduction Steps

Create a simple crate that depends on `aws-sdk-s3` with `rustls` disabled and `native-tls` enabled:

```
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = { version = "0.24.0", default-features = false, features = ["native-tls"] }
```

### Possible Solution

The dependency sneaks in by way of the `aws-smithy-client/test-util` feature, which the `aws-sdk-s3` crate enables in its _production_ dependencies, as of 8e625fd ([diff](https://github.com/awslabs/aws-sdk-rust/commit/8e625fdb6096e5485b2b6d850c05545d97531c61#diff-af85cbe03dfb6935be39980f5f95b2a2b588adc5a075430dce0a3a4ba34bece2)). I'm not sure what's different about the S3 SDK, but for all other SDKs the `aws-smithy-client/test-util` is only enabled as a _dev_ dependency.

### Additional Information/Context

cc @rcoh

### Version

```text
v0.24
```

### Environment details (OS name and version, etc.)

n/a

**Comment by rcoh** [comment]
thanks for reporting—looking into this now
