### ISSUE TITLE
New Service Support: GameLift Server

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [awslabs/aws-sdk-rust#73]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Add AWS GameLift Server SDK support.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are trying to use AWS GameLift as a primary hosting platform for our game, which is written in Rust. Unfortunately, AWS GameLift requires using their server SDK, which is not available for Rust (even `rusoto` doesn't support it).

**Are you currently working around this issue?**
There is no available AWS GameLift Server SDK for Rust. The most suitable version is the C++ version. So for now we need to build the whole AWS GameLift Server SDK from scratch or use some kind of bindings to the existing C++ SDK.

**Additional context**
There is a related topic on AWS GameTech forum: https://forums.awsgametech.com/t/rust-and-aws-gamelift-server-sdk/10650/

Also, AWS GameLift team can provide original Protobuf files for implementing SDKs for other languages without reverse-engineering Protobuf schema from already generated sources in the published SDKs. Related link: https://github.com/neguse/gomelift/issues/1 There are several AWS GameTech threads about the same issue.

Not sure, should you implement it in this SDK or create a separate SDK - it should be discussed.

**Comment by rcoh** [comment]
The Rust SDK is only for generating clients from Smithy service models. Support for things like GameLift server would require a separate SDK. The GameLift API, however, is in scope: #72
