### ISSUE TITLE
XML parsing Error when sending GetBucketLifecycleConfiguration operation in s3-sdk

### ISSUE THREAD

**Issue by ysaito1001** [awslabs/aws-sdk-rust#730]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/721

<div type='discussions-op-text'>

<sup>Originally posted by **dfireBird** January 29, 2023</sup>
I recently updated from aws-sdk-s3 version from 0.52.0 to 0.54.0. After the upgrade I removed the deprecated `Endpoint` struct from the config and changed it to using the newer `endpoint_url` method. For context I use a locally hosted minio server for testing. But when I now run my project it throws an error when sending GetBucketLifecycleConfiguration operation with message:
```
    0: service error
    1: unhandled error
    2: unhandled error
    3: error parsing XML: encountered invalid XML root: expected LifecycleConfiguration but got StartEl { name: Name { prefix: "", local: "ListAllMyBucketsResult" }, attributes: [Attr { name: Name { prefix: "", local: "xmlns" }, value: "http://s3.amazonaws.com/doc/2006-03-01/" }], closed: false, depth: 0 }. This is likely a bug in the SDK.
```

The code for config before the update:
```rust
    let config = config::Builder::from(&env_config)
        .region(Region::new(app_config.s3_region()))
        .endpoint_resolver(
            Endpoint::immutable(app_config.s3_endpoint()).context("Invalid Enpoint resolver.")?,
        )
        .build();
```
and the code after the update:
```rust
    let config = config::Builder::from(&env_config)
        .region(Region::new(app_config.s3_region()))
        .endpoint_url(app_config.s3_endpoint())
        .build();
```
Here the `s3_endpoint` method both return a string and it's of form `http[s]://host:port`.

The code where the error is thrown:
```rust
let resp = client
        .get_bucket_lifecycle_configuration()
        .bucket(app_config.s3_bucket_name())
        .send()
        .await?;
```

I'm not sure how to open the bug report filling all the required field, so I opened a discussion forum, please guide me if I should open a bug report.</div>

**Comment by ysaito1001** [comment]
Thank you for reporting. It is likely you are running into [this](https://github.com/awslabs/aws-sdk-rust/issues/727), given that the testing server returns an unrelated `ListAllMyBucketsResult` response based on a `GetBucketLifecycleConfiguration` request. Could you verify that's the case?

**Comment by dfireBird** [comment]
I tried sending a request using Postman, the request sent was (protin-files is the bucket name):
```
GET /protin-files?lifecycle HTTP/1.1
Content-MD5: q6yJDlIkcBaGGfb3QLY69A==
Host: localhost:9000
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230203T185916Z
Authorization: <Authorization_Header>
User-Agent: PostmanRuntime/7.30.0
Accept: */*
Cache-Control: no-cache
Postman-Token: <Token>
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

and I got the response:
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 201
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 17406595F60513BB
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Fri, 03 Feb 2023 18:59:16 GMT
 
<LifecycleConfiguration><Rule><ID>protin-files-expiration-lifecycle</ID><Status>Enabled</Status><Filter><Prefix></Prefix></Filter><Expiration><Days>1</Days></Expiration></Rule></LifecycleConfiguration>
```

I feel the server is working fine here. If I made the request wrong or anything please guide me through what steps I should do? Thanks for helping.

**Comment by dfireBird** [comment]
Consider my above comment wrong. I just saw after the new update the endpoints that request made are changed. It should've been in this case `protin-files.localhost:9000`. So I made a updated request as:
```
GET /?lifecycle HTTP/1.1
Content-MD5: q6yJDlIkcBaGGfb3QLY69A==
Host: protin-files.localhost:9000
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230203T191811Z
Authorization: <Authorization_Header>
Signature=221922a68a6c826b648b81cb45ab4715908518c194646479f21813ac85bd581a
User-Agent: PostmanRuntime/7.30.0
Accept: */*
Cache-Control: no-cache
Postman-Token: <Token>
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```
and got the response:
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 370
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Request-Id: 1740669E3539DF5C
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Fri, 03 Feb 2023 19:18:11 GMT
 
<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><Buckets><Bucket><Name>protin-files</Name><CreationDate>2023-01-29T09:45:00.527Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>
```
which indeed does return `ListAllMyBucketsResult` response for a `GetBucketLifecycleConfiguration` request. So I guess the issue is with server I'm hosting on my local.

Do you have any suggestions for a workaround to fix this issue now that `Endpoint` struct is deprecated?

**Comment by jdisanti** [comment]
I think you need to set [`force_path_style`](https://docs.rs/aws-sdk-s3/0.24.0/aws_sdk_s3/config/struct.Builder.html#method.force_path_style) to `true` on the Client config.

**Comment by dfireBird** [comment]
Thanks that made it work. We can close this issue now that's it resolved.
