### ISSUE TITLE
CHANGELOG is difficult to relate to crate versions

### ISSUE THREAD

**Issue by jszwedko** [awslabs/aws-sdk-rust#731]
### Describe the issue

While the CHANGELOG is great at describing the changes including linking to pull requests, the fact that it uses dates rather than crate versions makes it difficult to understand which changes are in which crate release as you have to line up the tags with crate versions.

Would it be possible to use versions in the CHANGELOG instead?

### Links

https://github.com/awslabs/aws-sdk-rust/blob/66423e05991ee831696bc32fe3e452694cf0d231/CHANGELOG.md

**Comment by jdisanti** [comment]
I was just thinking this myself today. I think we should update the changelog generator to include the versions in an expand/collapse section.
