### ISSUE TITLE
Mark aws_sdk_rdsdata::client::Client::execute_sql as deprecated.

### ISSUE THREAD

**Issue by ThaddeusTreloar** [awslabs/aws-sdk-rust#740]
### Describe the issue

Calling:

```rust
let aws_config = aws_config::load_from_env().await;
let rds_client = aws_sdk_rdsdata::Client::new(&aws_config);

let result = rds_client.execute_sql()
        .db_cluster_or_instance_arn(some_arn_str)
        .aws_secret_store_arn(some_secret_arn_str)
        .sql_statements(some_sql_str)
        .database(some_db_str)
        .send()
        .await?;
```

Results in:

```rust
ServiceError(
  ServiceError { 
    source: ExecuteSqlError { 
       kind: BadRequestException(
          BadRequestException { 
            message: Some("This API is deprecated and not available. Use ExecuteStatement API instead")
  }
)
```

At runtime.

I am assuming that this is directly referring to `aws_sdk_rdsdata::client::Client::execute_sql` as calling `aws_sdk_rdsdata::client::Client::execute_statement` does not produce the same result.

If this is the case, making the function as deprecated in the documentation would be helpful.

### Links

https://docs.rs/aws-sdk-rdsdata/latest/aws_sdk_rdsdata/client/struct.Client.html#method.execute_sql

**Comment by Velfi** [comment]
Hey @ThaddeusTreloar, thanks for reporting this issue. I've submitted a fix [in this PR](https://github.com/awslabs/smithy-rs/pull/2386).

**Comment by ThaddeusTreloar** [comment]
Thanks @Velfi , I will mark this as closed!
