### ISSUE TITLE
State enums (ref aws_sdk_rds::model::DbCluster::status() ).

### ISSUE THREAD

**Issue by ThaddeusTreloar** [awslabs/aws-sdk-rust#742]
### Describe the feature

Although this directly refers to the above-mentioned case (aws_sdk_rds::model::DbCluster::status()), it would be excellent if state relevant permutations could be represented as an enum rather than raw strings.

### Use Case

During development if one is matching on such states it is helpful to know in advance, all possible states a service can be in. Or, in other cases, you don't have to go back and fix a problem caused by using the wrong case in a str ('creating' rather than 'Creating'). It also is particularly annoying where the possibles states aren't listed in the documentation anywhere as it makes it fairly difficult to handle edge cases, or even know what they may be.

### Proposed Solution

By using an enum instead of a &str to represent state you will have a compile time guarantee that all possible states are handled. You will also save time on documentation as enums are self-documenting.

Eg: 
`
enum DbClusterGroupState {
  Creating,
  Available,
  SomeEdgeCase
  ..
}
`

can then be matched via:
`
match aws_sdk_rds::some_retrieval_function().await?{
  DbClusterGroupState::Creating => do_something(),
  DbClusterGroupState::Available => do_something_else(),
  DbClusterGroupState::SomeEdgeCase => handle_edge_case(),
};
`

rather than:
`
match aws_sdk_rds::some_retrieval_function().await?{
  "creating" => do_something(),
  "available" => do_something_else(),
  _ => panic!("Unhandled edge case...")
};
`
or
`
// Will be caught during testing or deployment.
match aws_sdk_rds::some_retrieval_function().await?{
  "Creating" => do_something(),
  "Available" => do_something_else(),
  _ => panic!("Unhandled edge case...")
};
`

### Other Information

This obviously isn't limited to the described case but will still apply in similar situations.
I apologise if this is already on the list of todos as I understand the rust sdk is still in developer preview.
Thank you for your hard work, team!

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @ThaddeusTreloar, this is an issue with the model which we consume to generate the RDS SDK. I agree that the service team should probably be using an enum for this.

@jmklix Since this is a model issue, can you transfer this issue to the cross-SDK repo and follow up with the RDS team? Once you've done so, close this issue.

**Comment by jmklix** [comment]
new issue opened here: https://github.com/aws/aws-sdk/issues/481
closing this issue
