### ISSUE TITLE
S3 HeadObject is missing the presigned() method

### ISSUE THREAD

**Issue by lowsfer** [awslabs/aws-sdk-rust#753]
### Describe the feature

HeadObject needs a presigned() method, as the SDK for other (e.g. C++) languages can do it with GeneratePresignedUrl

### Use Case

I've been using it with C++ SDK but when I try to rewrite my project with rust, I can't do it.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
We're sort of tracking this in https://github.com/awslabs/aws-sdk-rust/issues/488. I'll investigate this week whether we can enable pre-signing for the `HeadObject` request.

**Comment by Velfi** [comment]
https://github.com/awslabs/smithy-rs/pull/2451

This PR will enable presigning support for `HeadObject`.

**Comment by ysaito1001** [comment]
Fix released in https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-03-30.
