### ISSUE TITLE
Regex Crate using Unicode

### ISSUE THREAD

**Issue by 0cv** [awslabs/aws-sdk-rust#772]
### Describe the feature

Many crates are using Regex such as `aws-sdk-appconfig`, `aws-sdk-appconfigdata`, `aws-endpoint`, `aws-sdk-ses` (and many more).

By default, Unicode tables are contained within the Regex crate, which increases notably the size of the compiled binary. It would be good if a flag could be passed to deactivate unicode tables when not needed, as mentioned in the Regex crate https://github.com/rust-lang/regex#crate-features

### Use Case

Decrease binary size when unicode is not needed.

### Proposed Solution

Add a feature flag at the `aws-*` crates level, that can change the features of the Regex crate.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by ysaito1001** [comment]
As part of https://github.com/smithy-lang/smithy-rs/pull/3269, the `regex` crate has been replaced by the `regex-lite` crate. The primary motivation for the PR was to reduce client initialization time at runtime, but it should also help reduce the size of the complied binary, as noted in https://github.com/rust-lang/regex/issues/961#issuecomment-1527512468.
