### ISSUE TITLE
impl ProvideErrorMetadata for [service]::Error

### ISSUE THREAD

**Issue by imp** [awslabs/aws-sdk-rust#780]
### Describe the feature

For each `service` (such as `dynamodb`, `ec2`, `iam`, etc)  there is `trait service::error::ProvideErrorMetadata` which is implemented for all the variants of the `service::Error`. However the `service::Error` itself does not implement this trait. It may be useful to provide this out of the box. Automatically generating this impl block should not be a problem as is it should just call a respective `.meta()` method on the inner error variant.

### Use Case

I am writing some error handling code and using `service::Error` is very convenient. Alas, after converting to this type I am loosing access to error details, and this makes general purpose diagnostic very hard.

### Proposed Solution

Here is example implementation for `aws_sdk_iam::Error` (very similar to how `RequestId` is implemented):

```
impl ProvideErrorMetadata for Error {
    fn meta(&self) -> ErrorMetadata {
        match self {
            Self::ConcurrentModificationException(e) => e.meta(),
            Self::CredentialReportExpiredException(e) => e.meta(),
            Self::CredentialReportNotPresentException(e) => e.meta(),
            Self::CredentialReportNotReadyException(e) => e.meta(),
            Self::DeleteConflictException(e) => e.meta(),
            Self::DuplicateCertificateException(e) => e.meta(),
            Self::DuplicateSshPublicKeyException(e) => e.meta(),
            Self::EntityAlreadyExistsException(e) => e.meta(),
            Self::EntityTemporarilyUnmodifiableException(e) => e.meta(),
            Self::InvalidAuthenticationCodeException(e) => e.meta(),
            Self::InvalidCertificateException(e) => e.meta(),
            Self::InvalidInputException(e) => e.meta(),
            Self::InvalidPublicKeyException(e) => e.meta(),
            Self::InvalidUserTypeException(e) => e.meta(),
            Self::KeyPairMismatchException(e) => e.meta(),
            Self::LimitExceededException(e) => e.meta(),
            Self::MalformedCertificateException(e) => e.meta(),
            Self::MalformedPolicyDocumentException(e) => e.meta(),
            Self::NoSuchEntityException(e) => e.meta(),
            Self::PasswordPolicyViolationException(e) => e.meta(),
            Self::PolicyEvaluationException(e) => e.meta(),
            Self::PolicyNotAttachableException(e) => e.meta(),
            Self::ReportGenerationLimitExceededException(e) => e.meta(),
            Self::ServiceFailureException(e) => e.meta(),
            Self::ServiceNotSupportedException(e) => e.meta(),
            Self::UnmodifiableEntityException(e) => e.meta(),
            Self::UnrecognizedPublicKeyEncodingException(e) => e.meta(),
            Self::Unhandled(e) => e.meta(),
        }
    }
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @imp, thanks for submitting this issue. This would increase crate file sizes but it seems worth it. We'll add it to our backlog.

**Comment by imp** [comment]
Perhaps fix for this could be implemented together with #784 (which was recently addressed by smithy-rs#2564).
It feels like both tickets belong to the same problem domain and could save a few cycles if addressed together.

**Comment by imp** [comment]
Hello, is there anything that could be done to help progress with this issue? (Short of submitting actual PR - I am not familiar with Kotlin).

**Comment by jdisanti** [comment]
Sorry for the delay on this. I've implemented the functionality in https://github.com/smithy-lang/smithy-rs/pull/3189

**Comment by jdisanti** [comment]
This will go out in the next release.

**Comment by jdisanti** [comment]
This went out with the [November 16th release](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-11-16).
