### ISSUE TITLE
Make `aws_sdk_polly::types::Voice` `Serialize`

### ISSUE THREAD

**Issue by attila-lin** [awslabs/aws-sdk-rust#795]
### Describe the feature

It can't be serialize

### Use Case

I want to serialize it through JSON to web end.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by ysaito1001** [comment]
Thanks @attila-lin for submitting a request. While `serde` is currently not supported in the Rust SDK, there is an ongoing community contribution to enable it behind the unstable feature flag ([RFC](https://awslabs.github.io/smithy-rs/design/rfcs/rfc0030_serialization_and_deserialization.html)).

One way around this limitation is to create an accompanying struct wrapping fields from `aws_sdk_polly::types::Voice` you wish to include and make that struct `#[derive(Serialize, Deserialize)]`.

```rust
#[derive(Serialize, Deserialize)]
struct Voice {
    // fields from `aws_sdk_polly::types::Voice` you need.
}
```
