### ISSUE TITLE
Copy command from S3 to Redshift

### ISSUE THREAD

**Issue by adlsh11** [awslabs/aws-sdk-rust#813]
### Describe the feature

The feature should achieve the same functionality of Python's copy command from S3 to Redshift.

Example in Python as below:
# Create a new table named "iris"
sql_query = """CREATE TABLE IF NOT EXISTS iris_3
               (
               sepal_length NUMERIC,
               sepal_width NUMERIC,
               petal_length NUMERIC,
               petal_width NUMERIC,
               species VARCHAR
               )
            """
execute_sql(sql_query, conn_string)

# Define S3 source file path
file_path = "s3://data-to-migrate/iris_dataset.csv"

# Copy data
sql_query = """
    COPY iris_3
    FROM '{}'
    IAM_ROLE '{}' 
    csv
    IGNOREHEADER 1
    ;
""".format(file_path, role_arn)
execute_sql(sql_query, conn_string)

### Use Case

I would like to expedite query execution time by moving away from Python to Rust, when it comes to data extraction and load. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @adlsh11, thanks for submitting this issue. We'll add it to our backlog but we won't be looking at tasks like this until after GA.

> _"tasks like this" refers to everything labeled "high-level-library" in GitHub._

**Comment by jmklix** [comment]
Closing this for now, as this isn't something that we plan on supporting in the near future.
