### ISSUE TITLE
Implement `into_paginator` for `aws_sdk_iam::client::Client::list_role_tags(&self)`

### ISSUE THREAD

**Issue by lcmgh** [awslabs/aws-sdk-rust#817]
### Describe the feature

Other builders such as `crate::operation::list_roles::builders::ListRolesFluentBuilder` implement `into_paginator`. `aws_sdk_iam::client::Client::list_role_tags(&self)` is lacking of that convenience method.

### Use Case

To fetch all role tags in one command.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
@lcmgh thanks for submitting this issue. We'll add it to our backlog.

**Comment by jmklix** [comment]
This is cross sdk feature request, so I have moved it to [here](https://github.com/aws/aws-sdk/issues/681)
