### ISSUE TITLE
aws_sdk_route53 has member function `type` that is a reserved word

### ISSUE THREAD

**Issue by eric-seppanen** [awslabs/aws-sdk-rust#826]
### Describe the bug

`aws_sdk_route53::types::builders::ResourceRecordSetBuilder` has a member fn called `type`. This seems unwise, as it's uncallable from Rust unless you use the obscure "raw identifiers" syntax:

```rust
let records = ResourceRecordSet::builder()
    .name(name)
    .type(RrType::Txt);
```

```txt
error: expected identifier, found keyword `type`
  --> src/foo.rs:56:6
   |
56 |     .type(RrType::Txt);
   |      ^^^^ expected identifier, found keyword
   |
help: escape `type` to use it as an identifier
   |
56 |     .r#type(RrType::Txt);
   |      ++
```

### Expected Behavior

I don't think idiomatic crates should use reserved words as the names of functions.

### Current Behavior

Trying to call `type` using normal syntax causes a compiler error.

### Reproduction Steps

See sample code above.

### Version

```text
aws-sdk-route53 v0.28.0
```

### Environment details (OS name and version, etc.)

Linux

**Comment by rcoh** [comment]
Unfortunately, we have to use the models given to us and do our best. I'm working with the rustdoc folks to see if we can generate better docs here that include the `r#` prefix.
