### ISSUE TITLE
Amazon EventBridge code bindings for Rust

### ISSUE THREAD

**Issue by brainstorm** [awslabs/aws-sdk-rust#829]
### Describe the feature

Currently the available code bindings for EventBridge schemas do not include Rust as a target language:

<img width="600" alt="Screenshot 2023-06-16 at 10 45 02 pm" src="https://github.com/awslabs/aws-sdk-rust/assets/175587/170b9e81-c8ce-409d-86ec-abd99b70b8f4">

<img width="1431" alt="Screenshot 2023-06-16 at 10 45 35 pm" src="https://github.com/awslabs/aws-sdk-rust/assets/175587/9f066fa8-f48d-476a-bdcc-7b5dca73ec9e">

/cc @mmalenic @reisingerf @victorskl

### Use Case

Our organization is developing a few microservices in different languages:

https://github.com/umccr/orcabus/

It's inconvenient that Rust bindings cannot be downloaded from the web console, but it would be super convenient to have those in any other way: perhaps it's possible via some `aws-sdk-rust` codegen?

### Proposed Solution

Provide a programmatic way to generate EventBridge schema code bindings for Rust.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @brainstorm, thanks for submitting this issue. We'll add it to our backlog.

**Comment by rcoh** [comment]
This is actually totally separate from the Rust SDK—this is an eventbridge feature.

**Comment by brainstorm** [comment]
Is there any way we can follow progress with the Eventbridge team on this one then?

**Comment by brainstorm** [comment]
Almost one year later it seems that the language bindings still exclude Rust @Velfi @rcoh, and we'll need pretty soon for our tests, I guess we'll have to generate them manually? :_/

![Screenshot 2024-05-03 at 9 39 47 PM](https://github.com/awslabs/aws-sdk-rust/assets/175587/6abf1c31-eaf1-4915-885e-f12d10f112f0)
