### ISSUE TITLE
[request] SDK for Amazon Verified Permissions

### ISSUE THREAD

**Issue by Velfi** [awslabs/aws-sdk-rust#837]
### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/835

<div type='discussions-op-text'>

<sup>Originally posted by **tatsuya6502** June 22, 2023</sup>
[Amazon Verified Permissions](https://aws.amazon.com/verified-permissions/) went GA on June 13, 2023 (Congratulations!) I am looking forward to having Rust SDK for it.

- https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-verified-permissions-generally-available/
- https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/making-api-requests.html#using-libraries</div>

**Comment by rcoh** [comment]
Released: https://crates.io/crates/aws-sdk-verifiedpermissions
