### ISSUE TITLE
S3 ListObjectsV2 query parameter

### ISSUE THREAD

**Issue by jpds** [awslabs/aws-sdk-rust#842]
### Describe the feature

I've looked at the documentation at https://docs.rs/aws-sdk-s3/0.28.0/aws_sdk_s3/operation/list_objects_v2/builders/struct.ListObjectsV2FluentBuilder.html and the examples provided in this repo, and I cannot see how I'd add a `--query` parameter to this API call as I would do the following with the Python CLI app:

```
aws --endpoint=$AWS_ENDPOINT s3api list-objects-v2 --bucket bucket-name --query 'Contents[?LastModified<`2023-07-01`].Key' --output=text
```

### Use Case

I'd like to directly ask the API to list all objects older than a week/year old without having to go through each individual object in a bucket and read their last-modified timestamp.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by ceffiro** [comment]
> The query parameter in the CLI is actually a higher level feature. We could consider adding a higher level library that included this functionality

Alright, but is there a way to use query params using the aws_rust_sdk right now?

**Comment by jmklix** [comment]
Thanks for this suggestion, but we currently don't have any plans in the near future to add this to this sdk.
