### ISSUE TITLE
Consider bumping the minor version of crates like aws-config when doing so for the SDK

### ISSUE THREAD

**Issue by abusch** [awslabs/aws-sdk-rust#845]
### Describe the feature

At the moment there are (at least) 2 different versioning schemes: one for the SDK itself (e.g. 0.28.0), and one for crates like `aws-config` (e.g. 0.55.3).

The problem is that crates like `aws-config` only get their `patch` number bumped when the SDK gets its `minor` version number bumped. This causes issues when running `cargo update` in a project.

### Use Case

Consider a project with the following dependencies:
```toml
aws-sdk-dynamodb = "0.27.0"
aws-config = "0.55.2"
```

Then run `cargo update` in your project. `aws-sdk-dynamodb` stays at version `0.27.0` (as it should per semver rules), but `aws-config` gets bumped to `0.55.3`, which ends up pulling in crates from the `0.28.0` version of the SDK. The project now accidentally depends on 2 different versions of the SDK.

### Proposed Solution

Bump the minor version number of crates that depends on the SDK when a new minor version of the SDK is released.

i.e. I think `aws-config` should have been released as `0.56.0` instead of `0.55.3`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by 1oglop1** [comment]
@Velfi Would you consider reopening this?

I'm having a really hard time updating and understanding the versioning of crates. 
On top of that, there seems to be a new `release-<date>` version tags 

the problem with that is there's no way to tell which of these packages are compatible with each other.
I needed a crate `aws-smithy-types-convert = 0.60.2` but after adding it I found it is not compatible with aws-config=1.1.1 so I need 1.1.2

but my project currently depends on 
```
aws-config = { version = "1.1.2", features = ["behavior-version-latest"] }
aws-types = "1.1.1"
aws-sdk-cognitoidentityprovider = "1"
aws-sdk-dynamodb = "1.9.0"
aws-sdk-s3 = "1"
aws-sdk-ssm = "1.9.0"
aws-sdk-sqs = "1.9.0"
aws_lambda_events = "0.13.0"
aws-smithy-types-convert = {version = "0.60.2", features = ["convert-streams"]}
```
And I spent a lot of time just trying to find the correct version combination. Every update of Rust AWS-SDK feels a bit like cracking the safe for the right combination.

https://github.com/awslabs/aws-sdk-rust/commit/49e8288f658719d287da50ee20c979fa955fd6cf

Or am I doing something wrong while trying to import this https://docs.rs/aws-smithy-types-convert/0.60.2/aws_smithy_types_convert/stream/trait.PaginationStreamExt.html 

Maybe a very simple solution would be just to version **everything** to a single version number.

**Comment by rcoh** [comment]
Can you give some more details about what you're seeing? I would expect smithy-types-convert to work with aws-config 1.1.1, seems like a bug if not.

In any case, each release includes a full listing of the crate versions in the pop-out tag: https://github.com/smithy-lang/smithy-rs/blob/fe36727499a7a74e42a2beca7e76d0b433871181/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/Util.kt#L121-L155

I think it's possible you just needed to run cargo update? _Generally_ you should only need to specify `"1"` for the stable crates. Cargo will pick up the latest available version. That's equivalent to listing out the version number as you have above.

Even if I force aws-config "1.1.1" with `aws-config = "=1.1.1"` aws-smithy-types-convert seems to compile OK?

**Comment by 1oglop1** [comment]
I needed a crate `aws-smithy-types-convert = 0.60.2` but after adding it I found it is not compatible with `aws-config=1.1.1` so I need `^1.1.2`.

I had similar problems pre 1.0 with different crates from SDK but I let it go since this issue was opened. 

Also a lot of `smithy code` seems to be not intended for direct usage, I'd rather have its components reexported via SDKs, so I do not need to make my code dependent on your internal library causing dependency headaches.
