### ISSUE TITLE
Handling failed conditional writes

### ISSUE THREAD

**Issue by Smotrov** [awslabs/aws-sdk-rust#847]
### Describe the feature

Amazon DynamoDB now simplifies and lowers the cost of handling failed conditional writes by providing a copy of the item as it was during the failed write attempt. 

Would be good to have it in the crate.

### Use Case

Previously, condition check errors in single write operations did not return a copy of the item in the event of a condition check error. A separate read request was necessary to get the item and investigate the cause of the error. Now with the ReturnValuesOnConditionCheckFailure parameter, DynamoDB error messages can include a copy of the item as it was during the write attempt at no additional cost.

### Proposed Solution

Implement additional attributes to `aws_sdk_dynamodb::operation::update_item::UpdateItemOutput`

Currently the Attributes map is only present **if the update was successful** and ReturnValues was specified as something other than NONE in the request. Each element represents one attribute. Despite the fact that now **ALL_OLD** should work even for failed conditional check. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hey @Smotrov, thanks for submitting this issue. We'll add it to our backlog.

**Comment by rcoh** [comment]
I believe this is implemented now: https://docs.rs/aws-sdk-dynamodb/0.29.0/aws_sdk_dynamodb/types/error/struct.ConditionalCheckFailedException.html#structfield.item

@Smotrov can you confirm and close the issue if I'm understanding correctly?
