### ISSUE TITLE
Generate documentation for the workspace

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [awslabs/aws-sdk-rust#848]
### Describe the feature

Generate a single source of documentaiton for all crates in the workspace.

It is easier to search through documentation when it is all indexed by the same filter.

See https://github.com/rust-lang/cargo/issues/8229 and https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#--index-page-provide-a-top-level-landing-page-for-docs.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by Velfi** [comment]
Hey @JonathanWoollett-Light, thanks for submitting this issue.

We provide something similar here: https://awslabs.github.io/aws-sdk-rust/
Is there something missing from that page that you'd like us to add?

**Comment by JonathanWoollett-Light** [comment]
While https://awslabs.github.io/aws-sdk-rust/ links to all the documentation it doesn't offer a unified search. This is the key feature that is valuable to me.

**Comment by rcoh** [comment]
We actually used to do this! Unfortunately the resulting index was over 400MB and was crashing browsers.

**Comment by JonathanWoollett-Light** [comment]
@rcoh Sounds like it could be an issue with rustdoc, I definitely think this should be able to be done.

**Comment by rcoh** [comment]
The issue is there are >12K individual APIs in the SDK—probably a more efficient search index could be built. But the issue is that since the search happens totally in browser, the entire search index has to be stored as JSON and compressed.

Rust Doc search was never really designed for a set of the crates as large as the AWS Rust SDK

**Comment by rcoh** [comment]
heh I just remembered the other issue—GitHub will only host files up to 100MB on Github pages websites. We'd have to deploy elsewhere.

**Comment by JonathanWoollett-Light** [comment]
@rcoh It should be relatively cheap to host with S3 e.g. https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html.

But searching the docs appears a much more difficult and blocking task, but could be quite an interesting task. I'm thinking it would be a PR on https://github.com/rust-lang/rust/tree/master/src/librustdoc to update how search is handled.

**Comment by jmklix** [comment]
As @rcoh mentioned GitHub has limitations on how big the docs can be, so we currently don't have any plans to do this. You can however generate the docs for your project with `cargo doc --workspace`.
