### ISSUE TITLE
wasm: aws-config uses fastrand, which needs a feature patch for WASM compatibility

### ISSUE THREAD

**Issue by simbleau** [awslabs/aws-sdk-rust#851]
### Describe the bug

To be fixed with #59.

Attempting to compile anything using `aws-config` on WASM will fail since it uses `fastrand`.

See the [`Cargo.toml`](https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/aws-config/Cargo.toml#L25).

`fastrand` has a dependency on `rand`, and `rand` uses `getrandom`. `getrandom` needs to be compiled with the `js` feature.

Fortunately, `fastrand` has the undocumented `js` feature flag to fix this for us. We just need to include it for wasm.

### Expected Behavior

Successful compile.

### Current Behavior

Fails to compile.

```text
14:35 simbleau on main ~ wasm-pack test --node
[INFO]: 🎯  Checking for the Wasm target...
   Compiling getrandom v0.2.10
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /Users/simbleau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:285:9
    |
285 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
286 | |                         default, you may need to enable the \"js\" feature. \
287 | |                         For more information see: \
288 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |________________________________________________________________________^
```

### Reproduction Steps

- Create a rust lib project.
- Include in cargo.toml deps: `aws-config = { version = "0.55", default-features = false }`
- Compile.

### Possible Solution

Here's the fix to the Cargo.toml:
```toml
[target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown"))'.dependencies]
fastrand = { version = "2", features = ["js"] }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown"))'.dependencies]
fastrand = "2"
```

### Version

```text
Main
```

### Environment details (OS name and version, etc.)

MacOS Ventura

**Comment by Velfi** [comment]
Hey @simbleau, thanks for submitting this issue. We'll add it to our backlog.

To whomever picks this one up: It looks like we should consider making the source of randomness configurable, just like we did for the async sleep impl and the time source.

**Comment by jdisanti** [comment]
`getrandom` is also an optional dependency for fastrand, so we could consider disabling it as well. I ran into other issues with `getrandom` last week and started removing it. I'll check to see if it's completely gone for the next release.

**Comment by jdisanti** [comment]
It looks like in the latest code, `rand` and `getrandom` are no longer pulled in, so this should be resolved with the next release.

**Comment by jdisanti** [comment]
I think you can work around this in the current release of aws-config by setting `no-default-features`.

**Comment by simbleau** [comment]
> I think you can work around this in the current release of aws-config by setting `no-default-features`.

By current release, do you mean 0.55?

If so, then that is not correct. I didn't have default features (in the reproduction steps).

**Comment by jdisanti** [comment]
Hmmm. OK, I didn't look into that thoroughly enough. I saw that our integration test for webassembly was depending on aws-config with no default features, and it is currently passing, but that may be a more recent development.

**Comment by jdisanti** [comment]
This has been fixed in the [August 3rd](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-08-03) release.
