### ISSUE TITLE
`RuntimeComponents` should be re-exported

### ISSUE THREAD

**Issue by jdisanti** [awslabs/aws-sdk-rust#862]
`RuntimeComponents` are required in order to implement custom interceptors, and they're not currently re-exported by the SDK crates.

**Comment by jdisanti** [comment]
PR to fix this: https://github.com/awslabs/smithy-rs/pull/2904

**Comment by jdisanti** [comment]
This has been fixed with the [August 23rd](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-08-23) release.

**Comment by rcoh** [comment]
fix verified
