### ISSUE TITLE
[request]: Compatibility with actix-web (v4)

### ISSUE THREAD

**Issue by blagovestb2c2** [awslabs/aws-sdk-rust#87]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**
Hello, I am trying to integrate this crate in an actix-web project. My cargo toml reads:

```toml
[dependencies]
aws-sdk-secretsmanager = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.4-alpha", package = "aws-sdk-secretsmanager"}
actix-web = "4.0.0-beta.6"
```

This results in a conflict.
```
error: failed to select a version for `futures-core`.
    ... required by package `smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.4-alpha#7683f759)`
    ... which is depended on by `aws-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.4-alpha#7683f759)`
    ... which is depended on by `aws-hyper v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.4-alpha#7683f759)`
    ... which is depended on by `aws-sdk-secretsmanager v0.0.2 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.4-alpha#7683f759)`
    ... which is depended on by `risk v0.1.0 (/redacted/)`
versions that meet the requirements `^0.3.14` are: 0.3.15, 0.3.14

all possible versions conflict with previously selected packages.

  previously selected package `futures-core v0.3.12`
    ... which is depended on by `actix-codec v0.4.0`
    ... which is depended on by `actix-http v3.0.0-beta.6`
    ... which is depended on by `actix-web v4.0.0-beta.6`
    ... which is depended on by `risk v0.1.0 (/redacted/)`

failed to select a version for `futures-core` which could resolve this conflict
```
I am not sure which crate I should post this to, but I'm posting it here since you're in alpha and you have the stricter version requirement.

**Are you currently working around this issue?**
How are you currently solving this problem?
I'm considering using rusoto in hopes of resolving the issue. I'd rather use what seems to be the future, i.e. this crate.

**Additional context**
Anything else we should know?
n/a

**Attachments**
n/a

**Comment by rcoh** [comment]
So this is a pretty weird error. `actix-codec` is depending on `^0.3.12` which is actually compatible. Is it possible you have a cargo.lock file preventing the upgrade? I can change our futures-core dependency to `0.3`, but I can't actually reproduce this issue so I'm not sure if that would fix it.

**Comment by rcoh** [comment]
I just hit this same error for an unrelated dependency locally and it cleared after deleting `Cargo.lock`. Can you try that and let me know if it resolves the issue for you?

**Comment by blagovestb2c2** [comment]
Deleting Cargo.lock and recompiling did it for me. Weird. Maybe something went wrong when switching branches
