### ISSUE TITLE
excessive logging during credential load

### ISSUE THREAD

**Issue by mattklein123** [awslabs/aws-sdk-rust#872]
### Describe the bug

With recent SDK versions I'm seeing:
```
[08-17-23 15:16:41.746Z 8 INFO tracing::span] lazy_load_credentials;
[08-17-23 15:16:41.746Z 8 INFO tracing::span] try_op;
[08-17-23 15:16:41.746Z 8 INFO tracing::span] try_attempt;
[08-17-23 15:16:41.849Z 8 INFO tracing::span] finally_attempt;
[08-17-23 15:16:41.849Z 8 INFO tracing::span] finally_op;
```

Every time a credential is loaded.

I can manually squelch `tracing::span` but am worried I might miss something else. Can these logs be dropped to debug or trace? Or is there a better way to squelch? Thank you.

### Expected Behavior

Logs as debug/trace level

### Current Behavior

Per above.

### Reproduction Steps

Use the default credential provider and load credentials.

### Version

```text
0.29
```

### Environment details (OS name and version, etc.)

MacOs/Linux

**Comment by jdisanti** [comment]
Thanks for reporting this!

**Comment by rcoh** [comment]
It would probably be handy to add a "logging volume regression test" — we can use the existing sensitive logging tests but instead track the total volume when run on `INFO` to catch future regressions.

**Comment by jdisanti** [comment]
A fix for this will go out in the next release.

**Comment by mattklein123** [comment]
Wow thank you for the fast turnaround!

**Comment by jdisanti** [comment]
This has been fixed with the [August 23rd](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-08-23) release.
