### ISSUE TITLE
Sesv2 API issues.

### ISSUE THREAD

**Issue by Sanjuvi** [awslabs/aws-sdk-rust#881]
### Describe the bug

The send_email method on the SesClient always fails to parse data, whether it's a simple string type or an EmailTemplate type. Even the official documentation on sending emails does not function as intended.It panics or consistently returns an error (Err). I'm uncertain about the issue that arises during the data parsing process. Please modify the API behavior, as I intend to experiment with template emails to complete the project.

### Expected Behavior

The compilation should either provide more information about the problem, such as additional context, instead of just generic errors. It either panics when calling unwrap on 'send' or returns an error when pattern matching. This situation can be extremely frustrating and often leads to **more frustration** than dealing with the Rust compiler itself. I would like to receive a successful message such as 'Emails have been sent successfully,' instead of dealing with compiler errors that occur 100 or 200 times.

### Current Behavior

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadRequestException(BadRequestException ```{ message: Some("Domain contains illegal character")```, meta: ErrorMetadata { code: Some("BadRequestException"), message: ```Some("Domain contains illegal character")```, extras: Some({"aws_request_id": "323f7d4e-e918-4e3c-8e96-fb3b08299f09"}) } })', src\main.rs:21:94
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\back-end.exe` (exit code: 101)

### Version

```text
aws-config = "0.56.0"
aws-sdk-s3 = "0.30.0"
aws-sdk-sesv2 = "0.30.0"
aws-credential-types = "0.56.1"
aws-types = "0.56.1"
```

### Environment details (OS name and version, etc.)

stable-x86_64-pc-windows-msvc (default)
 rustc 1.71.1 (eb26296b5 2023-08-03)
windows 11 
docker wsl

```send_message(&client,"MyList","sanjeevimani567@gmail.com","Testing","Hello Folks").await.unwrap();```
What is wrong with this code, which is from the [official documentation?](https://github.com/awslabs/aws-sdk-rust/blob/main/examples/examples/ses/src/bin/send-email.rs) I haven't received any errors regarding credentials, email identity, or the non-existence of the list. What could be the issue with those two strings?

Providing test examples will improve developer efficiency, instead of solely giving commands, and it will also aid in debugging.

**Comment by rcoh** [comment]
That code looks correct to me—are those the exact values that you're sending when you get an error. Is it possible that non-ascii characters are being included?

From the SES docs: https://docs.aws.amazon.com/ses/latest/dg/troubleshoot-error-messages.html
> There are non-ASCII characters in the email address—The email address string must be 7-bit ASCII. If you want to send to or from email addresses that contain Unicode characters in the domain part of an address, you must encode the domain using Punycode. Punycode is not permitted in the local part of the email address (the part before the @ sign) nor in the "friendly from" name. If you want to use Unicode characters in the "friendly from" name, you must encode the "friendly from" name using MIME encoded-word syntax, as described in [Sending raw email using the Amazon SES API](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html). For more information about Punycode, see [RFC 3492](http://tools.ietf.org/html/rfc3492).

Can you include logs to help us understand what's going on?

**Comment by Sanjuvi** [comment]
There's no problem anymore 😄😄

**Comment by rcoh** [comment]
🤷🏻 nice!
