### ISSUE TITLE
Can't configure `AssumeRoleProvider` to use the FIPS endpoints

### ISSUE THREAD

**Issue by jdisanti** [awslabs/aws-sdk-rust#882]
There's an issue in `aws-config` where the `AWS_USE_FIPS_ENDPOINT` environment variable isn't respected for the AssumeRoleProvider, and the `ConfigLoader::use_fips` value doesn't flow into the AssumeRoleProvider.

### Discussed in https://github.com/awslabs/aws-sdk-rust/discussions/880

<div type='discussions-op-text'>

<sup>Originally posted by **jszwedko** August 25, 2023</sup>
This came up through [an issue report on Vector](https://github.com/vectordotdev/vector/issues/18382) about it not using the FIPS endpoints when `AWS_USE_FIPS_ENDPOINT=true`.

</div>

**Comment by alex-rowe** [comment]
@jdisanti does this need to be raised in [smithy-rs](https://github.com/awslabs/smithy-rs) instead?

**Comment by jdisanti** [comment]
We try to track SDK issues in this repo, although sometimes they end up in smithy-rs.
