### ISSUE TITLE
Performance degredation with aws-config

### ISSUE THREAD

**Issue by ymwjbxxq** [awslabs/aws-sdk-rust#894]
### Describe the bug

I have noticed that Lambda Cold Start doubled if not replicated because of the update on the library 
`aws-config = "0.56"`

Before at `0.55 `it was all fine 

```
#[tokio::main]
async fn main() -> Result<(), Error> {
    setup_tracing();

    let timeout_config = TimeoutConfig::builder()
        .operation_timeout(Duration::from_millis(200))
        .operation_attempt_timeout(Duration::from_millis(50))
        .build();
    let retry_config = RetryConfigBuilder::new()
        .max_attempts(3)
        .initial_backoff(Duration::from_millis(25))
        .build();
    let config_dynamo = aws_config::from_env()
        .retry_config(retry_config)
        .timeout_config(timeout_config)
        .load()
        .await;

    let client_dynamodb = aws_sdk_dynamodb::Client::new(&config_dynamo);


    run(service_fn(|event: Request| {
        function_handler(&client_dynamodb, event)
    }))
    .await
}
```

The standard cold start time for DynamoDB has increased from around 140ms to over 350ms.

### Expected Behavior

The standard cold start time for DynamoDB has increased from around 140ms

### Current Behavior

Cold start time for DynamoDB has increased over 350ms

### Reproduction Steps

- create a Lambda
- run some executions
- check with Logs Insight

```
filter @type="REPORT" | fields greatest(@initDuration, 0) + @duration as duration, ispresent(@initDuration) as coldStart| stats count(*) as count, 
pct(duration, 5) as p5,
pct(duration, 10) as p10,
pct(duration, 25) as p25,
pct(duration, 50) as p50,
pct(duration, 75) as p75, 
pct(duration, 90) as p90,
pct(duration, 99) as p99, 
 max(duration) as max by coldStart
 ```

### Version

```text
aws-config = "0.56"
aws-sdk-dynamodb = "0.30"
```

### Environment details (OS name and version, etc.)

Lambda/ARM64/256MB

**Comment by rcoh** [comment]
thanks for reporting this—we'll investigate. Do you happen to have logs from both cases?

**Comment by ymwjbxxq** [comment]
with 0.55 that query (LogInsights)

p5: 128.02
p10: 128.02
p25: 128.02
p50: 129.45
p75: 138.36
p90: 138.9
p99: 157.9

with 0.56 that query (LogInsights)

p5: 226
p10: 255
p25: 323
p50: 433
p75: 528
p90: 578
p99: 658

**Comment by rcoh** [comment]
ah sorry I mean a cold start with `RUST_LOG=debug` with 55 and 56

**Comment by ymwjbxxq** [comment]
I cannot do it, sorry

**Comment by ymwjbxxq** [comment]
I changed the query to see just the Init Duration without executions, and it is consistent under 100ms with both versions.

So the issue is inside the Lambda execution, maybe due to aws networking latency.
