### ISSUE TITLE
Bedrock production support

### ISSUE THREAD

**Issue by prattcmp** [awslabs/aws-sdk-rust#913]
### Describe the feature

We need a production-ready Bedrock SDK for Rust.

### Use Case

We are building an ultra-fast LLM pipeline on Rust and, as a consequence, need a Bedrock SDK for Rust.

### Proposed Solution

I'm not sure what makes the current crate non-production-ready, but getting it to production-ready state is what we need.

https://crates.io/crates/aws-sdk-bedrock

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by ishaan-jaff** [comment]
Hi @prattcmp - I believe we can make this easier
I’m the maintainer of LiteLLM - we allow you to deploy an LLM proxy to call 100+ LLMs in 1 format - Bedrock, OpenAI, Anthropic etc https://github.com/BerriAI/litellm/tree/main/openai-proxy. 

If this looks useful (we're used in production)- please let me know how we can help.

## Usage 

Bedrock request
```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "bedrock/anthropic.claude-instant-v1",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

gpt-3.5-turbo request
```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

claude-2 request 
```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "claude-2",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

**Comment by prattcmp** [comment]
> Hi @prattcmp - I believe we can make this easier
> 
> I’m the maintainer of LiteLLM - we allow you to deploy an LLM proxy to call 100+ LLMs in 1 format - Bedrock, OpenAI, Anthropic etc https://github.com/BerriAI/litellm/tree/main/openai-proxy. 
> 
> 
> 
> If this looks useful (we're used in production)- please let me know how we can help.
> 
> 
> 
> ## Usage 
> 
> 
> 
> Bedrock request
> 
> ```shell
> 
> curl http://0.0.0.0:8000/v1/chat/completions \
> 
>   -H "Content-Type: application/json" \
> 
>   -d '{
> 
>      "model": "bedrock/anthropic.claude-instant-v1",
> 
>      "messages": [{"role": "user", "content": "Say this is a test!"}],
> 
>      "temperature": 0.7
> 
>    }'
> 
> ```
> 
> 
> 
> gpt-3.5-turbo request
> 
> ```shell
> 
> curl http://0.0.0.0:8000/v1/chat/completions \
> 
>   -H "Content-Type: application/json" \
> 
>   -d '{
> 
>      "model": "gpt-3.5-turbo",
> 
>      "messages": [{"role": "user", "content": "Say this is a test!"}],
> 
>      "temperature": 0.7
> 
>    }'
> 
> ```
> 
> 
> 
> claude-2 request 
> 
> ```shell
> 
> curl http://0.0.0.0:8000/v1/chat/completions \
> 
>   -H "Content-Type: application/json" \
> 
>   -d '{
> 
>      "model": "claude-2",
> 
>      "messages": [{"role": "user", "content": "Say this is a test!"}],
> 
>      "temperature": 0.7
> 
>    }'
> 
> ```
> 
> 
> 
> 
> 
> 

I like this idea, but we don't want to add another layer of cost or latency.

**Comment by ishaan-jaff** [comment]
@prattcmp thanks for the feedback -if we could minimize latency for the proxy would you use it ?

**Comment by prattcmp** [comment]
> @prattcmp thanks for the feedback -if we could minimize latency for the proxy would you use it ? 
> 
> 
> 
> 

We wouldn't pay for it, but if it were a well-maintained, open-source SDK, we might consider using it

**Comment by kellertk** [comment]
Hi @prattcmp, as you can tell, the AWS Rust SDK (and all of the client crates) are currently in Developer Preview. For anyone not sure what we mean when we say Developer Preview, check out https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html

What makes this Developer Preview and not GA is we're still developing this SDK. When we release things as GA, we are making certain backward compatibility guarantees that we don't have with Developer Preview. GA products are expected to be generally stable at both runtime and compile time. We're not ready for that with Rust yet.

I'm closing this issue because we won't have any more information to add here until we're ready to release the SDK.

**Comment by DuckyBlender** [comment]
So right now the Rust SDK doesn't support AWS Bedrock invocations?

**Comment by rcoh** [comment]
bedrock is fully supported

**Comment by DuckyBlender** [comment]
> bedrock is fully supported

Sorry my bad, I was using the `aws-sdk-bedrock` crate instead of the `aws-sdk-bedrockruntime` crate. Perhaps some examples should be made to clarify this?
