### ISSUE TITLE
Quotes in secret (may be user error)

### ISSUE THREAD

**Issue by rseymour** [awslabs/aws-sdk-rust#917]
### Describe the issue

When I retrieve a secret and print without debug, I find it returns `"secret"` instead of `secret`

I'm following the show secret example. I believe it's a JSON/not JSON situation. I'm using SAM to automatically create the secret.  I wish there was an auto-quote removal here, but that might cause even more issues.

### Links

https://docs.rs/aws-sdk-secretsmanager/latest/aws_sdk_secretsmanager/operation/get_secret_value/struct.GetSecretValueOutput.html#method.secret_string

**Comment by ysaito1001** [comment]
Hi @rseymour,

Thank you for bringing this up to our attention.

> I'm following the show secret example.

I assume you are referring to [our example for retrieving a secret string from our example repo](https://github.com/awsdocs/aws-doc-sdk-examples/blob/fb800b19a6e1ece5649157ff5015c8a38cd1742d/rust_dev_preview/secretsmanager/src/bin/get-secret-value.rs)? When I ran it, I got the output
```
Value: SecretValue
```
In my case, the secret manager stores just a plaintext string `SecretValue` (as opposed to Key/value) and when displayed without debug in the above example, it does not show quotes.

Maybe you could tell us more about what secret value you have in the secret manager and about how you run the reproduction steps where the output shows quotes around your secret value?
