### ISSUE TITLE
Remove dependency on tokio async executor

### ISSUE THREAD

**Issue by trevorstr** [awslabs/aws-sdk-rust#922]
### Describe the feature

I noticed that the AWS SDK documentation indicates that `tokio` is a requirement for AWS projects. However, there are other async crates, such as `smol`. I would suggest removing the hard dependency on tokio, or if there isn't one, then clarify in the documentation that other async executors can be used instead of tokio.

Affected document: https://docs.aws.amazon.com/sdk-for-rust/latest/dg/getting-started.html#hello-world

### Use Case

Each Rust project will have different requirements for dependencies.
Forcing dependency on one specific async executor crate is not a good practice IMO.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by igiona** [comment]
I, on the other hand, am not so in favor of N different implementations for the same thing.
This is probably the biggest drawback of rust.

It would be better if the community would stick to one implementation and put the efforts in properly maintaining and improving that one instead of creating the own maybe-better solution.

Best, imho, would be to have it in the rust core libraries. Especially for such essential things like async.

**Comment by jdisanti** [comment]
The Tokio requirement is all feature gated, so you can turn it off if you want. However, we haven't implemented support for any alternative executors, so you would have to do that work yourself in your application. We only require an async sleep implementation, and a HTTP connector that works with the alternate runtime.

**Comment by trevorstr** [comment]
> We only require an async sleep implementation, and a HTTP connector that works with the alternate runtime. 

@jdisanti Hmmm, good to know. Are there any docs stating these requirements in detail?

> Tokio requirement is all feature gated

Perfect.

**Comment by jdisanti** [comment]
I don't think there are docs for it currently. Best I can do is point you to our [alternate runtime S3 integration test](https://github.com/awslabs/smithy-rs/blob/main/aws/sdk/integration-tests/s3/tests/alternative-async-runtime.rs), but it doesn't exercise the alternate HTTP connector at all.

For the HTTP connector, you basically just have to ensure hyper works, or if hyper is incompatible with the alternate runtime, then replace it wholesale. We experimented with replacing hyper with surf when attempting to get async-std working, but it's not so easy. If hyper already works with your desired runtime, then it should be easy to get it working.

Here is the API for replacing the connector: https://docs.rs/aws-config/latest/aws_config/struct.ConfigLoader.html#method.http_connector

Something like:
```rust
let sdk_config = aws_config::from_env()
    .http_connector(my_connector)
    .sleep_impl(my_sleep_impl)
    .load()
    .await;
```

**Comment by jdisanti** [comment]
Also, here is @Velfi's original experiment with replacing hyper with surf: https://github.com/awslabs/smithy-rs/pull/1604

**Comment by jdisanti** [comment]
I'm going to close this since it's possible to replace the Tokio runtime in the SDK.
