### ISSUE TITLE
Support AWS IoT thing shadow rest API.

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-sdk-rust#943]
### Describe the feature

[AWS IoT thing shadow rest API.](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-rest-api.html)

### Use Case

Most IoT use case need this thing shadow feature.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by Velfi** [comment]
Hello @overheat. Because this API is unmodeled, we'd have to hand-write a crate for this. We likely won't get to this for a while, if ever. However, since it's a REST API, you can probably get pretty far constructing and sending HTTP requests manually using `reqwest`.

**Comment by jmklix** [comment]
We have decided this would need to be it's own sdk like the aws-iot-device-sdk's ([java-v2](https://github.com/aws/aws-iot-device-sdk-java-v2), [js-v2](https://github.com/aws/aws-iot-device-sdk-js-v2), [python-v2](https://github.com/aws/aws-iot-device-sdk-python-v2), and [cpp-v2](https://github.com/aws/aws-iot-device-sdk-cpp-v2)). This is not something that we currently have plans to do so I will close this issue
