### ISSUE TITLE
migration guide for aws-smithy-client

### ISSUE THREAD

**Issue by cetanu** [awslabs/aws-sdk-rust#952]
### Describe the issue

I'm updating some dependencies for an open-source project and they are using aws-smithy-client.

When I browse the docs for this crate, it shows that the crate is now empty and was deprecated some time ago.
However, I cannot find a corresponding guide for migrating away from using this crate. 

Can someone point me to such documentation, or an example of how to use some alternative in place of the now-removed crate?

### Links

https://docs.rs/aws-smithy-client/latest/aws_smithy_client/

**Comment by Velfi** [comment]
What is the open source project trying to do with the client? Could you share a link to it?

**Comment by jdisanti** [comment]
The changelogs for both aws-sdk-rust and smithy-rs should have information on breaking changes:
https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md
https://github.com/smithy-lang/smithy-rs/blob/main/CHANGELOG.md

**Comment by stmcginnis** [comment]
The example code also needs to be updated. It is currently broken with this change.

https://github.com/awslabs/aws-sdk-rust/blob/main/examples/examples/custom-root-certificates/src/main.rs#L7

**Comment by jdisanti** [comment]
Thanks for letting us know! It looks like it fell out of the Cargo workspace, so it wasn't getting picked up by CI. I filed an issue on the examples repo to fix it: https://github.com/awsdocs/aws-doc-sdk-examples/issues/5668

**Comment by cetanu** [comment]
The project is vector, there are usages such as this throughout the codebase: https://github.com/vectordotdev/vector/blob/master/src/sinks/aws_cloudwatch_logs/config.rs#L36-L50

I'll read through the provided docs and give it a crack at some point

**Comment by jmklix** [comment]
Please checkout the changelogs, or let us know if you have any other specific migration questions

> The changelogs for both aws-sdk-rust and smithy-rs should have information on breaking changes: https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md https://github.com/smithy-lang/smithy-rs/blob/main/CHANGELOG.md
