### ISSUE TITLE
`aws_sig_auth` successor

### ISSUE THREAD

**Issue by lcmgh** [awslabs/aws-sdk-rust#953]
### Describe the bug

What is the successor of https://docs.rs/aws-sig-auth/latest/aws_sig_auth/index.html ?

The doc of the now deprecated crate showed how to get signed tokens for RDS IAM auth. How can this be done now?

https://docs.rs/aws-sig-auth/0.56.1/aws_sig_auth/

### Expected Behavior

See above.

### Current Behavior

No docs and further hints.

### Reproduction Steps

-

### Version

```text
-
```

### Environment details (OS name and version, etc.)

macOS Montery

**Comment by jdisanti** [comment]
See #951
