### ISSUE TITLE
Confusing interface of `no_credentials()` for config

### ISSUE THREAD

**Issue by ivan-kiselev** [awslabs/aws-sdk-rust#971]
### Describe the bug

So, I am not quite sure it's a bug or intended, but I am trying to use locally running DynamoDB provided by NoSQL workbench for integration testing and general development loop, thus I need to connect SDK to the `http://localhost:8000` instance of DynamoDB. 

I tried to play with [no_credentials()](https://docs.rs/aws-config/latest/aws_config/struct.ConfigLoader.html#method.no_credentials) thing for a little while, but it doesn't really workout with the following error:
```
called `Result::unwrap()` on an `Err` value: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: NoMatchingAuthScheme, connection: Unknown } })
```

And in the same time, shall I introduce silly Credentials provider, it will work alright.

```Rust
use aws_sdk_dynamodb::config::Credentials;

fn create_my_credential_provider() -> Credentials {
    Credentials::new("example", "example", None, None, "example")
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    let cfg = aws_config::defaults(aws_config::BehaviorVersion::latest())
        .endpoint_url("http://localhost:8000")
        .region("eu-west-1")
        // .no_credentials() <- doesn't work
        .credentials_provider(create_my_credential_provider()) // <- works, but kinad silly and feels like should be covered by .no_credentials() instead
        .load()
        .await;

    let cfg = aws_sdk_dynamodb::Config::new(&cfg);
    let client = aws_sdk_dynamodb::Client::from_conf(cfg);
    let response = client.list_tables().send().await.unwrap();
    for table in response.table_names().iter() {
        println!("Found table {}", table)
    }
}
```

Now, as much as there's though seemingly silly, but robust workaround, it does feel that implementation of `.no_credentials()` is somehow incomplete and this use-case shall be covered by it.

As in, I, as a user of the sdk, when seen this method - it seemed natural for me to assume that it is exactly what I need, but somehow it was not.

Also, if I am doing something fundamentally wrong, I am happy to stand corrected.

### Expected Behavior

Either [no_credentials()](https://docs.rs/aws-config/latest/aws_config/struct.ConfigLoader.html#method.no_credentials)  on on `aws_config::ConfigLoader` removes any checks/validations for authentication from any client build with such config, or maybe it shall be renamed to something a bit more narrow if it was not the intent for the method. 

### Current Behavior

For dynamodb, at least, when building client with `.no_credentials()` config, one gets an error:
```
called `Result::unwrap()` on an `Err` value: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: NoMatchingAuthScheme, connection: Unknown } })
```

### Reproduction Steps

Run the following snippet with locally running DynamoDB
```Rust
#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    let cfg = aws_config::defaults(aws_config::BehaviorVersion::latest())
        .endpoint_url("http://localhost:8000")
        .region("eu-west-1")
        .no_credentials() <- doesn't work
        .load()
        .await;

    let cfg = aws_sdk_dynamodb::Config::new(&cfg);
    let client = aws_sdk_dynamodb::Client::from_conf(cfg);
    let request = client.list_tables().send().await.unwrap();
    for table in request.table_names().iter() {
        println!("Found table {}", table)
    }
}

```

### Version

```text
[dependencies]
aws-config = "1.0.0"
aws-sdk-dynamodb = { version = "0.39.0", features = ["behavior-version-latest"] }
tokio = { version = "1.34.0", features = ["full"] }
tracing-subscriber = "0.3.18"

```
```


### Environment details (OS name and version, etc.)

MacOS 14.1.1 (23B81) ❯ uname -a Darwin hehe.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64

### Logs

_No response_

**Comment by rcoh** [comment]
Dynamo isn't configured to work with no credentials (this is required to be modeled behavior). As the docs of `no_credentials` say, this is a very specific behavior that actually fully disables authentication (when allowed by the model).

Another option is [`Credentials::for_tests()`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/config/struct.Credentials.html#method.for_tests)

note that this will require enabling the `test-util` feature

**Comment by rcoh** [comment]
We should clarify the documentation of `no_credentials`, at the very least.

**Comment by ivan-kiselev** [comment]
Well, one would use absence of auth in testing purposes anyways, so enabling `test-util` is completely fine. 

Can confirm that [Credentials::for_tests()](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/config/struct.Credentials.html#method.for_tests) works just fine.

**Comment by jdisanti** [comment]
The [fix](https://github.com/smithy-lang/smithy-rs/pull/3279) for this has been merged and will go out in an upcoming release.

**Comment by jdisanti** [comment]
The fix for this went out in the [December 14th release](https://github.com/awslabs/aws-sdk-rust/tree/release-2023-12-14).
