### ISSUE TITLE
Compile-time check of inclusion of required parameters

### ISSUE THREAD

**Issue by ulf5** [awslabs/aws-sdk-rust#983]
### Describe the feature

It would be nice if compilation could fail when there are missing required parameters instead of during runtime:

e.g.:
```
use aws_config::meta::region::RegionProviderChain;
use aws_sdk_s3::Client;

#[tokio::main]
async fn main() {
    let region_provider = RegionProviderChain::default_provider().or_else("us-east-1");
    let config = aws_config::from_env().region(region_provider).load().await;
    let client = Client::new(&config);

    dbg!(client.get_object().send().await);
}
```

This compiles, but during runtime it fails due to missing required parameters of get_object (bucket and key).
The parameters are marked as "required: true" in the docs so the library seems to be aware of them being required.

### Use Case

It can be easy to forget even the most obvious required parameters, and it would be nice to not have to wait until runtime to notice.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by rcoh** [comment]
We have considered this in the past. Unfortunately given the requirements of backwards compatibility as new members are added + a reasonable compile times and error messages, we were unable to build a version of type-state builders that was sufficient to address these issues.

I'd like to see a Rust feature in the future we could use like, `must_call` where you could assert that a function must be called prior to the object being dropped, e.g.

Another linting tool would also be really helpful to address these—I agree it's not an ideal situation.

**Comment by djrodgerspryor** [comment]
A similar but distinct example is the recently added `BehaviorVersion` parameter which is now required to build a `aws_sdk_dynamodb::Client`. That crate version upgrade seemed to succeed, but failed in some of our runtime paths which require a (lazily constructed) dynamo connection for locking.

That seems like an easier case where backwards compatibility was broken anyway and it would have been nice to break it at compile time by making it a required additional parameter or similar.

**Comment by rcoh** [comment]
w/ the BehaviorVersion, it can come from other sources, e.g. `SdkConfig` (or by enabling the `behavior-version-latest` Cargo feature so we can't make it compile time required on the Config builder unfortunately.

**Comment by jmklix** [comment]
Thanks for this suggestion, but we currently don't have any plans in the near future to add this to this sdk.
