### ISSUE TITLE
Outdated `aws_smithy_runtime::client::http::hyper_014::HyperConnector` rustdoc example referencing `DefaultHttpsTcpConnector`

### ISSUE THREAD

**Issue by declanvk** [awslabs/aws-sdk-rust#986]
### Describe the issue

As the title says, there is a rustdoc referencing a non-existent type `DefaultHttpsTcpConnector` in:

https://github.com/awslabs/aws-sdk-rust/blob/3cb1d769a8a1ad02ec46ec1362d57b2bd67dad95/sdk/aws-smithy-runtime/src/client/http/hyper_014.rs#L132-L143

I think that instead this should be instead be something directly from the `hyper` crate, similar to what is used in the tests: 

https://github.com/awslabs/aws-sdk-rust/blob/3cb1d769a8a1ad02ec46ec1362d57b2bd67dad95/sdk/aws-smithy-runtime/tests/reconnect_on_transient_error.rs#L128-L130

### Links

 - https://docs.rs/aws-smithy-runtime/1.0.2/aws_smithy_runtime/client/http/hyper_014/struct.HyperConnector.html#examples

**Comment by jdisanti** [comment]
Thanks for reporting this! Working on a fix.

**Comment by jdisanti** [comment]
This will be fixed in an upcoming release.

**Comment by declanvk** [comment]
> This will be fixed in an upcoming release.

Thank you for the quick work!

**Comment by jdisanti** [comment]
The fix for this went out in the [December 14th release](https://github.com/awslabs/aws-sdk-rust/tree/release-2023-12-14).
