### ISSUE TITLE
[request]: Retry if the request fails with a TooManyRequestsError

### ISSUE THREAD

**Issue by gcrespi** [awslabs/aws-sdk-rust#99]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Tell us about your request**

[Automatic retries with backoff](https://docs.aws.amazon.com/general/latest/gr/api-retries.html) when the aws API fails with a TooManyRequestsError

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I'm building a rust script to get concurrently the version of several lambda functions pointed by a certain alias name.
The problem is some of these calls fails with a TooManyRequestsError and causes the whole script to fail.

**Are you currently working around this issue?**
The workaround I found so far is to turn down the level of concurrency with which I call the get_alias method, but this is not the best case for me and is also flaky.

**Additional context**
I'm using the aws-sdk-lambda version: v0.0.6-alpha

The TooManyRequestsError I get reads as follows:

```
Error: ServiceError { err: GetAliasError { kind: TooManyRequestsError(TooManyRequestsError { retry_after_seconds: None, r#type: Some("User"), message: Some("Rate exceeded"), reason: Some(CallerRateLimitExceeded) }), meta: Error { code: Some("TooManyRequestsException"), message: Some("Rate exceeded"), request_id: Some("****"), extras: {} } }, raw: Response { status: 429, version: HTTP/2.0, headers: {"date": "Wed, 02 Jun 2021 14:41:24 GMT", "content-type": "application/json", "content-length": "76", "x-amzn-requestid": "****", "x-amzn-errortype": "TooManyRequestsException"}, body: SdkBody { inner: Once(Some(b"{\"Reason\":\"CallerRateLimitExceeded\",\"Type\":\"User\",\"message\":\"Rate exceeded\"}")), retryable: true } } }
```

**Comment by rcoh** [comment]
This error actually is retriable. Would you mind turning on debug logging? I suspect that we're retrying here, but actually just running out of retries.

```rust
// Cargo.toml:
tracing-subscriber = "0.2.18

// in main:
tracing_subscriber::fmt::init();
```

then: `RUST_LOG='smithy_http_tower::dispatch=trace,smithy_http::middleware=trace'`

You should _hopefully_ see some spans that indicate that we're retrying those errors

**Comment by gcrespi** [comment]
@rcoh you are right!, there are retries before failing.
I will close this issue but first, I would like to ask you, how can I configure the number of retries and the exponential backoff parameters?
For example in the Java version of the sdk there is a RetryPolicy attribute on the ClientConfiguration, is there anything analogous here?

Thank you very much!

**Comment by rcoh** [comment]
It's not currently possible but please file an issue to request it :-)
