### ISSUE TITLE
Reading `Extensions` value from `Response` wrapper

### ISSUE THREAD

**Issue by declanvk** [awslabs/aws-sdk-rust#990]
### Describe the feature

I would like to be able to access the [`extension` field](https://docs.rs/aws-smithy-runtime-api/latest/src/aws_smithy_runtime_api/http/response.rs.html#76) of the [`Response` wrapper](https://docs.rs/aws-smithy-runtime-api/latest/aws_smithy_runtime_api/http/struct.Response.html#method.into_body).

The issue is that in an interceptor hook, I cannot use the [`try_into_http02x` method](https://docs.rs/aws-smithy-runtime-api/latest/aws_smithy_runtime_api/http/struct.Response.html#method.try_into_http02x) because it requires an owned value and the context will only return a [shared reference to the `Response`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/config/interceptors/struct.FinalizerInterceptorContextRef.html#method.response). Additionally, [`Response` does not implement clone](https://docs.rs/aws-smithy-runtime-api/latest/aws_smithy_runtime_api/http/struct.Response.html#), so I wouldn't be able to `response.clone().try_into_http02x()`.

### Use Case

I need this access so that I can read information like the [`HttpInfo`](https://docs.rs/hyper/0.14.27/hyper/client/connect/struct.HttpInfo.html) as part of an [`Intercept`](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/config/trait.Intercept.html) implementation that uses the [`read_after_attempt` hook](https://docs.rs/aws-sdk-dynamodb/latest/aws_sdk_dynamodb/config/trait.Intercept.html#method.read_after_attempt).

### Proposed Solution

I realize that directly exposing the [`http::Extension`](https://docs.rs/http/latest/http/struct.Extensions.html) doesn't make sense for a wrapper type where you are attempting to hide the `http` dependency.

Other options might be:
 - Implement `Clone` for the `Response` wrapper in a way that preserves the `extensions` value
 - Implement your own `Extensions` type that is compatible with `http`'s and then expose that type in a public interface

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jdisanti** [comment]
What problem are you trying to solve with the extensions? Maybe there's an alternative we can propose.

**Comment by rcoh** [comment]
We actually capture `http_info` in a generic way (and we use this internally).

We write [`CaptureSmithyConnection`](https://docs.rs/aws-smithy-runtime/latest/aws_smithy_runtime/client/http/connection_poisoning/struct.CaptureSmithyConnection.html) into the property bag: https://github.com/awslabs/aws-sdk-rust/blob/51f987bfd65e1d2d3de2124be5e8daa6ac598cdc/sdk/aws-smithy-runtime/src/client/http/connection_poisoning.rs#L76

[`ConnectionMetadata`](https://docs.rs/aws-smithy-runtime-api/1.0.3/aws_smithy_runtime_api/client/connection/struct.ConnectionMetadata.html) currently only exposes a narrow amount of information, but we could consider exposing more fields of HttpInfo

**Comment by declanvk** [comment]
> What problem are you trying to solve with the extensions? Maybe there's an alternative we can propose.

Mostly I need the `HttpInfo` data so that I can attempt to uniquely identify the TCP connection (using local + remote addr + port). I'd also like to have the remote addr information generally so that I can record number of unique hosts that I'm connecting to.

-----

> We actually capture http_info in a generic way (and we use this internally).

Thanks for the example! Apply that to my own case, would I also need to write a new `CaptureSmithyConnection` to both the request `extensions` and the interceptor `cfg`? Like in https://github.com/awslabs/aws-sdk-rust/blob/51f987bfd65e1d2d3de2124be5e8daa6ac598cdc/sdk/aws-smithy-runtime/src/client/http/connection_poisoning.rs#L57-L61

Or can I assume (with some tests) that a built-in smithy `Intercept` implementation will write this to the configuration for me?

If yes, then I would only need the `local_addr` information recorded into the `ConnectionMetadata` struct. Around https://github.com/awslabs/aws-sdk-rust/blob/51f987bfd65e1d2d3de2124be5e8daa6ac598cdc/sdk/aws-smithy-runtime/src/client/http/hyper_014.rs#L325-L332 would need to pull out the `local_addr` from the `HttpInfo`.

**Comment by declanvk** [comment]
I do think that you might still want to implement `Clone for Response`, otherwise the `try_into_http02x` will not be useful for any `Intercept` hooks. Maybe something similar to the [`Request::try_clone`](https://docs.rs/aws-smithy-runtime-api/latest/aws_smithy_runtime_api/http/struct.Request.html#method.try_clone) and keep the warning on it that says that it will clear the `extensions` field?

It wouldn't be useful for my case, but it might make the interface more flexible for someone else.

**Comment by jdisanti** [comment]
@declanvk contributed a change to smithy-rs that will solve their problem in https://github.com/smithy-lang/smithy-rs/pull/3286

Accessing http extensions is not something we would like to support unless there is a very compelling reason for it, so I'm going to close this for now.
